### ISSUE TITLE
Bandwidth

### ISSUE THREAD

**Issue by calledit** [mossmann/hackrf#101]
Why does the hackrf and sdr devices in general limit the incoming bandwidth.
If one can capture 2GHz why would the same capture not also contain all the lower rf to?

**Comment by milahu** [comment]
i am slightly puzzled by the combination of 

* 1 MHz to 6 GHz operating frequency
* up to 20 million samples per second

but then i remember: the hackrf one is no oscilloscope but a radio transceiver / tuner

is this a correct summary .... ?

* sample rate = 20MSPS
* bandwidth = 20MHz ["the HackRF does complex sampling, where sampling rate = bandwidth"]<br/>in contrast to "direct sampling" <br/>where the "nyquist shannon sampling theorem" would limit the bandwidth <br/>to only 8MHz to 10MHz = factor 2.5 to 2.0
* frequencies above 20MHz can be received/transmitted,<br/>but then you dont access the "full spectrum" from (f_min = 1MHz) to f_max,<br/>but you have a "frequency window" from (f_max - 20MHz) to f_max,<br/>in other words: from (f_tune - 10MHz) to (f_tune + 10MHz).<br/>just like a frequency upconverter/downconverter will shift [not scale] the spectrum.
* to access frequencies below 1MHz, you need a frequency upconverter
  * NooElec Ham It Up Plus - range 300Hz to 65MHz - offset 125MHz
  * NooElec Ham It Up v 1.3 - range 100kHz to 60MHz - offset 125MHz

captain obvious was here
