### ISSUE TITLE
Question: Some Specifications are Missing in the BOM

### ISSUE THREAD

**Issue by Detmud** [mossmann/hackrf#102]
Hello,

I want to build a HackRF but I have some Problems with your BOM.

1.)  U26 - SOT23-5 - RF_LDO 
What is V_in What is V_out ?

2.) U3 - GSG-LP0603 - RX_LOWPASS_FILTER
Which frequency ?
http://www.avx.com/docs/catalogs/lp0603.pdf

3.) U8 - GSG-HP-DEA - RX_HIGHPASS_FILTER
Which frequency ?

**Comment by afiskon** [comment]
@mossmann  This is still an actual issue. I tried to find a replacement component for U8 and couldn't. Having a complete BOM would be great, for an open-hardware project...

**Comment by miek** [comment]
The BOM is complete, make sure you include the manufacturer and part number fields when you export it:

<img width="921" height="545" alt="Image" src="https://github.com/user-attachments/assets/1191f5fd-8bef-4a36-a778-9c95044e4efc" />
