### ISSUE TITLE
HackRF One RX spectrum

### ISSUE THREAD

**Issue by scateu** [mossmann/hackrf#109]
I use a  walkie talkie to transmit 455.550MHz signal.

on version f9ffe90 , 

```
osmocom_fft -f 455M
```

![good](https://f.cloud.github.com/assets/533192/2248140/f2f67922-9d75-11e3-878d-ab677e40848f.png)

but when using firmware on latest version 7f34c6c,

![bad](https://f.cloud.github.com/assets/533192/2248159/08cb57fe-9d76-11e3-9aa7-a3cf05a4cb28.png)

I think the IQ was swapped, actually in gqrx, I can enable "Swap I/Q" to temporarily "fix" it.

**Comment by palaksyi** [comment]
May I know how can I get the IF or LO frequency? IF is a fixed frequency right. Based on RF frequency we tune to PLL gives right LO frequency to get the required IF frequency. 
Is the function 'hackrf_rffc5071_read' provided the LO frequency ? If so what is the value for the parameter 'register_number'?
If I am wrong, please correct me.
Awaiting for your valuable comment.

Thanks & Best Regards,
Yeshaswini
