### ISSUE TITLE
CPLD update fails on Windows

### ISSUE THREAD

**Issue by mossmann** [mossmann/hackrf#113]
We don't know why yet.  As a workaround, use Linux to perform the update.

**Comment by dominicgs** [comment]
@supersat Do you still have the code for this?  I tried writing a version but the first bulk transfer fails.  I'm investigating why, but if you're willing/able to share your solution, that would make things quicker.

**Comment by supersat** [comment]
Yep: http://pastebin.com/tgeD8Zrf

**Comment by dominicgs** [comment]
@supersat Thanks!  I was failing to initialise the endpoint.

I've created PR #186 to fix this based on the above pastebin/patch.

**Comment by dominicgs** [comment]
PR #186 was merged and was included in the 2015.07.2 release.
