### ISSUE TITLE
Full-Duplex support on single HackRF

### ISSUE THREAD

**Issue by msva** [mossmann/hackrf#114]
Hi there!
I just wondered, is it any plans to make full-duplex (and single-board) versions of HackRF-devices? ;)

**Comment by Montilien** [comment]
Hi,
would you have somme project to use HackRF as RF test equipment? I think at a simple wobbulator using HackRF as sweeper and an external RF log detector to detect level vs frequency. This is the minimal configuration to do RF response curve and SWR testing also.?
