### ISSUE TITLE
hackrf_transfer ppm support

### ISSUE THREAD

**Issue by scateu** [mossmann/hackrf#116]
perhaps we need a ppm correction argument for hackrf_transfer or hackrf.c

**Comment by uhwsin** [comment]
https://github.com/mossmann/hackrf/issues/230

**Comment by dominicgs** [comment]
The `-C ppm` argument handles this now.

**Comment by paranoidninja** [comment]
Hi, I tried to use the -C option. My ppm crystal is 39.144. But it gives and invalid option when I use -C with hackrf_transfer... Am I missing something?

![image](https://user-images.githubusercontent.com/21009111/33522964-24695680-d820-11e7-8b3c-0be9b05b44b8.png)
