### ISSUE TITLE
Usage of old Version of DFU-Tool

### ISSUE THREAD

**Issue by Detmud** [mossmann/hackrf#117]
Hello,
you are using a older version of the DFU-Tool.
You can see here [https://github.com/mossmann/hackrf/blob/master/firmware/common/Makefile_inc.mk#L13](https://github.com/mossmann/hackrf/blob/master/firmware/common/Makefile_inc.mk#L13) that you're using the option -s.

As you may see in the [official Repo](https://gitorious.org/dfu-util/dfu-util), this option ist not used any more (2014) https://gitorious.org/dfu-util/dfu-util/source/fc81c6cc4eba30eaadf0010deb3d38f3be93ecd1:src/suffix.c#L52

So I tried to find a version with this option.
It seems like you are using an older (2012) version [https://github.com/Stefan-Schmidt/dfu-util](https://github.com/Stefan-Schmidt/dfu-util)  ... with this version all your scripts and manuals are working quite fine. The problem is that this version isn't developed anymore.

Both versions are version 0.7 so this problem gets even worse.
A clarification would be very nice.

**Comment by hessu** [comment]
To get hackrf firmware compiled, I cloned dfu-util sources from gitorious, then checked out the v0.7 tag, and compiled & installed from there. libusb-1.0 is required for building it.

    sudo apt-get install libusb-1.0-dev
    git clone https://gitorious.org/dfu-util/dfu-util.git
    cd dfu-util
    git checkout -b v0.7 v0.7
    sh autogen.sh 
    make
    sudo make install

**Comment by felipebalbi** [comment]
I have this issue with dfu-util from debian sid (0.8)

**Comment by liubenyuan** [comment]
OIC, maybe only `dfu-util 0.7` works with hackrf one.

**Comment by itsbert** [comment]
The source code for dfu-util has moved to sourceforge and the release branches are not listed any more but the following works if you need 0.7:
git clone git://git.code.sf.net/p/dfu-util/dfu-util
cd dfu-util
git log --grep "Release 0.7"
git checkout 4e312c5567a84f76654295c267ec35f71727fe5a
sh autogen.sh 
make
sudo make install

But the cmake change by  russm above is probably better.to use.

**Comment by stiege** [comment]
It completed itsbert's instructions but I'm still getting CRC warnings and a bricked device:
```
stiege@spyro:~/projects/hackrf/firmware/build/hackrf_usb$ dfu-util -D hackrf_usb.dfu
dfu-util 0.7

Copyright 2005-2008 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2012 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

Opening DFU capable USB device... ID 1fc9:000c
Run-time device DFU version 0100
Claiming USB DFU Runtime Interface...
Determining device status: state = dfuIDLE, status = 0
WARNING: Runtime device already in DFU state ?!?
Found Runtime: [1fc9:000c] devnum=0, cfg=1, intf=0, alt=0, name="DFU"
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0100
Device returned transfer size 2048
DFU CRC does not match
Warning: File has no DFU suffix
bytes_per_hash=409
Copying data from PC to DFU device
Starting download: [##################################################] finished
```

**Comment by dominicgs** [comment]
Could you post the output from the firmware build?  That output suggests that the DFU file is missing a suffix, which implies that the build did not work correctly.

**Comment by stiege** [comment]
```
stiege@spyro:~/projects/hackrf/firmware/build/hackrf_usb$ make all
[  7%] Built target hackrf_usb_m0.elf
[  7%] Built target hackrf_usb_m0.bin
[100%] Built target hackrf_usb.elf
[100%] Built target hackrf_usb.bin
dfu-suffix (dfu-util) 0.7

(C) 2011-2012 Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

No valid DFU suffix signature
Not valid TI Stellaris DFU prefix
TI Stellaris DFU prefix added.
New DFU suffix added.
[100%] Built target hackrf_usb.dfu
```

**Comment by stiege** [comment]
I used the dfu from the website to unbrick my device. Good enough fix for me...

**Comment by dominicgs** [comment]
As PR #229 has now been merged, we are able to build .dfu files using either dfu-util 0.7 or 0.8+.  Anything less than 0.7 will require an upgrade, but most distros are now shipping one of these two releases.
