### ISSUE TITLE
incorrect value in baseband filter table?

### ISSUE THREAD

**Issue by sgstair** [mossmann/hackrf#145]
I see a 2.5MHz value used for the second baseband filter value in the host/device code, but the MAX2837 datasheet specifies that it's 2.25MHz

**Comment by mossmann** [comment]
I agree that there is no need to fix this. I believe I measured the filter bandwidth once, and it wasn't particularly close to either 2.25 MHz or 2.5 MHz.  We can call it 2.5 MHz.
