### ISSUE TITLE
hackrf_transfer stops writing at 2GiB-1Byte under a 32bit OS

### ISSUE THREAD

**Issue by itsbert** [mossmann/hackrf#152]
It took me a while to work this out.
I created a filesystem with "mkfs.ext3 -b 4096 -L ext3 /dev/sda1" which should allow a maximum file size of 2TiB. I created a 4GB file with "dd if=/dev/urandom of=testfile bs=65536 count=65536" to confirm that the OS had no problem writing a file larger than 2GiB-1Byte, and it does not.

Then I started to think that maybe the problem was with the file creation functions in hackrf_transfer, but fopen , fwrite and fclose looked fine to me, and then eventually I found this link:
https://stackoverflow.com/questions/730709/2gb-limit-on-file-size-when-using-fwrite-in-c

Can fopen64 be used instead of fopen to allow the creation of files larger then 2GiB-1Byte if compiled on a 32bit OS (ARM) ?

EDIT: It works and I would submit a patch, but I get a three warning messages that I have no idea how to get rid of, programming ain't my bag.
[100%] Building C object src/CMakeFiles/hackrf_transfer.dir/hackrf_transfer.c.o
/root/src/hackrf/host/hackrf-tools/src/hackrf_transfer.c: In function ‘main’:
/root/src/hackrf/host/hackrf-tools/src/hackrf_transfer.c:789:4: warning: implicit declaration of function ‘fopen64’ [-Wimplicit-function-declaration]
    fd = fopen64(path, "wb");
    ^
/root/src/hackrf/host/hackrf-tools/src/hackrf_transfer.c:789:7: warning: assignment makes pointer from integer without a cast
    fd = fopen64(path, "wb");
       ^
/root/src/hackrf/host/hackrf-tools/src/hackrf_transfer.c:791:7: warning: assignment makes pointer from integer without a cast
    fd = fopen64(path, "rb");
       ^
Linking C executable hackrf_transfer

**Comment by mossmann** [comment]
I added the #define to the source file in 95c9ac6.
