### ISSUE TITLE
IQ Data form usb is signed? 

### ISSUE THREAD

**Issue by wzyy2** [mossmann/hackrf#155]
If I google "hackrf iq",I will be told that "The HackRF logs are IQ data pairs, stored as unsigned 8 bit integers "..............
even comment in gr-osmosdr say is unsigned.....

```
/* HackRF device produces 8 bit unsigned IQ data */
...........
    _lut.push_back( gr_complex( (float(char(i >> 8))) * (1.0f/128.0f),
                                (float(char(i & 0xff))) * (1.0f/128.0f) ) );
...........
```

Maybe It should be mentioned.

**Comment by mossmann** [comment]
The data are signed but were once (more than a year ago) unsigned.

**Comment by a232319779** [comment]
HI,mossmann,
    which firmware version had been changed?
    How about the version : 2014.08.01

**Comment by a232319779** [comment]
I should ask clearly:
it's signed at the firmware version 2014.08.01?

**Comment by dominicgs** [comment]
Yes, the change to signed data was introduced in release 2014.08.1.
