### ISSUE TITLE
hackrf_transfer.c:638: coding error ?

### ISSUE THREAD

**Issue by dcb314** [mossmann/hackrf#156]
host/hackrf-tools/src/hackrf_transfer.c:638:14: warning: taking the absolute value of unsigned type 'unsigned long' has no effect [-Wabsolute-value]

   freq_hz = abs(if_freq_hz - lo_freq_hz);

Subtracting two unsigned longs produces an unsigned long. 

Suggest code rework.

**Comment by mossmann** [comment]
Those are signed (int64_t) now. Thank you!
