### ISSUE TITLE
Activating "Phantom" Antenna power?

### ISSUE THREAD

**Issue by regulatre** [mossmann/hackrf#168]
Looking for a way to activate phantom antenna power on my HackRF while using it in GQRX, Gnuradio, and other Osmo based applications. Is there a way to activate this feature through hardware means - perhaps a jumper? I have a LNA4All modified for phantom power but I'm struggling to find a way to use it with applications using the Osmo driver. 

Thanks!

**Comment by dominicgs** [comment]
@regulatre Thank you for creating this issue.  We support antenna port power from the HackRF command line tools and libhackrf, so this will require an update to [gr-osmosdr](http://git.osmocom.org/gr-osmosdr)

Something that handles power in the same way as "buffers" is already handled by the sink block: http://git.osmocom.org/gr-osmosdr/tree/lib/hackrf/hackrf_sink_c.cc#n172

**Comment by ckuethe** [comment]
Airspy also has antenna power, controlled by "bias=1" in the device
arguments. Seems like a place to start

On Mon, May 11, 2015 at 10:46 AM, Dominic Spill <notifications@github.com>
wrote:

> @regulatre <https://github.com/regulatre> Thank you for creating this
> issue. We support antenna port power from the HackRF command line tools and
> libhackrf, so this will require an update to gr-osmosdr
> <http://git.osmocom.org/gr-osmosdr>
>
> Something that handles power in the same way as "buffers" is already
> handled by the sink block:
> http://git.osmocom.org/gr-osmosdr/tree/lib/hackrf/hackrf_sink_c.cc#n172
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mossmann/hackrf/issues/168#issuecomment-100993964>.
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by regulatre** [comment]
Thanks for the hints guys. I'll see what I can come up with.

**Comment by regulatre** [comment]
Added! gr-osmosdr Commit ID 594391982845b4ac0e4e48bbb91b4b85552f2af6 May 27th, 2015

**Comment by zodoczi** [comment]
Anyone know how to enable antenna power in Windows, SDR#?
