### ISSUE TITLE
where i can download the source code of SDR#

### ISSUE THREAD

**Issue by commthu** [mossmann/hackrf#169]
Only nightly builds currently support HackRF One - http://sdrsharp.com/downloads/sdr-nightly.zip

I want to make some modification of SDR# to use hackrf, where i can download the source code. 
Thanks

**Comment by dominicgs** [comment]
SDR# is not part of the HackRF project.

This question should be directed to the author(s) of that project, although I do not believe that it is open source software.

**Comment by commthu** [comment]
In fact,  i do not need SDR# source code.
I want to make some modification of hackrf.dll  where SDR# used.  Can i get the source code of hackrf.dll in SDR#.

**Comment by dominicgs** [comment]
The hackrf.dll file is a Windows build of libhackRF, which can be found here: https://github.com/mossmann/hackrf/tree/master/host/

Using cmake and your compiler of choice on Windows should allow you to build libHackRF as a DLL.

**Comment by commthu** [comment]
I complied that last week, it only generate 13kb size dll, however, SDR#
use 78kb size dll,  I replaced it, then SDR# failed to open.

2015-04-13 22:17 GMT+08:00 Dominic Spill <notifications@github.com>:

**Comment by miek** [comment]
Here's the source for the SDR# HackRF plugin: https://github.com/zefie/sdrsharp_hackrf

**Comment by commthu** [comment]
Thanks miek and dominicgs.
