### ISSUE TITLE
Help! After update the firmware, my computer can not recognize the usb device!

### ISSUE THREAD

**Issue by commthu** [mossmann/hackrf#170]
I download the code from https://github.com/mossmann/hackrf and  rebuild it, which generate a hackrf_usb.bin,  then i  run hackrf_spiflash.exe -w hackrf_usb.bin.  After that, my computer can not recognize the usb device.   
I have another hackrf device, which still works in this computer.

**Comment by dominicgs** [comment]
@commthu You can recover the original HackRF firmware using the process listed here: https://github.com/mossmann/hackrf/wiki/Updating-Firmware#recovering-the-spi-flash-firmware

That will allow you to use the firmware from the release to restore your HackRF.  It is a two step process, first you use the DFU mode to run an intermediate firmware, then you use ```hackrf_spiflash``` to write a known good firmware to the device.

I do not have any experience of performing this process on a Windows system, but I don't see any reason that would cause a problem with ```hackrf_spiflash```.  I am unsure how to acquire ```dfu_tool``` for Windows.
