### ISSUE TITLE
Using Eclipse issues

### ISSUE THREAD

**Issue by commthu** [mossmann/hackrf#171]
1: download hackrf-2014.08.1.tar.xz
2: libopencm3-master.zip,   and extract and  put it in the firmware/libopencm3
I configure the eclipse as  https://github.com/mossmann/hackrf/wiki/Firmware-Development-Setup
met the issue below:
uint8_t uin32_t uint16_t could not resolved
#include <libopencm3/lpc43xx/gpio.h>, etc, no  such include files and lpc43xx dir.

**Comment by dominicgs** [comment]
This appears to be a path issue.  ```stdint.h``` needs to be somewhere in your path.

I am unfamiliar with eclipse, so am not able recommend an exact solution.  You may find other users who have got this working with eclipse if you ask this question on the mailing list or IRC channel (both are linked from the [Getting Help](https://github.com/mossmann/hackrf/wiki/Getting-Help) page on the wiki.
