### ISSUE TITLE
Does Hackrf support GPS time-stamping the RF data?

### ISSUE THREAD

**Issue by commthu** [mossmann/hackrf#172]
I want to use GPS time stamping the RF data, does hackrf support this function.
I know some SDR device has this function. This is very useful in some applications.

**Comment by KC5CQW** [comment]
This will probably require additional hardware like the PortaPack H1 and a GPS to sync with its RTC. 
It may be possible to stream NEMA outputs into a GPIO but otherwise, this would seem to be a host software feature.

**Comment by ckuethe** [comment]
I wrote a gnuradio module to ingest NMEA data into your flowgraph. You could use that to write stream tagged samples to a data file... https://github.com/ckuethe/gr-nmea

**Comment by KC5CQW** [comment]
Boom Shaka Lahka. 
And there it is...

**Comment by ckuethe** [comment]
Note that this module can't push any timing information into the receiver
so you'll probably get some pretty jittery timestamps depending on system
load.

On Wed, Aug 5, 2015 at 11:20 PM, KC5CQW <notifications@github.com> wrote:

> Boom Shaka Lahka.
> And there it is...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mossmann/hackrf/issues/172#issuecomment-128263094>.
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by mossmann** [comment]
Thanks, ckuethe! I'm closing this issue as the remaining concern (timestamps implemented in firmware instead of on the host) already has an issue: #85
