### ISSUE TITLE
HackRF and L-Band Spectrum

### ISSUE THREAD

**Issue by mouradghafiri** [mossmann/hackrf#174]
Hello,
Please is it possible to use HackRF and GNU Radio to plot the spectrum of the whole L-Band (1 to 2 GHz) assuming we design an antenna that could capture this band.

Thank you in advance

**Comment by ckuethe** [comment]
Yes. HackRF is specified to work from 10MHz to 6GHz with no gaps.

**Comment by mouradghafiri** [comment]
I'm trying to order the hackrf but I need to know some details before
choosing it as a condidate.
What about the legal framework of it, I mean anyone could buy it regardless
of the regulatory boundries.

One last question about the 20 MHz of bandwith limits!, I don't understand
how it can capture the whole L-band and has 20MHz band limit?

Would you please elaborate a bit.

Regards;

**Comment by ckuethe** [comment]
You can tune anywhere between 10 and 6GHz (even more, actually) and sample up to +/- 10MHz from that frequency. That's enough to grab the entire commercial FM radio band, not enough to tune GPS L1/2/5 (for example). You could write a program to scan the band in 20MHz chunks, but HackRF won't be able to grab 1GHz of spectrum all at once.

**Comment by mouradghafiri** [comment]
Thank you so much, it is clear enough now.
