### ISSUE TITLE
hackrf_transfer amp enable / disable

### ISSUE THREAD

**Issue by vsboost** [mossmann/hackrf#178]
Noticed that when you issue hackrf_transfer -f xxxxxxxxxx -c 127 -x 20 -a 1 the tx amp is enabled however if you  re issue hackrf_transfer -f xxxxxxxxxx -c 127 -x 20 without amp argument the amp is still on, you need to use the -a 0 to switch it off.

**Comment by mossmann** [comment]
fixed in af13e756d9afd4e6af6958413559828e81d03501 and release v2015.07.1
