### ISSUE TITLE
building hackrf tools for windows

### ISSUE THREAD

**Issue by vsboost** [mossmann/hackrf#183]
Can anybody possibly write up some instructions for building the hackrf tools for windows, i know the .exe are available but would like to be able to build the latest commits myself using visual studio.

Thanks

**Comment by dominicgs** [comment]
There's a pull request for the readme file pending, it adds the following:

**Comment by dominicgs** [comment]
These instructions were added to the readme in commit c6ca16c

**Comment by jocover** [comment]
https://github.com/jocover/hackrf/commit/d5c5803a87ca4347849176552d64b0851dbee6bd
remove pthread-win32,using Win32Thread in Visual Studio

**Comment by dominicgs** [comment]
@jocover I've created pull request #199 for this commit.
