### ISSUE TITLE
CLKIN port  connect 10M square wave or sine wave?

### ISSUE THREAD

**Issue by commthu** [mossmann/hackrf#184]
I use 10M GPS Disciplined Oscillato as external clock to connect CLKIN port.
Should I use square wave or sine wave input? which is better?

**Comment by dominicgs** [comment]
CLKIN is a digital input, so should be a square wave.  I'm not sure what would happen if you used a sine wave, but I would expect it to produce strange results.

**Comment by commthu** [comment]
I tried. Both sine wave and square wave works.

**Comment by W8M2Hg9lLmWqXSGC** [comment]
@commthu What was your sine source? A 10MHz Rubidium frequency standard like a FE-5680A?

**Comment by scateu** [comment]
You may refer to this page.

http://www.hackrf.net/2014/03/hackrf-one-10mhz-clkout/

**Comment by rielt12** [comment]
Hello,
How did you generate the needed sqaure wave?
