### ISSUE TITLE
Patch for building 2015.07 on MSVC 2012

### ISSUE THREAD

**Issue by guruofquality** [mossmann/hackrf#203]
I updated my build scripts for the 2015.07 tag. I fixed some compiler issues for MSVC2012 regarding declaring variables at the top of the function.. MSVC2013 and up support c99, but I still package for MSVC2012 which is stuck on c89. I know this it totally annoying, but the patch is small and the rest of the code seemed to be c89 compatible.

So if this is useful to upstream, the patch is here, or let me know if a pull request is preferred:
https://github.com/pothosware/PothosSDR/blob/master/patches/hackrf_fix_compat_c89_vc11.diff

**Comment by dominicgs** [comment]
I have applied this patch and pushed it to master.  Thanks for the contribution, I'm sorry it took so long to merge.

**Comment by guruofquality** [comment]
Sweet! Thanks.
