### ISSUE TITLE
Frequency Calibration and Characterization

### ISSUE THREAD

**Issue by KC5CQW** [mossmann/hackrf#207]
Implement a self calibration feature to characterize the HackRF's onboard crystal reference by comparing a known standard (GPSDO, rubidium etc. on PLL1 or received local GSM carrier signals etc.) and the onboard temperature sensor(s) (A comparison of the LO xtal aganst the "standard" and how much the LO drifts per thermal unit. Delta/Temp).
Establish a procedure to ramp the temperature over the expected operation temp range (60-90 F for example) and store the characterization lookup table file onboard for operation without the external clock connected. This would be useful in remote/mobile operation when away from the laboratory (with time standard (I.e. PortapackH1 use etc.).
Define a realistic useful expiration limit for the calibration. (1 hour, day, week, TBD).

**Comment by KC5CQW** [comment]
Perhaps the next evolutionary step is to create an open source GPSDO!
With a small ublox: 
https://shop-america.u-blox.com/en/usd/3~110~AMERICAS/Positioning-modules/Timing-raw-data/LEA-NEO-timing-modules (or equivalent),
a PLL and a high quality VCXCO, one can be incorporated into a small daughter card to connect via on board headers. Optionally, a self contained enclosure may be utilized with a trade off of an extra cable.
Note: using a freq. output vs. 1PPM will render better Allen deviation and lock time. 

***At 0.1ppm native accuracy, one of these VCXTO's from Fox:
http://www.foxonline.com/pdfs/FOX321_Standard_Specifications.pdf (or equivalent)
Would be fantastic for times when GPS signals are weak or lost.***

Secondly, the GPS will output NEMA and UTC. Some modules also contain an RTC with battery/super cap backup for warm starts. 

Reference
http://www.w1ghz.org/small_proj/A_Flexible_VCXO_Locking_Board.pdf
http://www.allanstime.com/AllanVariance/index.html

**Comment by ckuethe** [comment]
Or you could just buy one...
http://www.jackson-labs.com/index.php/products/lc_xo

On Thu, Aug 6, 2015 at 12:23 AM, KC5CQW <notifications@github.com> wrote:

> Perhaps the next evolutionary step is to create an open source GPSDO!
> With a small ublox:
>
> https://shop-america.u-blox.com/en/usd/3~110~AMERICAS/Positioning-modules/Timing-raw-data/LEA-NEO-timing-modules
> (or equivalent),
> a PLL and a high quality VCXCO, one can be incorporated into a small
> daughter card to connect via on board headers. Optionally, a self contained
> enclosure may be utilized with a trade off of an extra cable.
> Note: using a freq. output vs. 1PPM will render better Allen deviation and
> lock time.
>
>
>
> *At 0.1ppm native accuracy, one of these VCXTO's from Fox:
> http://www.foxonline.com/pdfs/FOX321_Standard_Specifications.pdf
> <http://www.foxonline.com/pdfs/FOX321_Standard_Specifications.pdf> (or
> equivalent) Would be fantastic for times when GPS signals are weak or lost.*
>
> Secondly, the GPS will output NEMA and UTC. Some modules also contain an
> RTC with battery/super cap backup for warm starts.
>
> Reference
> http://www.w1ghz.org/small_proj/A_Flexible_VCXO_Locking_Board.pdf
> http://www.allanstime.com/AllanVariance/index.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mossmann/hackrf/issues/207#issuecomment-128275922>.
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by KC5CQW** [comment]
I could but... I already have one. Besides if more signals are needed, a simple distribution bandpass filter/buffer amp would offer many more clock signals for other equipment.
Still, a daughter card GPSDO build for the HackRF using small SMD components would yield a low power clock standard with a much smaller footprint than existing COTS units.

**Comment by KC5CQW** [comment]
See also: #116

**Comment by KC5CQW** [comment]
Not a significant need and TCXO’s in 0.1ppm are now very affordable.
