### ISSUE TITLE
sgpio-rx example needs updating for signed samples.

### ISSUE THREAD

**Issue by jboone** [mossmann/hackrf#209]
In rx_test(), there is an incantation that converts RX samples from a buffer using "(x & 0xff) - 0x80", which is incorrect as of changes in the CPLD over a year ago. Somebody (me) was less than thorough reviewing examples...

**Comment by s0pr3m3** [comment]
Tried the changes you pushed to your branch at https://github.com/jboone/hackrf/tree/sgpio_rx_samples_signed , however the example still doesn't work. sigi and sigq have value of 0. Also, shouldn’t magsq be equal to sigi * sigi + sigq * sigq instead just sigi * sigq.

**Comment by jboone** [comment]
Resolved in "sgpio_rx_samples_signed" branch, pull request #211.

**Comment by rroff** [comment]
Hello,

It is amazing what one can invent! You're gonna love it, I swear! Read more here <http://fophythoty.ohmygodareyouserious.com/aealkyt>

Sincerely, rroff@roff.us
