### ISSUE TITLE
hackrf_spiflash -r hangs

### ISSUE THREAD

**Issue by jboone** [mossmann/hackrf#213]
hackrf_spiflash -r filename -l number_greater_than_zero

...hangs at "Reading 256 bytes from 0x000000.". Use ctrl-C to stop hackrf_spiflash, and the HackRF is no longer responsive (e.g. hackrf_info reports no HackRF boards found). It appears that the firmware is crashing due to the SPI read operation.

**Comment by dominicgs** [comment]
Fixed by @jboone in #215
