### ISSUE TITLE
Add Calibration

### ISSUE THREAD

**Issue by Gamephreaker** [mossmann/hackrf#216]
Mine is off by more then 5 Mhz really hard to use I have hunt for broadcasts

**Comment by dominicgs** [comment]
5MHz sees like a very big offset and is more likely to be related to other issues than to a drifting clock.  Which hardware version are you using?  Which versions of firmware, host tools and CPLD firmware are you using?

Adding calibration functions is already being tracked as #207, although there are some limitations to the effectiveness of calibration techniques and their results over time.

**Comment by Gamephreaker** [comment]
I am using a hackrf one. I have used the current builds and now the portapack build. It does it on the portapack as well.

**Comment by natevw** [comment]
@Gamephreaker Are you perhaps picking up harmonics of strong signals instead? What software and filter/gain settings are you using?

**Comment by mossmann** [comment]
Closing due to lack of response from original poster.  This was almost certainly either a bug or a user error, not a calibration issue.  If further assistance is needed, please see: [https://github.com/mossmann/hackrf/wiki/Getting-Help](https://github.com/mossmann/hackrf/wiki/Getting-Help)
