### ISSUE TITLE
Hackrf One over ip

### ISSUE THREAD

**Issue by aler86** [mossmann/hackrf#225]
Hello,

I have bougth HackRF one and tested it with FM,GSM,DVB in gnuradio.

Now i'm tried hackrf one with IEEE 802.11 a/g and have a question:

Is it possible assign ip address to Hackrf one maybe through a serial-ethernet converter?

Thanks in advance

**Comment by aler86** [comment]
sorry....i'm trying hackrf one with IEEE 802.11 a/g and...

**Comment by dominicgs** [comment]
When it comes to network protocols, such as 802.11a/g, the HackRF hardware is the radio front-end.  The IP address or MAC address would be set in the software implementation of 802.11

**Comment by aler86** [comment]
Can i use tun/tap for Hackrf one?

**Comment by dominicgs** [comment]
There isn't any existing software to use tun/tap with HackRF.

What is it that you are trying to achieve?

**Comment by aler86** [comment]
I'm trying to achieve 802.11 a/g protocol

**Comment by dominicgs** [comment]
HackRF One is just the radio, everything else will need to be written in software.  If you wish to pass packets to your 802.11 stack via tun/tap, then you will need that to be built in to the software stack.
