### ISSUE TITLE
PDF downloads from repository corrupt

### ISSUE THREAD

**Issue by sbmocp** [mossmann/hackrf#231]
When trying to download any of the PDFs from the repository I get a message stating the download is corrupt or not a valid PDF. I've tried both the latest Adobe PDF reader and FoxIt with the same results. Using Windows 7 64-bit on my PC.

**Comment by dominicgs** [comment]
Do you mean the PDFs from the repository?  Are you downloading them from the GitHub web interface or checking out the repository?

Does this link work for you? https://github.com/mossmann/hackrf/raw/master/doc/LPCXPresso_Flash_Debug_Tutorial.pdf

**Comment by lukeweston** [comment]
This isn't a bug, more like a "how do I use the GitHub web interface"
question.

FYI, for beginners, say you're at the following page, for example.
https://github.com/mossmann/hackrf/tree/master/doc

Suppose LPC4330_SGPIO_SignalGenerator_Measurements.pdf is the file you
want, so click on that link.

Now click on the little "Raw" box on the right side, and the PDF file will
download/open for you.

On Wed, Jan 13, 2016 at 2:38 AM, Dominic Spill <notifications@github.com>
wrote:

> Do you mean the PDFs from the repository? Are you downloading them from
> the GitHub web interface or checking out the repository?
>
> Does this link work for you?
> https://github.com/mossmann/hackrf/raw/master/doc/LPCXPresso_Flash_Debug_Tutorial.pdf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mossmann/hackrf/issues/231#issuecomment-170949813>.
>



-- 
This email is intended only for the personal and confidential use of the
human(s) named above. If intercepted by an extraterrestrial civilization,
all opinions expressed in this email are my own and do not necessarily
reflect the opinion of mankind as a whole.

**Comment by sbmocp** [comment]
lukeweston had it. Many thanks--it didn't work the way I'd expected.
