### ISSUE TITLE
Problems compiling HackRF Tools

### ISSUE THREAD

**Issue by GermMuz** [mossmann/hackrf#235]
I have followed the instructions for installing and setting up the environment for compiling the hackrf tools using Visual Studio 2012. Cmake successfully creates the .sln files. I have tried this on win 7 and win 10 and get multiple compile errors along the lines of:

syntax error: missing ';' before 'const'

there also seem to be  an int to bool issue on line 32 of hackrf.c

I would really appreciate some help here as I have no idea what to do now.

Is it better to use a different compiler????

I have tried zefies tools but these do not work, giving an error 5, device not found. SDR Sharp works perfectly, but I need a hackrf.dll without copyright issues for adding to one of my programs. Is there a more recent location to download the hackrf.dll from?

Thx

**Comment by dominicgs** [comment]
I haven't built the HackRF tools on a Windows host before, but I have heard of people having success with the Visual Studio compiler.  Could you copy and paste the entire build log so that we can see where these errors are coming from?

Also, which version of the HackRF code are you using, the latest release or git?

We don't ship binary files, so there is no official hackrf.dll file available.  I'm not sure I know of a reason that the version shipped with SDR# would be problematic, assuming that it is just a compiled copy libhackrf.

**Comment by GermMuz** [comment]
Firstly the output if running cmake

C:\>cd C:\hackrf-2015.07.2\host\cmake

C:\hackrf-2015.07.2\host\cmake>cmake ../ -G "Visual Studio 11 2012 Win64" -DLIBUSB_INCLUDE_DIR=c:\libusb-1.0.18-win\include\libusb-1.0 -DLIBUSB_LIBRARIES=c:\libusb-1.0.18-win\MS64\static\libusb-1.0.lib -DTHREADS_PTHREADS_INCLUDE_DIR=c:\pthreads-w32-2-9-1-release\Pre-built.2\include -DTHREADS_PTHREADS_WIN32_LIBRARY=c:\pthreads-w32-2-9-1-release\Pre-built.2\lib\x64\pthreadVC2.lib
-- The C compiler identification is MSVC 17.0.50727.1
-- The CXX compiler identification is MSVC 17.0.50727.1
-- Check for working C compiler using: Visual Studio 11 2012 Win64
-- Check for working C compiler using: Visual Studio 11 2012 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 11 2012 Win64
-- Check for working CXX compiler using: Visual Studio 11 2012 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Threads: c:/pthreads-w32-2-9-1-release/Pre-built.2/lib/x64/pthreadVC2.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/hackrf-2015.07.2/host/cmake

C:\hackrf-2015.07.2\host\cmake>

**Comment by GermMuz** [comment]
Now the compile using visual studio 2012

Error	1	error C2143: syntax error : missing ';' before 'const'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	319	1	hackrf
Error	2	error C2143: syntax error : missing ';' before 'const'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	319	1	hackrf-static
Error	3	error C2065: 'libusb_error' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	320	1	hackrf-static
Error	4	error C2065: 'libusb_error' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	320	1	hackrf
Warning	5	warning C4244: '=' : conversion from 'ssize_t' to 'int', possible loss of data	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	350	1	hackrf
Warning	6	warning C4244: '=' : conversion from 'ssize_t' to 'int', possible loss of data	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	350	1	hackrf-static
Warning	7	warning C4244: '=' : conversion from 'ssize_t' to 'int', possible loss of data	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	371	1	hackrf-static
Error	8	error C2143: syntax error : missing ';' before 'const'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	373	1	hackrf-static
Error	9	error C2065: 'serial_descriptor_index' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	374	1	hackrf-static
Error	10	error C2143: syntax error : missing ';' before 'type'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	379	1	hackrf-static
Error	11	error C2143: syntax error : missing ';' before 'const'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	380	1	hackrf-static
Error	12	error C2065: 'serial_number_length' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	381	1	hackrf-static
Error	13	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	382	1	hackrf-static
Error	14	error C2109: subscript requires array or pointer type	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	382	1	hackrf-static
Error	15	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	383	1	hackrf-static
Warning	16	warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	383	1	hackrf-static
Warning	17	warning C4024: 'strdup' : different types for formal and actual parameter 1	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	383	1	hackrf-static
Warning	18	warning C4244: '=' : conversion from 'ssize_t' to 'int', possible loss of data	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	371	1	hackrf
Error	19	error C2143: syntax error : missing ';' before 'const'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	373	1	hackrf
Error	20	error C2065: 'serial_descriptor_index' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	374	1	hackrf
Error	21	error C2143: syntax error : missing ';' before 'type'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	379	1	hackrf
Error	22	error C2143: syntax error : missing ';' before 'const'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	380	1	hackrf
Error	23	error C2065: 'serial_number_length' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	381	1	hackrf
Error	24	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	382	1	hackrf
Error	25	error C2109: subscript requires array or pointer type	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	382	1	hackrf
Error	26	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	383	1	hackrf
Warning	27	warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	383	1	hackrf
Warning	28	warning C4024: 'strdup' : different types for formal and actual parameter 1	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	383	1	hackrf
Warning	29	warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	427	1	hackrf
Error	30	error C2143: syntax error : missing ';' before 'type'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	449	1	hackrf
Error	31	error C2143: syntax error : missing ';' before 'const'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	450	1	hackrf
Error	32	error C2065: 'serial_number_length' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	451	1	hackrf
Error	33	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	452	1	hackrf
Error	34	error C2109: subscript requires array or pointer type	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	452	1	hackrf
Error	35	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	453	1	hackrf
Error	36	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	454	1	hackrf
Warning	37	warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	454	1	hackrf
Warning	38	warning C4024: 'strncmp' : different types for formal and actual parameter 1	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	454	1	hackrf
Error	39	error C2065: 'serial_number_length' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	463	1	hackrf
Error	40	error C2143: syntax error : missing ';' before 'type'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	602	1	hackrf
Error	41	error C2065: 'i' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	604	1	hackrf
Warning	42	warning C4028: formal parameter 3 different from declaration	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	1091	1	hackrf
Warning	43	warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	427	1	hackrf-static
Error	44	error C2143: syntax error : missing ';' before 'type'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	449	1	hackrf-static
Error	45	error C2143: syntax error : missing ';' before 'const'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	450	1	hackrf-static
Error	46	error C2065: 'serial_number_length' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	451	1	hackrf-static
Error	47	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	452	1	hackrf-static
Error	48	error C2109: subscript requires array or pointer type	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	452	1	hackrf-static
Error	49	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	453	1	hackrf-static
Error	50	error C2065: 'serial_number' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	454	1	hackrf-static
Warning	51	warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	454	1	hackrf-static
Warning	52	warning C4024: 'strncmp' : different types for formal and actual parameter 1	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	454	1	hackrf-static
Error	53	error C2065: 'serial_number_length' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	463	1	hackrf-static
Error	54	error C2143: syntax error : missing ';' before 'type'	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	602	1	hackrf-static
Error	55	error C2065: 'i' : undeclared identifier	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	604	1	hackrf-static
Warning	56	warning C4028: formal parameter 3 different from declaration	C:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	1091	1	hackrf-static
Error	57	error LNK1104: cannot open file '..\..\libhackrf\src\Debug\hackrf.lib'	C:\hackrf-2015.07.2\host\cmake\hackrf-tools\src\LINK	hackrf_max2837
Error	58	error LNK1104: cannot open file '..\..\libhackrf\src\Debug\hackrf.lib'	C:\hackrf-2015.07.2\host\cmake\hackrf-tools\src\LINK	hackrf_cpldjtag
Error	59	error C2275: 'hackrf_device' : illegal use of this type as an expression	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	61	1	hackrf_info
Error	60	error LNK1104: cannot open file '..\..\libhackrf\src\Debug\hackrf.lib'	C:\hackrf-2015.07.2\host\cmake\hackrf-tools\src\LINK	hackrf_rffc5071
Error	61	error C2065: 'device' : undeclared identifier	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	61	1	hackrf_info
Error	62	error C2065: 'device' : undeclared identifier	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	62	1	hackrf_info
Warning	63	warning C4047: 'function' : 'hackrf_device **' differs in levels of indirection from 'int *'	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	62	1	hackrf_info
Warning	64	warning C4024: 'hackrf_device_list_open' : different types for formal and actual parameter 3	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	62	1	hackrf_info
Error	65	error C2065: 'device' : undeclared identifier	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	69	1	hackrf_info
Warning	66	warning C4047: 'function' : 'hackrf_device *' differs in levels of indirection from 'int'	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	69	1	hackrf_info
Warning	67	warning C4024: 'hackrf_board_id_read' : different types for formal and actual parameter 1	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	69	1	hackrf_info
Error	68	error C2065: 'device' : undeclared identifier	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	78	1	hackrf_info
Warning	69	warning C4047: 'function' : 'hackrf_device *' differs in levels of indirection from 'int'	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	78	1	hackrf_info
Warning	70	warning C4024: 'hackrf_version_string_read' : different types for formal and actual parameter 1	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	78	1	hackrf_info
Error	71	error C2065: 'device' : undeclared identifier	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	86	1	hackrf_info
Error	72	error LNK1104: cannot open file '..\..\libhackrf\src\Debug\hackrf.lib'	C:\hackrf-2015.07.2\host\cmake\hackrf-tools\src\LINK	hackrf_si5351c
Warning	73	warning C4047: 'function' : 'hackrf_device *' differs in levels of indirection from 'int'	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	86	1	hackrf_info
Warning	74	warning C4024: 'hackrf_board_partid_serialno_read' : different types for formal and actual parameter 1	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	86	1	hackrf_info
Error	75	error C2065: 'device' : undeclared identifier	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	101	1	hackrf_info
Warning	76	warning C4047: 'function' : 'hackrf_device *' differs in levels of indirection from 'int'	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	101	1	hackrf_info
Warning	77	warning C4024: 'hackrf_close' : different types for formal and actual parameter 1	C:\hackrf-2015.07.2\host\hackrf-tools\src\hackrf_info.c	101	1	hackrf_info
Error	78	error LNK1104: cannot open file '..\..\libhackrf\src\Debug\hackrf.lib'	C:\hackrf-2015.07.2\host\cmake\hackrf-tools\src\LINK	hackrf_spiflash
Error	79	error LNK1104: cannot open file '..\..\libhackrf\src\Debug\hackrf.lib'	C:\hackrf-2015.07.2\host\cmake\hackrf-tools\src\LINK	hackrf_transfer
	80	IntelliSense: invalid combination of type specifiers	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	32	13	hackrf-static
	81	IntelliSense: a value of type "void *" cannot be used to initialize an entity of type "hackrf_device_list_t *"	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	346	31	hackrf-static
	82	IntelliSense: a value of type "void *" cannot be assigned to an entity of type "char **"	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	352	23	hackrf-static
	83	IntelliSense: a value of type "void *" cannot be assigned to an entity of type "hackrf_usb_board_id *"	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	353	22	hackrf-static
	84	IntelliSense: a value of type "void *" cannot be assigned to an entity of type "int *"	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	354	25	hackrf-static
	85	IntelliSense: argument of type "void *" is incompatible with parameter of type "libusb_device *"	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	363	32	hackrf-static
	86	IntelliSense: a value of type "uint16_t" cannot be assigned to an entity of type "hackrf_usb_board_id"	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	370	30	hackrf-static
	87	IntelliSense: argument of type "void *" is incompatible with parameter of type "libusb_device *"	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	375	22	hackrf-static
	88	IntelliSense: argument of type "void *" is incompatible with parameter of type "libusb_device *"	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	604	18	hackrf-static
	89	IntelliSense: argument of type "transceiver_mode_t" is incompatible with parameter of type "hackrf_transceiver_mode"	c:\hackrf-2015.07.2\host\libhackrf\src\hackrf.c	922	47	hackrf-static

**Comment by jboone** [comment]
I do not have the same compiler version, so I can't reproduce. However, reviewing the source code where the errors occur, these errors are pretty clearly from a C89 compiler attempting to compile a C99 or newer codebase, where variable declarations can appear after the first statement in a block. I believe C99 support came in VS 2013, and indeed, my VS 2013 compiler does not complain about those parts of the code (I have linker problems, but the compilation is successful and clean enough).

**Comment by dominicgs** [comment]
I have applied a patch to the git master branch that should fix the build errors caused by MSVC's C89 rules.

@GermMuz Until the next release you have two options:
1) Upgrade to a newer version of the compiler - the free community version is supported
2) Use the git codebase rather than the release

I recommend option 2.

**Comment by GermMuz** [comment]
Help appreciated, I'll try the latest build in a minute. I did try extracting the source code and making my own dll only having coded a few functions and that worked, I'll report back later.

**Comment by GermMuz** [comment]
I've now compiled the code (x64 version) and all is working well. 

Thank you

**Comment by GermMuz** [comment]
Thank you for the reply.

 

The problem is now fixed and I have the code compiled. 

 

I did try vs2015 first and run into the identical compile problems, then got out the old vs2012 disks.

 

Thank you for the fix, really appreciated.

 

Glenn
