### ISSUE TITLE
Why a strong noise signal in falls middle,if I change frequency, still exists

### ISSUE THREAD

**Issue by justforname** [mossmann/hackrf#251]
Why a strong noise signal in falls middle,if I change frequency, still there
Firmware Version: git-7e81647
I use SDR# record on windows

**Comment by Dygear** [comment]
You're taking about the DC offset?

https://github.com/mossmann/hackrf/wiki/FAQ

Check the FAQ.

--
Mark 'Dygear' Tomlin

**Comment by justforname** [comment]
@Dygear thank you, but when I replay the record signal, this noise covering normal signal

**Comment by vsboost** [comment]
Capture your sample slightly off frequency, when you replay you wont be affected by the dc offset.

**Comment by justforname** [comment]
@vsboost  ok~
