### ISSUE TITLE
Add WCID descriptor

### ISSUE THREAD

**Issue by dominicgs** [mossmann/hackrf#267]
For better Windows support we'd like to add the Windows compatibility descriptors.

Information can be found here: 
https://msdn.microsoft.com/en-gb/library/windows/hardware/ff537430(v=vs.85).aspx
https://msdn.microsoft.com/en-gb/library/windows/hardware/jj649944(v=vs.85).aspx
https://github.com/pbatard/libwdi/wiki/WCID-Devices#WCID_Advantages

**Comment by jocover** [comment]
linux and windows work fine,but OSX 10.11 not work

Jiangwei-Macbook-Air:build jiangwei$ hackrf_info 
No HackRF boards found.

Jiangwei-Macbook-Air:examples jiangwei$ ./listdevs
05ac:821f (bus 250, device 7) path: 3
05ac:024c (bus 250, device 4) path: 2
05ac:8404 (bus 253, device 2) path: 1
0a5c:4500 (bus 250, device 3) path: 1
05ac:850a (bus 250, device 2) path: 2
0424:2513 (bus 250, device 1) path: 1
0424:2513 (bus 253, device 1) path: 1

no found 1d50:6089 hackrf device

Jiangwei-Macbook-Air:examples jiangwei$ ./xusb 1D50:6089
Using libusb v1.0.20.11115

Opening device 1D50:6089...
  Failed.
