### ISSUE TITLE
Frequency gap ?

### ISSUE THREAD

**Issue by yo2ldk** [mossmann/hackrf#269]
I know that HackRF have not so god RF amplifier but, when I try to receive NOAA weather satellites in 137Mhz, I see nothing on waterfall, not even a bit ! 
 With the same equipment , in the same time, but with R820T2  the signal is full.
 So I have  a gap frequency or it is so "deft"  ? or is my unit damage?
Another thing, in the ExtIO dll file can be added something to remove DC ?
 Thank you in advance !

**Comment by dominicgs** [comment]
As I asked on your previous issue (#263), could you please provide some screenshots or other information about where you see gaps in the frequency range?  And what you mean by gaps?

HackRF does not have gaps in the frequency coverage, so this could be a software or other issue.  Do you see gaps elsewhere in the range?  Can you successfully receive broadcast FM radio?

What antenna do you have connected?
Which software are you using?
What does `hackrf_info` report?

**Comment by yo2ldk** [comment]
this is in windows with sdr# or hdsdr.
FM and 2m band is ok in receiving , just there I have no reception.
I will made some screenshots if is need it
 I not used hackrf_info. i will try

**Comment by dominicgs** [comment]
Yes please, could you attach screenshots.

Which antenna is connected?  Anything else?  Filters?  Amplifier?

**Comment by yo2ldk** [comment]
antenna is deedicated for 137Mhz; no filters and no LNA this time, just units
![hackfr_137b](https://cloud.githubusercontent.com/assets/1875591/16918381/c27a90ea-4d0d-11e6-8836-4de418612ae6.jpg)
![hackfr_137](https://cloud.githubusercontent.com/assets/1875591/16918382/c27d0ec4-4d0d-11e6-8a63-0a53e23f5a7e.jpg)
![airspy_137](https://cloud.githubusercontent.com/assets/1875591/16918383/c27e2714-4d0d-11e6-98c2-713ca1e3d173.jpg)
![img_20160718_172544](https://cloud.githubusercontent.com/assets/1875591/16918384/c2814976-4d0d-11e6-9292-c974137585d4.jpg)

**Comment by yo2ldk** [comment]
satellites just passed, but it is some identifiers signals as you see on airspy reception

**Comment by N8AUM** [comment]
Alexander, do you have a signal generator ? Also, turn the pre-amp ON. This is what a -130dbm CW signal looks like on mine:

![screenshot 2016-07-28 04 44 56](https://cloud.githubusercontent.com/assets/20634021/17208582/f5621384-547e-11e6-80f5-a5f933a85909.png)

**Comment by yo2ldk** [comment]
Hi Vidas,

  Thank you for reply,
My sig. gen. is under construction now I made one with si5351
I try also with amp (LNA) activated almoust the same , more background noise.
after my vacation  I made an external LNA to see if is better, it seems hackrf is deaf like an old man..

  my best 73 !

**Comment by rafael2k** [comment]
Hi all, I bought a HackRF and I have exact the same problem, completely deaf at 200MHz...

**Comment by straithe** [comment]
Are you still having trouble? We will close this issue if we don't get a reply within the next month.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
