### ISSUE TITLE
hackrf_transfer shows wrong exit message

### ISSUE THREAD

**Issue by rgerganov** [mossmann/hackrf#272]
When transmitting a single file like this:

```
$ hackrf_transfer -t fm.cfile -f 144800000 -s 2205000
call hackrf_sample_rate_set(2205000 Hz/2.205 MHz)
call hackrf_baseband_filter_bandwidth_set(1750000 Hz/1.750 MHz)
call hackrf_set_freq(144800000 Hz/144.800 MHz)
Stop with Ctrl-C
 1.6 MiB / 1.000 sec =  1.6 MiB/second

User cancel, exiting...
Total time: 1.00011 s
hackrf_stop_tx() done
hackrf_close() done
hackrf_exit() done
fclose(fd) done
exit
```

hackrf_transfer says "User cancel, exiting..." although I am not pressing CTRL+C and the program finishes by itself. The problem is that both libhackrf and hackrf_transfer are using `do_exit` flag which is not static and which is used for different purposes. So setting `do_exit` in libhackrf is interpreted like user exit in hackrf_transfer.

**Comment by dominicgs** [comment]
Nice catch!  I'll merge the PR now.
