### ISSUE TITLE
rom_to_ram firmware compilation

### ISSUE THREAD

**Issue by hchenji** [mossmann/hackrf#274]
Could not find instructions on building the rom_to_ram.bin seen in the release. I followed the instructions in firmware/README, but the generated .bin bricks the device and has to be DFU'd.

**Comment by dominicgs** [comment]
The instructions in firmware/README are correct for building the firmware as the build process defaults to loading from ROM.

Could you paste the `cmake` and `make` output in to this issue?
Which version of the firmware were you trying to build?  di you make any modifications to the code?

**Comment by hchenji** [comment]
Never mind, it works now if I do `rm -rf *` in build directory before re-make.
