### ISSUE TITLE
Building the host tools with an updated libusb to connect via VirutalHere

### ISSUE THREAD

**Issue by LuAbelt** [mossmann/hackrf#277]
Hey Folks,
I've tried to setup my hackrf via a virtual USB Software called "VirtualHere". My Host where I connect the HackRF to is a RasPi 3, my client on which I want to work with the Hackrf in GNURadio is a Windows 7 64 Bit machine. It seemed to work properly, as the HackRF showed up correctly in my device manager on Windows 7 BUT as I tried to perform hackrf_info in the command prompt it didn't found the HackRF.
After some digging I found out, that this seems to be a problem with the libusb Library that is used. The version that is recommended in the Readme in the host folder is very likely deprecated, as it is about two years old. The problem I've encountered with VirtualHere seems to be resolved in the latest version (see https://github.com/libusb/libusb/issues/187)
What I tried then is building the tools myself with the updated libusb library. I just want to say here, that this is the first time I tried to build something myself from Github so I tried to follow the instructions in the readme. It all worked pretty fine, I got to the point where I had the solution file and as the instructions end there, I figured that I just needed to compile those in Visual Studio.
I tried doing this on two different Systems, one using Windows 7 and Visual Studio 2013 Professional and the other using Windows 10 and Visual Studio 2015 Community.
Now this is where I got really confused. Compiling worked on none of these systems, but I encountered different errors on the two systems.

On my Windows 7 System Visual Studio showed up a message box that said:

> Unable to start program
> 'C:\hackrf-master\host\cmake\x64\Debug\ALL_BUILD'
> Access is denied

After a little Google research, this problem seems to be rather common with no really universal solution.

On my Windows 10 System, I got a compiler error that had a problem with the "timedev" struct in the pthread.h file(Line 320). I'm not 100% sure what the exact problem was but I think it was because the timedev struct is already defined somewhere else and Visual Studio didn't seem to like that.
I tried "fixing" this by commenting out the timedev struct. That did resolve that error but as I tried to compile that it threw out a couple of more errors that see to be cuased by the libusb library. I'm sorry, that I cannot give you any detailled information about that at the moment, but I will later when I'm back at my Windows 10 system.

So now my question is, as I never build something from giothub: Was compiling the solution file even the right thing to do? Sorry agaiun, but I'm completely new to this.
Did someone ever tried to build the software with the latest libusb(see http://libusb.info/) or at least some newer version than the one recommended in the readme? Most importantly did you encountered similar errors and know how to fix them?
Did anyone of you ever tried using the HackRF via a virtal USB hub and can maybe recommend another tool that works without rebuilding the host tools?

If there was a convenient way to build the host tools with this newer version of libusb I would also highly recommend updating the link in the readme
Thank you all in advance

**Comment by miek** [comment]
@LuAbelt I'm sorry this didn't get answered originally. Given the amount of change in all the software since this was filed, I don't think I can give any reasonable answers so I'm going to close this for now. However, if you're still looking to do something like this, please do open up a new issue and I'll be happy to help.
