### ISSUE TITLE
Binaries are missing in the "latest release"

### ISSUE THREAD

**Issue by dmitryelj** [mossmann/hackrf#278]
Please add a Windows binaries to the "latest release" section.
I cannot find hackrf_transfer.exe anywhere, and it's not comfortable to install half megabyte of IDE tools to build it.

Thanks.

**Comment by dominicgs** [comment]
We don't ship binaries as part of our releases, but you can get precompiled libhackrf as part of SDR# or PothosSDR here: http://downloads.myriadrf.org/builds/PothosSDR/?C=M;O=D

**Comment by dmitryelj** [comment]
What is the reason that binaries are not available? Copyright issues?

I was needed hackrf_transfer.exe as utility I can use, not libhackrf as a
library I can link :)

2016-09-13 0:34 GMT+02:00 Dominic Spill <notifications@github.com>:

**Comment by James-Brown** [comment]
Dmitrii – Email me and I’ll send you What I have.
Jim@SETI.Net
