### ISSUE TITLE
unable to install libhackrf software in ubuntu 14.04 32 bit

### ISSUE THREAD

**Issue by sagniknitr** [mossmann/hackrf#279]
![screenshot from 2016-09-12 21 23 35](https://cloud.githubusercontent.com/assets/17951883/18442486/8eae10aa-792e-11e6-936e-9b49ee2f8177.png)

**Comment by dominicgs** [comment]
That screenshot is a build failure for osmosdr as it tries to link to libhackrf.  Do you already have libhackrf installed?

How are you building this?  We'll need more information to help you to debug this.
