### ISSUE TITLE
HackRF and WIN 7 32bit

### ISSUE THREAD

**Issue by Rolf9999** [mossmann/hackrf#284]
Hi,

got the HackRf as a gift. Unfortunately I'm not a Linux guy. How can I instali the HackRF with WIN7 32bit ? The recommendations I found so far are more than 2 years old and do not work on my Laptop. Many thanks for any help.

Rolf

**Comment by yo2ldk** [comment]
you can install SDR# from airspy dot com, and there you have hackrf driver as device

**Comment by dominicgs** [comment]
I recommend either [SDR#](http://airspy.com) as @yo2ldk recommended, or [HDSDR](http://www.hdsdr.de) if you're more interested in the amateur radio bands.

**Comment by Rolf9999** [comment]
Yo2ldk thank you - tried it again, found HacKRF under source menue, select it and try to start, error message = "No device selected"

dominicgs - thank you too, will try HDSDR also

driver is libusb-win32 devices in system setup, there is the HackRF, driver manuf. OpenMoko, Inc, vers. 02.08.2012 1.2.6.0 and status is active, so it seems to be ok

**Comment by Rolf9999** [comment]
So found the problem. Was the wrong driver. Problem is solved. Thanks again for your assistances.

**Comment by Dygear** [comment]
If you don't like it, I'd be happy to take it off your hands for a fair price.
