### ISSUE TITLE
HackRF stops receiving

### ISSUE THREAD

**Issue by i02much** [mossmann/hackrf#286]
Read a previous issue on this where the problem was bad / faulty USB cables / OTG cables.  I've got several of each and I have the same issue on each one.  I'm using HackRF with Nexus 6P on CM13.  I've changed sample rates, gain, you name it,  Everything will work for a couple minutes then "HackRF stopped receiving" error.  I click the play button and it starts back up and after a few seconds, stops receiving.

**Comment by dominicgs** [comment]
Which piece of software are you using?
Have you tried to connect the HackRF to any other system?
Do they exhibit the same behaviour?

**Comment by dominicgs** [comment]
Closing as no response within a year.
