### ISSUE TITLE
hackrf_transfer not transmitting/receiving anything

### ISSUE THREAD

**Issue by jc1122** [mossmann/hackrf#290]
I have a Pentoo 2015.0 RC4.6 Release distribution to run hackrf. I updated the firmware to version 2015.07.2 (did only step 1!) according to the instructions here : https://github.com/mossmann/hackrf/wiki/Updating-Firmware . Then I built host software using instructions: https://github.com/mossmann/hackrf/tree/master/host . Then I updated CPLD (step 2 of firmware update). Both firmware and CPLD update seems to be OK. hackrf_info shows an updated device.

I tested the device using GNU Radio Companion to capture and transmit FM radio signal. The results are OK - I could hear the signal from hackrf on a small FM radio device.

I tried to reproduce the capture and transfer with hackrf_transfer:

`hackrf_transfer -r test -f 92000000`

then:

`hackrf_transfer -t test`

I also tried to transmit the file captured with GNU Radio Companion.
Both attempts are successful, as either RX or TX LED is on, however I do not receive any signal on my FM radio device. 
I also tried to play GPS signal with GNU Radio Companion, the attempt was successful - mobile phone could see the signal, however there was no effect when using hackrf_transfer.

What am I doing wrong?

**Comment by dominicgs** [comment]
You may want to set some gain settings on both receive and transmit.

It would also be worth taking a look at the received `test` file to see whether or not the data is good.

**Comment by jc1122** [comment]
The FM signal is strong, I could capture it with rf, if and bb gain set to zero.
![fm radio grc](https://cloud.githubusercontent.com/assets/22999250/19625390/aeb2b516-9906-11e6-9d72-879882499e6c.png)

The spectrum of replayed radio signal (captured with GNU Radio Companion at 96.2 MHz) is attached below:
![screenshot_2016-10-23_11-56-15](https://cloud.githubusercontent.com/assets/22999250/19625414/1a339aa8-9907-11e6-8647-359d373dfb9b.png)

![screenshot_2016-10-23_11-58-11](https://cloud.githubusercontent.com/assets/22999250/19625416/40b40096-9907-11e6-973b-1a83e4da70e7.png)

I tried to experiment with hackrf_transfer gain settings, however the result is the same every time. See screenshots below:

![screenshot_2016-10-23_12-01-05](https://cloud.githubusercontent.com/assets/22999250/19625434/e68cd83a-9907-11e6-9b00-627d32de96c5.png)

![screenshot_2016-10-23_12-01-38](https://cloud.githubusercontent.com/assets/22999250/19625435/eee5a67e-9907-11e6-9a31-1e72b57e178e.png)

What else should I check?

**Comment by jc1122** [comment]
converting the hackrf_transfer -r output to f32 solved the problem.

**Comment by BigNerd95** [comment]
How did you convert it?

**Comment by jc1122** [comment]
use sox, see here:
https://greatscottgadgets.com/sdr/11/
