### ISSUE TITLE
HACK RF error in ubuntu 14.04 32 bit

### ISSUE THREAD

**Issue by sagniknitr** [mossmann/hackrf#291]
Please anyone identify and solve this error
![error](https://cloud.githubusercontent.com/assets/17951883/19972257/6d208d30-a207-11e6-8d7d-c888589b3104.png)
![error](https://cloud.githubusercontent.com/assets/17951883/19972268/75d17cc8-a207-11e6-8526-47d9e5163006.png)

**Comment by dominicgs** [comment]
Try running `sudo ldconfig` to make sure that the system knows where libhackrf is installed.

**Comment by sagniknitr** [comment]
Already did that....still the error persists. Is this error because my ubuntu is 32 bit?
I tried the same instructions in ubuntu 64 bit 14.04 and it was working

**Comment by dominicgs** [comment]
This looks like different versions of the host tools and libhackrf are installed.  Did you build them both from source?  IS there a distribution provided package installed?

**Comment by dominicgs** [comment]
Closing as I believe that I was right about mismatched library and tools.  Also, Ubuntu 14.04 is now old enough that I don't plan to continue supporting it.
