### ISSUE TITLE
FATAL: No supported devices found to pick from

### ISSUE THREAD

**Issue by chakpongchung** [mossmann/hackrf#292]
linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.11.0.git-28-gc66cb1ba

gr-osmosdr v0.1.4-75-gae686c46 (0.1.5git) gnuradio 3.7.10.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy redpitaya 

FATAL: No supported devices found to pick from.

How we can solve this?

I am running #sudo gnuradio-companion fm_radio_rx.grc

**Comment by paulathomas** [comment]
I am having the same problem with a HackRF One despite my set-up working with NooElec SMART. My set up is on Xubuntu 16.10.

**Comment by dominicgs** [comment]
Do you have permission to access the HackRF?  Try running `hackrf_info` and pasting the output here.

**Comment by dominicgs** [comment]
@chakpongchung, @paulathomas any feedback on this?  I'd like to close this issue.
