### ISSUE TITLE
Very low gain (without RF gain enabled)

### ISSUE THREAD

**Issue by xluccianox** [mossmann/hackrf#297]
Hi, I've recently bought a HackRF One, before I've been playing arround for a while with an R820T2 NESDR Mini Dongle from NooElec.
I'm experiencing very low gain with HackRF compared with a rtl sdr dongle, you can see this clearly in the FM spectrum (I've attached some screenshots), with RF Gain on it looks more alike the rtl sdr dongle output, should use it always on? Cause on Mike's SDR video tutorials he mention not to leave it on (because an strong signal may damage the unit).
The hackrf firmware is up to date and I'm using an ANT700 antenna (from Great Scott Gadgets) with the HackRF and a very similar telescopic antenna with the NooElec NESDR.
Could it be a defective unit?

| HackRF with RF Gain = 0 dB  | HackRF with RF Gain = 14dB |
| ------------------------------------- | ------------------------------------- |
| ![hackrf no rf gain](https://cloud.githubusercontent.com/assets/1659902/21915030/dd22269e-d915-11e6-9fbd-6630f552641b.png)  | ![hackrf rf gain on](https://cloud.githubusercontent.com/assets/1659902/21915033/dd233c14-d915-11e6-8753-e8abe3cf91d9.png) |

| NESDR Mini with LNA Gain = 0 dB  | NESDR Mini with LNA Gain = 14db |
| -------------------------------------------- | -------------------------------------------- |
|  ![rtl no lna gain](https://cloud.githubusercontent.com/assets/1659902/21915031/dd230028-d915-11e6-91e8-677a80b0461c.png)  |  ![rtl lna gain 14db](https://cloud.githubusercontent.com/assets/1659902/21915032/dd23127a-d915-11e6-8665-a9a0dfec33fe.png)  |

Thanks.

PD: Sorry if this issue doesn't belong here, I didn't find another place to ask a solution for it.

**Comment by candrewneal** [comment]
I'm having the same problem as you, I'm using SDR# with the ANT500 antenna on Windows 10.

**Comment by mossmann** [comment]
What sample rate are you using?  HackRF One's lowest supported sample rate is 2 Msps, and you'll typically get better receive sensitivity at higher sample rates (up to a maximum of 20 Msps).  For best sensitivity, use a high sample rate with a narrow baseband filter bandwidth.

**Comment by xluccianox** [comment]
Sorry I didn't answer. I've checked the receiving sensibility and transmission in the RF lab of my university, all 3 hackrfs we tested gave the same values, so there is no problem with mine.
And yes, I was using low sample rates.

**Comment by cyba3r** [comment]
I have the same issue like xluccianox. What was the solution to fix the problem?

**Comment by dominicgs** [comment]
@cyba3r The solution was to use a higher sample rate and a narrower baseband filter.

**Comment by kouroshdd** [comment]
Hi i have the same problem with my hack rf its very weak signal but my rtl2832 is very powerfull than hack rf one !!!it is normal or my hack rf have problem please tell me im very nervos

**Comment by SpiryMedia** [comment]
HackRF per general has a very weak signal. Extremely weak. Basically deaf. They are selling a very deaf RF.

**Comment by gpgib6** [comment]
I can also confirm this. First is from hackrf one, second is from $20 rtl dongle. I will say that using cubicSDR made a big difference though.

![myhackrfone](https://user-images.githubusercontent.com/43342108/53769653-94018200-3eaa-11e9-84f5-4c0b27a86d08.png)
![myrtl](https://user-images.githubusercontent.com/43342108/53769679-a11e7100-3eaa-11e9-9b03-d9729b6bffa9.png)
