### ISSUE TITLE
hackrf no IQ data

### ISSUE THREAD

**Issue by abdullah612** [mossmann/hackrf#298]
hello

i have the HackRF One running latest firmware 2015.07.02 it was working until suddenly stopped
it is recognized by both hackrf_tools in VMware and SDR# in windows
but when i press the play button in SDR# the RX led lights but i get no IQ data and when i press the stop button it hangs untill i reset the hackrf
i did test it with hackrf_transfer but i get the folowing error :

Couldn't transfer any bytes for one second.

Exiting... hackrf_is_streaming() result: HACKRF_TRUE (1)
Total time: 1.00091 s
hackrf_stop_rx() done
hackrf_close() failed: HACKRF_ERROR_LIBUSB (-1000)

i already checked the clock chip as @bg8wj suggested and it appears to be working
i have 10MHz clock at CLKOUT and a clock at the pins of ic equal to sample rate and double the sample rate all as documented in the schematic
i also checked voltages and they seem ok at 1.8V and 3.3V
i also checked the RX_enable signal on pin 48 of the MAX2837 and it has 3.3V when i press start on SDR#

hackrf_info output :

Board ID Number: 2 (HackRF One)
Firmware Version: 2015.07.2

my laptop core i7 16g ram

**Comment by dominicgs** [comment]
As discussed in IRC, this appears to be a hardware failure.  We'll continue debugging via other channels and a replacement can be issued if required.
