### ISSUE TITLE
support rudimentary TX/RX switching

### ISSUE THREAD

**Issue by mossmann** [mossmann/hackrf#320]
See @argilo's solution on #195 and make sure that we have implemented it or something comparable.  A higher performance solution will be investigated when reworking the transceiver code in the firmware after the release.

**Comment by dominicgs** [comment]
Using https://github.com/argilo/contest-sdr/blob/master/vhf_transceiver.py to test, we were able to switch between rx and tx with a single HackRF using the current master branch HEAD.

There does not appear to be a need to ignore transfer cancellations and errors.

I'm going to close this issue, please let me know if you have a script/flowgraph that requires the libusb errors to be ignored.
