### ISSUE TITLE
hackrf_sweep doesn't build on Windows

### ISSUE THREAD

**Issue by mossmann** [mossmann/hackrf#338]
We don't build it because we had trouble linking to fftw.  This is probably solvable.

**Comment by mrbubble62** [comment]
Got it working, probably not the right way.
https://github.com/mrbubble62/hackrf/commit/63435f5616133abe25c8f9b4f09ea220046e2af4

**Comment by dominicgs** [comment]
@mrbubble62 This looks great.  I have a couple of questions, which I'll comment on the commit, but I'd like to merge this soon.

**Comment by dominicgs** [comment]
That's looking great.  Would you like to submit a pull request so that we can merge it?

I'll try to replicate your process with the Appveyor config too.

**Comment by mossmann** [comment]
fixed in #343
