### ISSUE TITLE
Not really an issue, but a noob question. rtlsdr_scanner, rtl_fm does does not detect hackrf

### ISSUE THREAD

**Issue by securisec** [mossmann/hackrf#340]
### Steps to reproduce
1. This is more of a question on what I am doing wrong with the Hackrf. When i use the hackrf with grc, it is picking it up fine... but when i try using it with something like rtlsdr_scanner, or rtl_*, it doesnt detect it. This behavior is consistent in both my ubuntu 1604, and pentoo. Same thing applies to GRC where i am getting a "no rf or hardware blocks found" message. I have tried running all tools with sudo just to make sure.

When i use my nooelec sdr with any of these tools, I do not see the same behaviour, and all programs are working well with the sdr. 

unexpected behavior also is refected on 
multimon-ng  NRF24-BTLE-Decoder  RFAnalyzer  RTLSDR-Scanner  rx_tools  sdrsharp  SoapySDR  

### Expected behaviour
that all other programs mentioned would work with the hackrf.

### Version information
ubuntu 16.04 and pentoo

**hackrf_info output:**

hackrf_info version: git-e7647f6
libhackrf version: git-e7647f6 (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000909864c838618dcf
Board ID Number: 2 (HackRF One)
Firmware Version: git-0335f1a (API:1.02)
Part ID Number: 0xa000cb3c 0x00654755
If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
output of rtlfm:
No supported devices found.
```
Thanks a lot in advance!

**Comment by reldred** [comment]
You need to use hackrf_sweep not the rtl tools.

**Comment by reldred** [comment]
Most of the rtl tools won't work with a hackrf. Instead of something like rtl_power for instance gets replaced with hackrf_sweep.

**Comment by vsboost** [comment]
Use qspectrumanalyzer, the fork from mossmann or miek

https://github.com/miek/qspectrumanalyzer
https://github.com/mossmann/qspectrumanalyzer

**Comment by securisec** [comment]
thanks @vsboost but it seems like even with qspectrumanalyzer, i still have the same issue with the hackrf. i get a ```No supported devices found.``` message.

**Comment by vsboost** [comment]
What happens when you run hackrf_info and what happens when you run hackrf_sweep

**Comment by securisec** [comment]
They both work. I have the hackrf_info in my original post.

**Comment by vsboost** [comment]
Can you re-do the hackrf firmware with the release one https://github.com/mossmann/hackrf/releases/tag/v2017.02.1

**Comment by vsboost** [comment]
How are you installing qspectrumanalyzer?

**Comment by securisec** [comment]
I redid the hackrf tools, and firmware withe the 2017.02.1 version. I am using the qspectrumanalyzer mossmann fork. As for installation, I followed the steps in the fork. 

Here is the output for qspectrumanalyzer:
```rtl_power params:
{'bin_size': 10.0,
 'crop': 0.2,
 'gain': 20,
 'hops': 0,
 'interval': 0.01,
 'ppm': 0,
 'single_shot': False,
 'start_freq': 100.0,
 'stop_freq': 105.0}

Range: 100.0M:105.0M:10.0k
Mode: hopping
Number of frequency hops: 5
Dongle bandwidth: 1280000Hz
Downsampling by: 1x
Cropping by: 21.88%
Total FFT bins: 640
Logged FFT bins: 500
FFT bin size: 10000Hz
Buffer size: 16384 bytes (6.40ms)

Reporting every 1 seconds
No supported devices found.```

Here is the flashed hackrf_info:
```hackrf_info version: 2017.02.1
libhackrf version: 2017.02.1 (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000909864c838618dcf
Board ID Number: 2 (HackRF One)
Firmware Version: 2017.02.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x00654755```

**Comment by vsboost** [comment]
Ahh i think i know whats wrong, the installation steps in the forked versions are wrong, if you used pip3 install qspectrumanalyzer it will install the original creators version which does not contain the mods for the hackrf.

You need to clone the version from mossmann or miek and build it manually by running python3 setup.py install

then when you run qspectrumanalyzer in the file --> settings menu you should see the hackrf in the drop down menu.

**Comment by securisec** [comment]
Ah. that was is. Now qspectrumanalyzer can see hackrf. 

For a fix suggestion, I would say that in the mossmann version, I cant change the crop% or the ppm. Hence my scan looks messed up. see the screenshot. 
Thanks again for your help! Any other awesome tool I should be aware off? I am mostly meddling in the 2.4 Ghz space for now. 

![image](https://cloud.githubusercontent.com/assets/22226823/22870215/78817f8e-f173-11e6-8b7f-0071510d040d.png)

**Comment by vsboost** [comment]
Yea crop / ppm / gain don't work for me as well, i think that should be an easy fix.  As for other tools that use hackrf_sweep for graphing im not sure.

**Comment by vsboost** [comment]
Correction gain is working, just have to stop and start.

**Comment by dominicgs** [comment]
It looks like the initial query was answered, so I'm going to close this issue.

Any bugs/suggestions for QSpectrumAnalyzer should likely be raised against the upstream version of the tool.
