### ISSUE TITLE
Exception thrown in hackrf_sweep.exe: 0xC0000005: Access violation reading location

### ISSUE THREAD

**Issue by mrbubble62** [mossmann/hackrf#346]
hackrf_sweep -f 985:1015 -w2414

Exception thrown at 0x00007FF7A09A1BEF in hackrf_sweep.exe: 0xC0000005: Access violation reading location 0x0000018B1F042290.

VS debugger stops at  line 240:
```		/* copy to fftwIn as floats */
		buf += SAMPLES_PER_BLOCK - (fftSize * 2);
		for(i=0; i < fftSize; i++) {
>>			fftwIn[i][0] = buf[i*2] * window[i] * 1.0f / 128.0f;
			fftwIn[i][1] = buf[i*2+1] * window[i] * 1.0f / 128.0f;
		}
```
fftSize = 8292
If "FFT bin width (-w) must be no more than one quarter the sample rate" 
Then buf overflow makes sense.

Whats interesting is bin_width value 2415 resulting in fftSize = 8284 is OK no errors

There is definitely something wrong at line 482:
```
	if(4 > fftSize) {
		fprintf(stderr,
				"argument error: FFT bin width (-w) must be no more than one quarter the sample rate\n");
		return EXIT_FAILURE;
	}
```

**Comment by dominicgs** [comment]
We receive 16k blocks from the HackRF and perform the FFT over the final FFTsize*2 of them.  Once you use a high enough fftSize, that code will try to start before the start of the buffer.

We should catch this when parsing arguments and give an appropriate error message.
