### ISSUE TITLE
Can i softwarely reset the device

### ISSUE THREAD

**Issue by commthu** [mossmann/hackrf#363]
some times, the device is dead. I have to push the reset button or reconnect the usb plug.
Can i softwarely reset the device, becasue in some applications, the device is in remote.
if you can provide such funciton in the lib, that is will be very usefull.

**Comment by dominicgs** [comment]
`hackrf_spiflash -R` will reset the HackRF.

Of course, if the HackRF is not responding, it's possible that it won't respond to the reset request either.
