### ISSUE TITLE
Do hackrf support cross-compiled to arm development board?

### ISSUE THREAD

**Issue by Li-albert** [mossmann/hackrf#376]
We use ubuntu cross-compile hackrf program,and found that the prgram dependent environment do not support cross-complie to arm development board?

Do you have any method to slove this problem?

**Comment by dominicgs** [comment]
Assuming that you are trying to cross compile the host tools, could you post the output from cmake and make?

**Comment by miek** [comment]
Closing as there's been no response for a while, but if you're still having trouble with this feel free to re-open or open a new issue.
