### ISSUE TITLE
what's  accuracy of  SDR oscillator in HackRF one? for example, the USRP1 to 20 parts per million (ppm)

### ISSUE THREAD

**Issue by stackprogramer** [mossmann/hackrf#379]
i read in  this link that USRP1 has accuracy frequency clock??

>  for example, the USRP1 to 20 parts per million (ppm)his is sufficient for a number of purposes, but not for others. Some SDRs (including the HackRF and USRP) also support external oscillators. For example, the Clock Tamer, the KSP 52MHz and the FA-SY 1 are all accurate clocks.

https://github.com/scateu/kalibrate-hackrf

for rtl-sdr is about 85 ppm.

http://davidnelson.me/?p=371

i want to know whats this for HackRF one ? it can effect on bad receiving HackRF one?
thanks best regards stackprogramer

**Comment by dominicgs** [comment]
HackRF One features a crystal that has frequency stability of 20 ppm.

**Comment by schielb** [comment]
@dominicgs Where did you find that out?
