### ISSUE TITLE
Trouble updating Firmware

### ISSUE THREAD

**Issue by steven-bloom** [mossmann/hackrf#415]
Hi everyone
I wanted to update Firmware for my Hackrf, but facing that Problem. Is that normal behavior
![screenshot from 2017-10-18 17-27-57](https://user-images.githubusercontent.com/30798903/31727741-a92945e8-b42a-11e7-83b6-4bfa90fa03ce.png)
I really appreciate any help you can provide

**Comment by dominicgs** [comment]
Yes, that's how a normal firmware update looks.  I'm aware that it's not entirely clear that it succeeded.

I can add a line to make it more obvious that it's complete, but we don't know if the write was successful until you reset the device and run the new firmware.

**Comment by steven-bloom** [comment]
Hello, Dominicgs! Thanks for your response. 
I did reset. The output of the command "hackrf_info" is below.
![screenshot from 2017-10-18 19-28-31](https://user-images.githubusercontent.com/30798903/31733110-f6c928ee-b43a-11e7-8a35-cf41d54b95af.png)
The problem is, however, that these hackrf does not transmit output signal correct.
I have two HackRFs and one GNU-Radio Flowgraph that produce DRM-Radio Signal. One the Picture below is one of my HackRF that does that proper (wide signal)
![picture 1](https://user-images.githubusercontent.com/30798903/31733323-99f16a0e-b43b-11e7-9f72-00c42e658e16.png)
 Аnd in this picture  of the same signal, but produced with another HackRF (with the topic in question). No changes have been made, only another HackRF. And it can not be properly decoded.
Thats why i decided to make Firmware update 
![picture 2](https://user-images.githubusercontent.com/30798903/31733564-4f8bf42e-b43c-11e7-8eec-b4c411e026d6.png)
Anyway, I'm still getting this wrong narrow signal even with Firmware-update.
Assuming that Firmware is correct installed, what could be the problem
Thanks for help again

**Comment by gtg498u** [comment]
Try putting a Correct IQ block right after the osmocom source block.
![image](https://user-images.githubusercontent.com/32823519/31738162-c3836152-b417-11e7-8887-7f9c6b8f8bf9.png)

**Comment by dominicgs** [comment]
Is the CPLD up to date?  You can update it with `hackrf_cpldjtag -x hackrf_cpld_default.xsvf` from the`firmware-bin` directory.

Instead of transmitting from GNU Radio, could you use a file sink (signed bytes format) and transmit it with `hackrf_transfer` using the two radios.  This helps me to narrow down where the problem is.

**Comment by steven-bloom** [comment]
It didn't worked, I tried with hackrf_transmit and i can not still receive wideband signal (Picture 1) unlike to Picture 2 
![screenshot from 2017-10-19 14-45-14](https://user-images.githubusercontent.com/30798903/31772468-1235bf02-b4e0-11e7-95eb-c7db638aabdc.png)
![screenshot from 2017-10-19 15-10-14](https://user-images.githubusercontent.com/30798903/31772471-14263da0-b4e0-11e7-84bf-0941c28a5115.png)

I have also CPLD updated, and it still didnt  worked
I also tried Firmware 2015...no result

**Comment by hustpigeon** [comment]
I have the problem like him， before I update newest firmware, at least I can receive some FM, and now none can receive

**Comment by hustpigeon** [comment]
I solved this problem by update CPLD firmware

**Comment by steven-bloom** [comment]
CPLD is uptodate,  but it stil doesnt work :(

**Comment by dominicgs** [comment]
@steven-bloom Could you contact your reseller for a replacement HackRF?  I think we need to get this one back to analyse it for defects.
