### ISSUE TITLE
HackRF has no USB Light and Not Visible on any Computer

### ISSUE THREAD

**Issue by AlexL410** [mossmann/hackrf#420]
### Steps to reproduce
1. Plug in HackRF to USB Port
2. No Sound in Windows on multiple Computers
3. USB light on HackRF does not light

### Expected behaviour
Windows should recognize when HackRF is plugged in and beep

### Actual behaviour
No sound, and Zadig does not see the device to allow me to configure the drivers. USB port is not physically damaged. There is no physical damage to USB port.

### Version information
Windows 7 64 Bit and Windows 10 64Bit

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by gtg498u** [comment]
I had an issue with different USB cables. Be sure you are using a short one with a ferrite choke.

**Comment by dominicgs** [comment]
Is there anything listed in the device manager?

If you hold down the "DFU" button as you connect it, does a device appear?

**Comment by AlexL410** [comment]
Hi gtg498u,

It looks like it was the cable. I tried about 5 of them I have, but only one worked. I do not have one with a coil on it. But at least I can access the device now. Thank you.

**Comment by AlexL410** [comment]
Dominic, 
I have it working now with a different USB cable. Several others did not work.
With the non-working cables, holding the DFU button did not make the HackRF show up in device manager. It is interesting that the same cables work fine with other microcontroller micro-usb devices.
Thank you for your help.

**Comment by dominicgs** [comment]
On rare occasions the micro USB ports can become a little loose.  With the non-working cables, is there some play in the connector?

**Comment by AlexL410** [comment]
Dominic, 
the USB connector is not loose at all. It has a good solid mounting to the inside circuit board. There is no side to side movement at all. I tried moving between the 5 cables, and the only connection that shows up is with the working cable. Since the usb-micro connector can be broken easily, I am gentle with the insertions and removals of all my devices.
Cheers!

**Comment by hustpigeon** [comment]
bad cable has week current,so hackrf one can't work correct
