### ISSUE TITLE
Hack RF Conformal coating on pads for RF Shield

### ISSUE THREAD

**Issue by ncoop23** [mossmann/hackrf#426]
There is conformal coating over the ground pads for the RF shield.  This makes it very hard to install a RF shield on new boards.

**Comment by yhetti** [comment]
Where did you buy your HackRF One from? I ask because Great Scott Gadgets does not use a conformal coating on any of it's products. I have found that sometimes it is difficult to get solder to stick to the first pad. This is because it is hard to get the pad to heat evenly with the shield frame. Heat is dissipating through the ground plain and the many nearby pads are acting like a heat sink.

**Comment by ncoop23** [comment]
Got it from Amazon.  When I was heating the pads, there was a lot of melting of the conformal coating which then got all over and made the solder not want to stick.  My RF shield is not attached properly now and I'm having issues with noise.  I'm about to cut it off and deal with the noise.  I have a metal case and portapack which helps a lot.

**Comment by yhetti** [comment]
Can you attach a photo of your board?

**Comment by ncoop23** [comment]
See attached. 
![20171109_114113](https://user-images.githubusercontent.com/1179525/32617471-1377eb4c-c543-11e7-9cb4-f0df83ce6a82.jpg)

**Comment by ncoop23** [comment]
I'm not the best at soldering but every time I touched the pad, a river of coating flowed in to the pad and the solder wouldn't stick. I figured whatever and went for broke but that didn't work either. I'm going to snip it off and forget about it I think.

**Comment by ncoop23** [comment]
The extra header went on nicely on the back.

**Comment by yhetti** [comment]
It looks to me like you have enough of it soldered to make the shield effective. If you take the pick and place bridge off of the top you may get better access to the pads near the P28 header. If you decide to solder anymore of it, make sure to use an excessive amount of flux. Then snap the shield on and you should see a noise reduction.

**Comment by KC5CQW** [comment]
Actually, it looks like too much flux is there...
From the picture, I cannot find any evidence of conformal coat. Are you referring to the green solder mask?  I can say that your iron is undersized (low wattage) and not properly heating the pads on the PCB. There is already more than enough solder and flux there for a reheat if you haven’t removed anything yet. I recommend getting a 35-40watt iron and reflow the solder to ensure a good electromechanical bond. Next, clean up the PCB with rubbing alcohol (IPA) and q-tips until no flux is within the shielded RF area (at a minimum). Have no worries about cleaning the board, you won’t harm anything unless you power it up whilst still wet.
