### ISSUE TITLE
can hackrf one be applied to rfid systems?

### ISSUE THREAD

**Issue by Katerhong** [mossmann/hackrf#428]
I am sorry about my english, I hope you can understand what i say.
Dear Sir
I am a graduate stduent from  hangzhou dianzi university of china.I have studied your video from your website.thanks for you detailed lessons.
my qustion is can i use hackrf one to read and write rfid tage?we can use two hackrf one boards.
my e-mail is :522080514@qq.com ;Looking forward you reply.Thank you.
                                                                                             

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by miek** [comment]
It's possible to use HackRF for RFID systems in theory, but it's not supported out of the box and would need extra hardware & significant software development.
As a starting point, Michael Ossmann touches on the idea in this talk: https://www.youtube.com/watch?v=4Lgdtr7ylNY
