### ISSUE TITLE
how to import IQ data in matlab?

### ISSUE THREAD

**Issue by lshangguan** [mossmann/hackrf#431]
Hi, could you help to check whether the following steps give the correct IQ data when importing them (collected by HackRF) into Matlab?

fid= fopen('filename.dat');
data=fread(fid);
>> y = data - 128;
>> y = y(1:2:end) + j*y(2:2:end);

The firmware version is 2015.07.2

Thanks!

**Comment by barto-** [comment]
This should work
```Matlab
fid = open('samples.bin',  'r');
len = 1000; % 1000 samples
y = fread(fid, 2*len, 'int8');
y = y(1:2:end) + 1j*y(2:2:end);
fclose(fid)
```
