### ISSUE TITLE
Installed host for HackRF error ,when excuted the command of "cmake ../ -DINSTALL_UDEV_RULES=ON"

### ISSUE THREAD

**Issue by freesky918** [mossmann/hackrf#432]
### Steps to reproduce

$ sudo apt-get install build-essential cmake libusb-1.0-0-dev
pkg-config
git clone https://github.com/mossmann/hackrf.git
cd hackrf/host
mkdir build
cd build
cmake ../ -DINSTALL_UDEV_RULES=ON

### Version information
**Operating system**:ubuntu 16.04,hackRf one sdr
### Output
ThinkPad-X250:~/hackrf/host/build$ cmake ../ -DINSTALL_UDEV_RULES=ON
-- Setting udev rule group to - plugdev
-- HackRF udev rules will be installed to '/etc/udev/rules.d' upon running 'make install'
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find FFTW (missing: FFTW_LIBRARIES FFTW_INCLUDES)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindFFTW.cmake:28 (find_package_handle_standard_args)
  hackrf-tools/src/CMakeLists.txt:26 (find_package)

**Comment by dominicgs** [comment]
This is failing because it is looking for libfftw3 but failing to find it.  I'm fairly sure this souldn't cause it to fail, but should simply give you a warning that it's not going to build `hackrf_sweep`.

To fix this you can run `sudo apt-get install libfftw3-dev`
