### ISSUE TITLE
Windows build artifacts from Appveyor

### ISSUE THREAD

**Issue by dominicgs** [mossmann/hackrf#436]
It would be nice to store the build artifacts from AppVeyor for the adventurous Windows users.

**Comment by dominicgs** [comment]
Progress: https://ci.appveyor.com/project/dominicgs/hackrf/build/1.0.101/artifacts

**Comment by caquino** [comment]
Is this issue fixed? I'm asking based on your progress as I'm able to see the artifacts available for download, is help still needed?

**Comment by dominicgs** [comment]
I haven't tested the binaries and I think I probably need to export the rest of the libraries.  If you'd like to experiment with it, I'd really appreciate the help.

**Comment by caquino** [comment]
Sadly looks like appveyor don't let me change the permissions for oauth and it's asking access to all my organizations, which is an issue for me as I can't give access to work-related organizations.

I will try to setup a new github login during the weekend to test this.
