### ISSUE TITLE
Ranging Using HackRF

### ISSUE THREAD

**Issue by elal007** [mossmann/hackrf#440]
### Steps to reproduce
1. I set up two HackRFs. One as Transmitter(TX) with Power Level 47 (max) and other as Receiver (RX)
2. I use hackrf_sweep to measure the signal strength.
3. I turn off Transmitter and measured the RSSI value: -70dB (noise floor)
4. Then I turn on the transmitter so that the distance is 30cm from RX. And the RSSI measured is -60dB

From 3 and 4, the ranges of RSSI is -70db<RSSI<-60dB.
### Expected behaviour
Because I want to use the hackrf for ranging, I want to increase the RSSI range measurement. I was trying to work with LNA and VGA gain, but it seems that the range was always constant, nearly 10dB.
Is there any way to increase the range?

The command to save the RSSI
 elal@ubuntu:~/sdr-utils/experiment$ hackrf_sweep -f 2400:2405>filerssidistance1m.csv

# hackrf_info output

elal@ubuntu:~/sdr-utils/experiment$ hackrf_info
hackrf_info version: git-2174aa0
libhackrf version: git-2174aa0 (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000925866e62ba72ae3
Board ID Number: 2 (HackRF One)
Firmware Version: 2017.02.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x005a4f5e

**Comment by miek** [comment]
Sorry this never got a response originally. I'd need a bit more information on how the transmitter is configured to give a good answer.

I'm gonna close this as it's a couple of years old now, but if you are still needing some help with this project please do re-open or open a new issue.

**Comment by SrikanthPatel471** [comment]
rssi should be in dbm
