### ISSUE TITLE
Question about opera cake and hack-RF

### ISSUE THREAD

**Issue by hoyunwon** [mossmann/hackrf#461]
### Expected behaviour
We are currently trying on switching antennas through opera cake and Hack-RF. However, we can only turn on one antenna as instructed from wiki.

### Actual behaviour
What kind of code should we use? Any further instructions will be welcomed.

**Comment by miek** [comment]
Could you expand a bit and paste the commands & output that you're trying to use, and also the versions of host tools & firmware?
