### ISSUE TITLE
Receive GPS data error

### ISSUE THREAD

**Issue by CodoonAutomatedTest** [mossmann/hackrf#462]
from gps sdr simulation, I could transmitting using hackrf One.it is transmitting well and i could receive the signals well, but when I used GPS Data application on HUAWEI Android phone(Kirin CPU). The GPS Data is different from another phone, The receive data is not available for data transmission. how can i probably fix?

**Comment by KC5CQW** [comment]
Do you need the GPS NEMA data or just a clock signal? 
It sounds like you may need the GPS protocol from the Huawei company.

**Comment by KC5CQW** [comment]
Huawei may be using the Beidou protocol and not GPS.
