### ISSUE TITLE
usb ACK what use usb_transfer_schedule_block()???

### ISSUE THREAD

**Issue by hustpigeon** [mossmann/hackrf#480]
![default](https://user-images.githubusercontent.com/12145816/39486249-0dd3c85c-4dae-11e8-9ab5-6956a36fb850.png)

**Comment by dominicgs** [comment]
This vendor request is used to write firmware to the SPI flash chip.  We send the firmware binary in chunks on the bulk out endpoint.

The function `usb_transfer_schedule_block()` is used to tell the USB stack where to write the data from the bulk out endpoint once it arrives.  Once the buffer has been copied this function is called again with the `stage` argument set to `USB_TRANSFER_STAGE_DATA` and we can then write the buffer to the chip.

**Comment by hustpigeon** [comment]
@dominicgs  thank you very much， the other question, when we ACK **setup transaction**， is usb stack ack by default? the code shows we ACK  "data transacton" and  "status transaction", but not ack "setup transaction"

**Comment by hustpigeon** [comment]
i get it ,the function usb_transfer_schedule_ack() is not the real function that ack usb data， it is only set usb stack to receive or send data. may be usb ack data by default?!!

**Comment by hustpigeon** [comment]
the usb stack will send ack packet by defualt , or automatically, programer need not to care it.
