### ISSUE TITLE
how to debug hackrf firmware code

### ISSUE THREAD

**Issue by hustpigeon** [mossmann/hackrf#483]
I want to debug hackrf firmware code， bug have no clue! who can telll me step by step.

it 's best to give me a tutorals， thank you

**Comment by mossmann** [comment]
We have some information about setting up firmware debugging in the wiki: https://github.com/mossmann/hackrf/wiki/LPC43xx-Debugging

I recommend the Black Magic Probe with gdb.  Once you have gdb running, you can follow one of the many gdb tutorials available online.
