### ISSUE TITLE
hackrf one transmit multiple channel?

### ISSUE THREAD

**Issue by haryows** [mossmann/hackrf#486]
greeting sir,

i want ask a simple question actualy, did hackrf one can transmit multiple channel?
if yes, how can i did it with my hackrf. thank you sir.

Version information:
hackrf_info version: git-5e9cad6
libhackrf version: git-5e9cad6 (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000909864c834771ccf
Board ID Number: 2 (HackRF One)
Firmware Version: git-5e9cad6 (API:1.03)
Part ID Number: 0xa000cb3c 0x00584756

**Comment by dominicgs** [comment]
This very much depends on what you mean by "channel".

HackRF can transmit 20 MHz of arbitrary signal.  If your signal is less than 10 MHz you can probably transmit multiple simultaneously, depending on channel spacing.

**Comment by dominicgs** [comment]
No, in that use case you would need multiple radios or a radio with 300 MHz of bandwidth.  HackRF has 20 MHz of bandwidth.

**Comment by haryows** [comment]
thank you very much for the answer sir.
