### ISSUE TITLE
What will the n(t) be at the end of ADC at receiver in theory ?

### ISSUE THREAD

**Issue by H1Rong** [mossmann/hackrf#489]
Hi if our hackrf in receiving mode, and there is no transmitter. All I'd like to do is to calculate the noise power in one interested frequency band, like 3000MHz- 3010MHz. 
The noise expressed as n(t), coming into the antenna goes through the LPF, goes into the mixer, is filtered by balun, is downconverted to baseband with the output both I and Q and finally convert from analog to digital by ADC.
So could you please help me with the equations of n(t) for each process?
That confuses me for serval months.
Thanks a lot!

**Comment by mossmann** [comment]
There are many sources of noise in the system, and how they affect the received signal is highly dependent on the configuration of various gain stages, switches, and frequency synthesizers.  I don't think your question is directly answerable.  You would have to perform measurements to learn about the noise characteristics of a particular configuration.
