### ISSUE TITLE
question about hcakrf clock

### ISSUE THREAD

**Issue by lanlanwei** [mossmann/hackrf#490]
The internal clock of hackrf is ?when I install an external clock ,which one is used??
Any help will be grateful.Thank you

**Comment by mossmann** [comment]
See https://github.com/mossmann/hackrf/wiki/HackRF-One#external-clock-interface-clkin-and-clkout

This will change in an upcoming software release (and has already changed in git) with the addition of a new command-line tool for clock control.

The internal clock is a 20 ppm crystal oscillator.
