### ISSUE TITLE
HackRF-One as a standalone node. 

### ISSUE THREAD

**Issue by HrfTdoa** [mossmann/hackrf#494]
Interested to implement TDOA using several stand alone HackRF - One sdrs.
Each node will be synchronized with TCXO, send data over GSM(using UART), and be powered by a battery via micro USB.
RF DSP related logic is to be implemented on the Cortex-M4 micro-controller.

Several questions:

1. Was HackRF-One designed for IoT standalone applications? 
If so – was the intention to use USB for battery and UART for Cellular? 
Is there a more efficient set up?
2. Seems that Cortex-M4 micro-controller can be programmed to perform DSP related functionality, as demonstrated in:

http://sdr-x.github.io/abar/ 

Looking for references of RF DSP algorithms implemented on HackRF as a standalone platform.
Any leads to related projects are welcomed.

Thanks in Advance.

**Comment by mossmann** [comment]
HackRF One can be used as a stand-alone platform.  As an example, see the [PortaPack H1](https://github.com/sharebrained/portapack-hackrf).  PortaPack is typically powered by a USB battery.

**Comment by HrfTdoa** [comment]
Thank you Michael.

In addition to being stand-alone platform, the device also should support a remote FW updating functionality.
Seems that for this purpose, a host will be needed. 
One possibility is to use Raspberry Pi.
This can also solve the DSP processing load, as raspberry pi 3 supports GNU radio.
My question is, can raspberry pi be avoided by using the existing HW of the HackRF.

Thanks.
