### ISSUE TITLE
hackrf_transfer 

### ISSUE THREAD

**Issue by mazen-bassiouny** [mossmann/hackrf#498]
### Steps to reproduce
1.i want to use Hackrf_transfer to generate binary date in certain frequencies 
2.i hava a program (grgsm) which use OsmoSDR block as source 
3. i want to replace the source block with the binary file generated from hackrf_transfer 

### Expected behaviour
Tell us what you expect should happen
i want to know the output itself from Osmosdr so i can synchronize 
### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by miek** [comment]
The main difference between the samples in a file created by hackrf_transfer, and samples coming from the OsmoSDR source block are the data types. hackrf_transfer creates files with signed 8-bit integers, while OsmoSDR (and most blocks in GNURadio) use 32-bit floats.

To replace an OsmoSDR block in a flowgraph, you need a File Source pointing at the recorded file, then IChar to Complex to convert the datatype, then a Multiply const by 1/128 to scale the samples correctly.
