### ISSUE TITLE
General Question, no issue: How to recover an undersampled OFDM signal?

### ISSUE THREAD

**Issue by gtg498u** [mossmann/hackrf#503]
I was trying to understand the HackRF Sweep tool.

I was so impressed with the functionality, that I wanted to see if I could use it to recover the baseband information of an undersampled OFDM signal.

The OFDM signal is rated for a 204.8MHz sampling rate!

Sampling at 20MHz give me enough resolution into the range of subcarriers I'm interested in, but I just want to see if I can recover the digital modulation by altering the hackRF sweep tool. 

I understand OFDM very well, but I'm used to having the full sample rate!
Thanks for any insider comments.

**Comment by miek** [comment]
The way HackRF sweep works is the firmware tunes to a frequency, dwells for some time sampling as normal, then it re-tunes and repeats. So you only receive samples for each frequency range for a limited portion of time, then miss what's going on while it's tuned elsewhere.

If that still sounds useful, then you'd need to modify the `hackrf_sweep` (or create your own application that calls `libhackrf`) that gives you access to the actual samples (without doing an FFT).
