### ISSUE TITLE
Looking for a source code for OFDM signal recording.

### ISSUE THREAD

**Issue by HrfTdoa** [mossmann/hackrf#504]
Hi,

I am totally new to hackRF.
Trying to record an OFDM signal in the 2.4Ghz domain and then analyze it in Matlab.
The 3 gains in the the osmocom source are not clear to me.
What should be their values for proper operation?
My current code is based on the FM receiver example.
Does anyone have a decent and simple GNU example I can use, being sure that the parameters are set correctly?

Thanks in Advance.

**Comment by miek** [comment]
Here's a tutorial on working with the GNURadio OFDM blocks: https://wiki.gnuradio.org/index.php/Basic_OFDM_Tutorial. I recommend going through that and getting it working in simulation first. Once you have a working flowgraph, you can introduce the HackRF and adjust the gains for best results.
