### ISSUE TITLE
set_freq_explicit / channel inversion bug

### ISSUE THREAD

**Issue by gibbi** [mossmann/hackrf#505]
### Expected behaviour / Actual behaviour
When we look at the firmware (tuning.c) the q channel is inverted for every frequency above 2150MHz. If i want to use set if/mixer explicitly instead the channel is only inverted if the MixerLO is higher than the IF. I assume both paths (explicit and auto) should work the same?

This bug makes it very hard to use explicit settings at all.

Did i miss something?

**Comment by hustpigeon** [comment]
did you solved this problem?

**Comment by straithe** [comment]
Are you still experiencing this issue?

**Comment by gibbi** [comment]
i did not check in a long time.. got it working well enough without the use of explicit tuning

**Comment by straithe** [comment]
Do you need any further assistance or may I close this ticket?

**Comment by straithe** [comment]
I'm going to close this for now as it seems your issue has been solved, but please re-open this issue or open a new one if you still need assistance.
