### ISSUE TITLE
Links in Wiki FAQ (troubleshooting section) are broken

### ISSUE THREAD

**Issue by bl4krat** [mossmann/hackrf#510]
### Steps to reproduce
1. View the [wiki FAQ](https://github.com/mossmann/hackrf/wiki/FAQ)
2. Scroll to the bottom (Troubleshooting section)
3. Try any of the three links

### Expected behaviour
link to helpful information telling me exactly what I have done wrong ;-)

### Actual behaviour
404 error, or a simple 'not found' page is displayed

### Version information
github as of today

**hackrf_info output:**
n/a

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.
n/a

### Output
n/a

**Comment by dominicgs** [comment]
Thanks for letting us know.  I've fixed them now.
