### ISSUE TITLE
Hackrf stuck in upgrade firmware

### ISSUE THREAD

**Issue by haryows** [mossmann/hackrf#512]
### Steps to reproduce
1. Download the fimrware from https://github.com/mossmann/hackrf/releases/tag/v2018.01.1
2. Extract file firmware>firmware-bin, n run " hackrf_spiflash -w hackrf_one_usb.bin"
3. Stuck

### Expected behaviour
I expect will get succes notification or do next instruction.

### Actual behaviour
I just stuck in this : 
![spiflashstuck](https://user-images.githubusercontent.com/30684427/44130957-20ef74d0-a07a-11e8-933c-de7fa5a96326.png)

I stuck in here for an hour n nothing happen

### Version information
Pentoo 2018.0

**hackrf_info output:**
![hackrfinfo](https://user-images.githubusercontent.com/30684427/44131020-72b6776e-a07a-11e8-8682-a1f39e794ff0.png)

what I should do for this stuck?i have no idea on it. help me please.

**Comment by haryows** [comment]
thanks for ur suggest sir, very appreciate that.
i'll try and report here as soon as posible.

**Comment by Slasher006** [comment]
i have found out that it works if you load the dfu from the release package and then write the bin from master. With the one that master builds it hangs at spi flash.
