### ISSUE TITLE
Hackrf 1hz-10ghz

### ISSUE THREAD

**Issue by joshspivey** [mossmann/hackrf#516]
Im paying for hackrf to be engineered to go from elf waves 1hz - 10ghz buy having the downconverters and up-converters printed into the board. Is there any firmware/software updates I have to do to get this to work?

**Comment by mossmann** [comment]
The answer is almost certainly yes: If you add elements to the design that are meant to be configurable in some way, you'll need some way to configure them, and that would require changes to both firmware and host code.
