### ISSUE TITLE
talking to the HackRF from an RCA Cambio 10 (win10 32bit?)

### ISSUE THREAD

**Issue by orrinwinton** [mossmann/hackrf#525]
Apologies if this has been covered again & again; i tried a search and found nothing.

(1) I communicate just fine with the HackRF using Ubuntu, Pentoo, etc.
(2) Just installed the Pothos suite on my Win10 64bit laptop, and e.g. hackrf_info.exe talks to the HackRF.
(3) Am finding that my 'new' RCA Cambio tablet/notebook won't run anything in the Pothos suite. Apparently the RCA uses a 32-bit version of Win10 (with a 64bit architecture?).
(4) A separate install of SDR# on the RCA does talk to the HackRF just fine.

I would like to get the RCA to run (as a test) hackrf_info.exe to talk to the HackRF. Has anyone wrestled with this issue? 

Possibly i should just stick with Linux, and i shall, but am exploring what the RCA Cambio can and can't do. Thanks for any comments. --orrin

**Comment by dominicgs** [comment]
Unfortunately the PothosSDR binaries only appear to be built for 64 bit Windows, so you'll need to build things from source.  I have recently update the [OS specific build instructions](https://github.com/mossmann/hackrf/wiki/Operating-System-Tips#windows-1).  Let me know what does and doesn't work for you.
