### ISSUE TITLE
hackrf_operacake: match port designations to silkscreen

### ISSUE THREAD

**Issue by dominicgs** [mossmann/hackrf#531]
When I wrote the `hackrf_operacake` tool it used a 0-7 numbering system to represent the ports.  The ports are labelled, we should use those labels in software to match the two up.

**Comment by mossmann** [comment]
Ports will be designated A0, A1, A2, A3, A4, B0, B1, B2, B3, B4 with A0 and B0 being primary ports and the others being secondary.
