### ISSUE TITLE
TX problem

### ISSUE THREAD

**Issue by mehdi-tazi-chellal** [mossmann/hackrf#537]
Hi everyone,
I am new in using HackRF One. I am trying to generate a signal with GNU Radio( WINDOWS version) and transmit it with HackRF One. The problem is when I try to test if I transmit something with a second HackRF One or an spectrum analyser I don't receive anything and the TX led is red. I tried a lot of tutorials in the net but no one works. If anyone can help me, please do it because I am really blocked. Thank you!!

**Comment by mehdi-tazi-chellal** [comment]
Hi,
Thank you for answering me. Now and after changing some parameters in sending and receiving part (RF,IF and BB gain), I can see the signal. But the quality of the signal changes when I change the band frequency( 2.4GHZ band, 5GHz band) and also It's a bad quality. If you know why it changes and how could I ameliorate the quality of the received signal please let me know. I joined here the flowgraph and the information in the command prompt. Thank you very much !!
![commandprompt](https://user-images.githubusercontent.com/44052864/46861300-aa7f4200-ce12-11e8-9602-1eca120e3a1a.png)
![flowgraph](https://user-images.githubusercontent.com/44052864/46861301-aa7f4200-ce12-11e8-9864-884c3cd49b2f.png)

**Comment by dominicgs** [comment]
I have a few questions:
 * How are you defining quality of the signal here?
 * 1MSps is a low sample rate for HackRF One, could you try using a higher one?
 * What antennas are you using?  Or are the HackRFs connected through an attenuator?
 * Your signal source and osmocom sink are using different sample rates
 * The bandwidth of your GUI sink is 20 MHz but you're only feeding it 1MHz of data - this probably won't cause an issue, but it might look unexpected

**Comment by mehdi-tazi-chellal** [comment]
Hi , 
when I am speaking about the quality of signal that's mean that I don't receive quietly the same emitted signal. There is lots of perturbations.
I don't use any antenna, I am using an SMA male plug. 
when I try to increase the sps I lose the signal. With this values I can see the signal but not the same one emitted.

**Comment by mehdi-tazi-chellal** [comment]
Hello, 
No the HackRF are not diirectly connected. here is a photo of them.
![44190210_284458378840995_4487542965148844032_n](https://user-images.githubusercontent.com/44052864/46936728-98461380-d05f-11e8-97d9-9b7091afbd4a.jpg)
Thank you :)

**Comment by mehdi-tazi-chellal** [comment]
hello,
I am generating a signal using the vector source and I want to variate the values in the vector source with the block GUI RANGE. the problem is when I begin the simulation and I change the values nothing happen to the graph. Please answer me if you have any suggestions. here is a photo of my program in GNU RADIO. Thank you.
![gui range](https://user-images.githubusercontent.com/44052864/47288084-cf369f00-d5f4-11e8-9c25-cc03eb924123.png)

**Comment by mossmann** [comment]
I'm seeing several different errors and misunderstandings represented in the above GNU Radio flowgraphs.  I suggest starting with my video series to learn how to use GNU Radio with HackRF:

https://greatscottgadgets.com/sdr/
