### ISSUE TITLE
hackrf constantly appearing and disappearing from USB?

### ISSUE THREAD

**Issue by nardev** [mossmann/hackrf#543]
I understand that it's less likely a hackrf issue, but just in case if somebody had this issue before.

When plugged in, hackrf loops between being detectable and disappearing.

    $ hackrf_info 
    Found HackRF board 0:
    hackrf_open() failed: HACKRF_ERROR_LIBUSB (-1000)

i'm using debian, kernel 4+

Any idea?

**Comment by nardev** [comment]
I'll, most likely.. although it was working on this very port before and actually i already tried other  ports.

**Comment by cjheath** [comment]
Grab the output of _dmesg_ and see what it says about the USB enumeration.

**Comment by dominicgs** [comment]
@nardev Any update on this?  Did you get the output from `dmesg`?

**Comment by nardev** [comment]
@dominicgs unfortunately no, will try do at Sunday.

**Comment by luoGanda** [comment]
in my case, this was a bad usb connector - some are not as tight as they should be.
So i just put into another usb and it worked.
