### ISSUE TITLE
USB(?) interference via antenna from the lowest frequencies to above 190 MHz

### ISSUE THREAD

**Issue by lastfuture** [mossmann/hackrf#544]
### Steps to reproduce
1. Connect Ant500 and extend it
2. Connect HackRF One with stock USB cable that came with HackRF One
3. Tune GQRX or GNU Radio to 90-100 MHz
4. Set gain to 24 dB IF and 30 dB BB
5. Observe FFT or waterfall

### Expected behaviour
smooth noise floor, random irregular noise pattern if any

### Actual behaviour
regular spikes and spurs and static noise characteristics as can be seen here
<img width="1342" alt="screenshot 2018-11-05 at 03 56 21" src="https://user-images.githubusercontent.com/4239297/47975846-fd65b580-e0af-11e8-97b0-e575c1f23b02.png">

Also very distinct noise around 480 MHz where USB 2 has its clock frequency
<img width="1341" alt="screenshot 2018-11-05 at 03 58 07" src="https://user-images.githubusercontent.com/4239297/47975889-2c7c2700-e0b0-11e8-8f62-bace020bb986.png">

### Additional info
The strength of both the regular noise patterns and the peaks around 480 MHz can be influenced by covering the cable with my hand, where covering the cable makes the noise pattern more prominent but reduces the intensity of the peaks around 480 MHz.

The noise is not visible when no antenna is connected, but it will always roughly scale with the strength of FM reception, even with antennae that are not tuned to the FM spectrum.

The noise will also entirely disappear when connecting HackRF to analog cable directly, even though the FM stations on there have a similar signal strength to the ones picked up via antenna. The noise floor is then smooth as expected

The computers I tested with are:
* iMac late 2012
* MacBook Pro 2018 via USB Type C plug to USB Type A socket adapter, both on battery and wall power

Noise intensity and characteristics are very similar on both machines

### Version information
**Operating system**:  
MacOS 10.14

**hackrf_info output:**  
```
hackrf_info version: unknown
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Serial number: 000000000000000087c867dc2b53b45f
Board ID Number: 2 (HackRF One)
Firmware Version: 2018.01.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x006e475a
```

Gqrx version 2.11.5  
GNU Radio 3.7.10.1

**Comment by lastfuture** [comment]
I've purchased a 20cm shielded USB Type C to Micro USB cable in an attempt to reduce both length of the cable and amount of plugs in the hopes it would make the phenomenon better.

Yikes! It makes the problem about 20 dB worse than the USB Type C to USB Type A adapter + USB cable included with HackRF.

Any suggestions as to how I can remedy the interference problem would be greatly appreciated.

**Comment by unixpunk** [comment]
Have you tried this with another antenna yet?  Or an antenna (connected via cable) that is not near the device/computer like the ANT500 is by its nature?

**Comment by lastfuture** [comment]
Yes. I've tried an antenna stand with 2m RG58 cable that came with my NooElec NeSDR Smart kit, similar to the one pictured here:
![sku_5188_1](https://user-images.githubusercontent.com/4239297/48040804-be506680-e17a-11e8-824e-c0698200c3f0.jpg)

I made a conscious effort to stretch the cable as far as possible with the computer and the HackRF across the room

* with their telescopic antenna extended by the same amount
  * the result was the same as with the ANT500 connected directly
* with their differently tuned antennae
  * the FM signals were weaker and the spurs were weaker by the same amount, resulting in roughly the same dB difference between signal and noise

I've also tried walking around with this solution in hand using the telescopic antenna. Curiously the noise always seemed to increase/decrease with the FM signal strength.

I can very easily and repeatedly demonstrate that the noise gets considerably worse as soon as I put my hand on the USB cable. This screenshot shows me repeatedly touching and letting go of the USB cable. The same doesn't happen when I touch the coax cable
<img width="1339" alt="screenshot 2018-11-06 at 04 10 39" src="https://user-images.githubusercontent.com/4239297/48040664-2ce0f480-e17a-11e8-90f3-6afa1b68e4fe.png">

**Comment by lastfuture** [comment]
Another test: This is me touching the USB cable first diectly at the computer, then increasingly closer to the HackRF in steps of about a hand's width apart. You can see the amplification of the interference gets worse the closer to the HackRF I touch the USB cable. None of this can be seen when I touch or cover the HackRF directly with my hand, or when I touch the coax cable.

<img width="1337" alt="screenshot 2018-11-06 at 04 30 24" src="https://user-images.githubusercontent.com/4239297/48041346-07091f00-e17d-11e8-81e7-369dc7b608f6.png">

**Comment by cjheath** [comment]
Try with the HackRF and laptop sitting on a metal bench (or kitchen sink?) to provide capacitive ground coupling between them. This will reduce pickup via the USB cable. Also, is your laptop running on batteries or power pack, and have you turned off other potential sources of local interference?

**Comment by lastfuture** [comment]
Capacitive ground coupling via a kitchen sink improved the noise significantly! (Moving away from any possible RF interference did nothing, I tried in the middle of a cemetary)

<img width="1059" alt="screenshot 2018-11-06 at 18 21 08" src="https://user-images.githubusercontent.com/4239297/48081712-f4c8c880-e1f0-11e8-97ec-ab9ddff98009.png">

Alright! What can I do to make this effect more permanent? I hope I don't have to carry a sheet of metal with me everywhere I want to use my HackRF.

**Comment by lastfuture** [comment]
It makes no difference if the laptop runs on battery or is plugged into wall power by the way, forgot to answer that part

**Comment by N8AUM** [comment]
Buy one of those cheap usb dongles and see how it reacts.Good luck,N8AUM

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 6, 2018 at 12:26 PM, Peter Marquardt<notifications@github.com> wrote:   
Dang, I'm sorry I have to drag this out, but the previous test was with the sink at work.

The sink at home as well as a metal baking tray have no effect. If anything they make it worse

**Comment by lastfuture** [comment]
I have an RTL-SDR dongle. It exhibits the same kind of interference.

Something else I just tried: I got my fingers on an FM band stop filter, and it eliminates the FM signals as expected, and also the interference along with them. That's both with the ANT500 and with the telescopic antenna connected via 2 meters of coax cable.

I've also tried on a third computer now, a 2016 MacBook. The interference looks the same there as well. The interference also looked almost the same at work on my MacBook Pro, several km from here. I'm not the only one using Macs with HackRF though, so this can't be a Mac thing, right?

**Comment by lastfuture** [comment]
Just out of curiosity, how does the FM band look for you people around 97 MHz with the amp off, IF gain on 24 dB and BB gain on 30 dB?

**Comment by unixpunk** [comment]
I checked this last night and for me the band looks similar to your screenshot for when you put things on the sink at work.  Quite except for the actual stations, no spikes every N khz or whatever.  I'm running PC though and my HackRF is in a metal case that houses the portapack with it.  I also don't have the original cable, I use a cable from monoprice that has a built in ferrite choke and gold-plated connectors.

**Comment by lastfuture** [comment]
My HackRF is in the plastic enclosure it's usually sold with. Do you think things could improve with it in an extruded aluminum enclosure?

**Comment by unixpunk** [comment]
Do you have the shielding/cage added to the hackrf board?  I would suggest doing one of the two, either add the cage/shield or get the metal case.  One option is more work but far less money than the other.  (I have both)

**Comment by lastfuture** [comment]
I'm prone to damaging electronics when I do fiddly work on them, so I'd rather shell out extra money for the enclosure and not worry about any damage I could deal. Installing the shield sounds hard

**Comment by cjheath** [comment]
If you want to know whether a shield will help, try the HackRF inside a cake tin (cut small holes for the USB and antenna leads). But this is really only for externally radiated noise, probably not your issue. The on-board shield protects the receiver from noise radiated from the rest of the HackRF.

However, your symptoms are caused by a noisy PC/laptop (noise on the USB ground), and lack of an earth on the HackRF. Isolate the HackRF with a CMC and earth it, use a CMC on the antenna too if you can, and you'll find the problem vanishes.

**Comment by lastfuture** [comment]
I tested if I could find surfaces in the house and in the street where reception would get better like on the sink at work, but all I got was various patterns of interference

I'm posting these in the hope that someone recognizes a pattern that suggests a solution

HackRF and Laptop on the hood of our car (signal went crazy)
<img width="1303" alt="screenshot 2018-11-06 at 23 12 17-hood" src="https://user-images.githubusercontent.com/4239297/48097783-1a6ac780-e21b-11e8-9797-4e45538e18f8.png">

In the middle of the street holding the HackRF an arms length away from the laptop, then close
<img width="1303" alt="screenshot 2018-11-06 at 23 06 02-street" src="https://user-images.githubusercontent.com/4239297/48097824-32424b80-e21b-11e8-933c-33afd736b5fd.png">

On a solid wood surface
<img width="1301" alt="screenshot 2018-11-06 at 22 50 10-solid-wood" src="https://user-images.githubusercontent.com/4239297/48097837-3d957700-e21b-11e8-9a08-47555c272cdd.png">

Putting it and the laptop onto the metal railing of our balcony (signal went semi crazy)
<img width="1301" alt="screenshot 2018-11-06 at 22 49 26-railing" src="https://user-images.githubusercontent.com/4239297/48097855-4dad5680-e21b-11e8-919e-9a664e549073.png">

On various surfaces in the kitchen (sink, stovetop, press board work surface)
<img width="1305" alt="screenshot 2018-11-06 at 22 48 31-kitchen" src="https://user-images.githubusercontent.com/4239297/48097940-8ea56b00-e21b-11e8-875f-466880cdbf05.png">

**Comment by cjheath** [comment]
You can stop with the location tests! I suggested the sink because it's probably earthed (your home must have plastic plumbing) to see if it looked like conducted or radiated noise. You clearly need an earth, and to isolate your HackRF from the noisy laptop.

**Comment by lastfuture** [comment]
Thank you @cjheath 
As english isn't my first language, with station earth you mean earth as in ground from e.g. plumbing, right? Where would I connect it to? The SMA thread?

**Comment by lastfuture** [comment]
If I understand the schematic all three SMA connector threads share common ground with the rest of the device, so I could make a grounded SMA connector minus the center pin and connect it e.g. to clkout, correct?

**Comment by cjheath** [comment]
Plumbing is a good start, otherwise your house power earth (connect a single short earth wire into a 3-pin socket). The best place to connect on the HackRF is the shield of the antenna input. You could solder an earth connector to the base of the antenna SMA socket.

First though, I'd be looking for a USB cable with a CMC built-in (the lump in the cable). Does yours have this?

**Comment by lastfuture** [comment]
It doesn't, the device came with a cable that has no lumps. I do have one ferrite core but if I understand correctly the choke has wire wound around it, which obviously is a difference.

I'll be looking for a cable with chokes on both sides as you described

**Comment by cjheath** [comment]
Passing the USB cable even once through a toroid will help, better if you can do two or three turns. Or use one like these:
![20181107_094911](https://user-images.githubusercontent.com/1703/48099363-6ea19600-e273-11e8-9e05-89d92ff0f45c.jpg)

**Comment by dominicgs** [comment]
I agree with @cjheath, I strongly recommend using one of those cables if you see this issue.

**Comment by lastfuture** [comment]
I found a Micro USB cable with two chokes on either end today and was excited, but it makes the problem worse than it is with the included cable.

included cable:
<img width="1239" alt="screenshot 2018-11-07 at 20 44 56" src="https://user-images.githubusercontent.com/4239297/48157188-4b0c3900-e2cf-11e8-8bbf-05eceda1296f.png">

cable with chokes:
<img width="1237" alt="screenshot 2018-11-07 at 20 44 09" src="https://user-images.githubusercontent.com/4239297/48157199-52334700-e2cf-11e8-9fd1-147f4c0c9fad.png">

These screenshots were taken seconds apart in the same location with the same settings.

I also tried a makeshift ground wire, holding one end to the ground of an outlet and the other to the thread of the antenna SMA connector, but either I wasn't able to make a connection or I did make a connection but it made no difference.

Can I be doing anything else wrong here? I feel like this has the potential to be really stupid user error given that none of the advice worked so far and you're very likely operating HackRFs much longer than me.
Just to make extra sure I'm not messing something up on the software level here, these are my settings. Can somebody please confirm that my Gqrx setup looks sound?

<img width="454" alt="screenshot 2018-11-07 at 20 59 19" src="https://user-images.githubusercontent.com/4239297/48157648-82c7b080-e2d0-11e8-876d-41161a15cc98.png">
<img width="337" alt="screenshot 2018-11-07 at 20 59 30" src="https://user-images.githubusercontent.com/4239297/48157651-85c2a100-e2d0-11e8-8b27-2d65369a2c97.png">
<img width="338" alt="screenshot 2018-11-07 at 20 59 45" src="https://user-images.githubusercontent.com/4239297/48157660-89eebe80-e2d0-11e8-917a-edcc88a5aa31.png">

(more Msps make it worse, fewer make it slightly better)

**Comment by lastfuture** [comment]
I've tried six more cables today, with choke, without choke, direct USB-C to Micro B, via adapter, via powered and unpowered hub. This is the absolute cleanest signal I can get and I'm super frustrated

<img width="1324" alt="screenshot 2018-11-08 at 19 41 02" src="https://user-images.githubusercontent.com/4239297/48220407-78b8b700-e38f-11e8-9147-010b2103e287.png">

I've also tried a fourth laptop with not much more luck

**Comment by James-Brown** [comment]
Peter. I haven’t followed this whole thread but does the ‘hair’ go away when you turn off the RF Amp? If so I would bet of an amplifier that is oscillating.

**Comment by lastfuture** [comment]
All of this is with the RF amp off. If I turn the RF amp on it looks exactly the same but about 10-15 dB stronger

**Comment by barto-** [comment]
You could try to install an optional RF shield. Check this video https://youtu.be/IQ_I8q3IUFs

**Comment by lastfuture** [comment]
To summarize:

The cleanest signal is still with the included USB cable. All other USB cables I've tried now, including the one with two chokes, produce a noisier signal. There's only one other cable in the bunch that also performs the same as the included cable.

A powered USB hub didn't help.

I've not been able to get a clean signal without the spurs on five computers, four of them laptops, four of them running macOS and one running Ubuntu.

Gqrx and GNU Radio agree on the FFT spectrum and they both show the spurs. I can also clearly hear it in the FM demodulation of weaker stations

The spurs disappear with no antenna connected or with a cable connected directly to the analog TV cable that also serves FM radio stations. Those come in super clear with no spurs in sight and a baby smooth noise floor.

The spurs are always there when an antenna is connected (except when a FM band stop filter is present), even in different locations (e.g. at home, at work) and with most electronics around turned off or far away from other electronics except the laptop. There is also no difference whether I use the ANT500 connected directly or another telescopic antenna connected via 2m long coax cable.

It happens with the laptop on battery power and powered via wall plug.

An RTL-SDR dongle exhibits similar (but differently spaced) spurs.


… taking all of this into account there are a few common denominators left that I can think of.
* I've performed all the tests in the same city.
* I'm always nearby when testing.
* There's always an antenna connected. (except for my test with cable)
* It's always a USB connection (and I think always capable of USB 3.0 or faster).
* I've performed all tests between 6 PM and 3 AM.
* I'm almost always using Gqrx and the same HackRF One. (except for my tests with GNU Radio and the test with the RTL-SDR dongle)
* The spurs always start tapering off above about 190 MHz until they're mostly gone at 210 MHz
* The HackRF has no RF shield and is in the injection molded plastic case

**Comment by lastfuture** [comment]
Here's one more thing I've just tested and which got me thinking:

The difference between the following two screenshots is that for the first screenshot I've misused an AM loop antenna (at 24 gain IF, 30 gain BB) and in the second one I tried matching the energy and FFT as closely as possible with the ANT500 extended (at 16 gain IF, 18 dB gain BB)

<img width="1322" alt="screenshot 2018-11-08 at 23 43 19" src="https://user-images.githubusercontent.com/4239297/48232550-43719080-e3b2-11e8-9808-8e8cfb946692.png">
<img width="1323" alt="screenshot 2018-11-08 at 23 53 15" src="https://user-images.githubusercontent.com/4239297/48232558-479dae00-e3b2-11e8-839b-d1fc07a09827.png">

The spurs are almost absent using the antenna meant for AM radio, even at higher amplification levels.
This got me thinking. I've read that an antenna can pick up signals well if it's the length of one wavelength, half a wavelength or a quarter wavelength. (Entering solid half-knowledge territory here)

* The AM antenna is about 3.5m long, which must roughly make it good at picking up 85.6 MHz, 42.8 MHz and 21.4 MHz
* ANT500 is about 72 cm extended. That means it would be roughly tuned to 416 MHz, 208 MHz and 104 MHz

Could this mean the spurious signals interfering with my HackRF must come from around 208 or 416 MHz since they're absent with the AM antenna?

Continuing that thought this would strengthen the theory that the component actually picking up the noise is the antenna, and in the light of everything else I've tested I know it's highly dependent on the cable, suggesting the cable is transmitting the noise. Since the USB 2.0 bus frequency of 480 MHz still seems to be the likely source and regarding the cable as a transmitting antenna, and assuming similar wavelengths calculations from above apply to sending antennae it would make sense that the length of the cable has something to do with the amount of noise present (along with its shielding I assume, but I can't measure that easily).

* The cables with which I got the best signal to noise ratio are 80cm and 95cm. Would that make them not good for transmitting 480 MHz?
* The worst cables were short, 25cm and 20cm. Could they be much better at transmitting close to 480 MHz?

Does that help me solve my problem?

**Comment by lastfuture** [comment]
… and following that train of thought, which length of USB cable would be the worst possible at transmitting 480 MHz?

**Comment by cjheath** [comment]
The spurs are probably all harmonics. Of whatever the spacing is. What is
it?

**Comment by lastfuture** [comment]
It looks like they're pretty much spaced 48 kHz apart, which incidentally is also the audio output's sample rate. What does that mean?

**Comment by lastfuture** [comment]
I have to revise my answer, those are the coarse spurs, if I increase the HackRF's sample rate I can also see fine spurs which fall into an 8 kHz raster

**Comment by lastfuture** [comment]
Here's a close up of the spurs. The ones at 48 kHz intervals are fanned out while the ones at 8 kHz intervals are sharp
<img width="1663" alt="screenshot 2018-11-09 at 23 04 03" src="https://user-images.githubusercontent.com/4239297/48290629-da525180-e473-11e8-841a-82925543f8d5.png">

**Comment by lastfuture** [comment]
I've had the unexpected opportunity of talking to the former Director of National System Development for Cellular One about this. He said this is very likely heterodyning. He said my working theory about the USB cable transmitting (resonant close to a quarter wave of 480 MHz) and the ANT500 receiving (close to a half-wave of 480 MHz) isn't far off. I'm on the right track about varying the length of USB cable in order to reduce the interference but since we don't know the primary heterodyne component I'm left to trial and error.

So I've decided to introduce as much trial into trial and error as I can. Perhaps I can build a variable length USB cable.

I'm learning a lot about RF and It's exciting

**Comment by cjheath** [comment]
I have the RF shield off mine because I expect to replace an MMIC soon. I see a lot of regularly-spaced (8KHz) spurs filling the frequencies between 27MHz and 33MHz. I think they're very likely from an internal source. Also spurs on 10MHz multiples running up to a couple hundred MHz (possibly from the new TCXO I just added?) I'll let you know what I find as I experiment further. I haven't tried connecting one of my large external antennas yet, for example.

**Comment by lastfuture** [comment]
I see the 10 MHz spurs you describe as well.

The strength of my spurs in the FM band seems to be very dependant on the antenna connected, and they disappear in certain cases. I'm therefore assuming that it's not an internal component causing them

**Comment by lastfuture** [comment]
I've tried two 1.8m USB cables that resulted in terrible noise. The USB cables yielding the best signal to noise ratio so far are 1m and 90cm. I'm going to try to confirm my cable length theory with more cables close to 1m in length.

I'm also braving up and installing an RF shield, even though my observations point towards it coming through the antenna. My soldering skills are not the best but I figured it should be doable and an RF shield certainly won't make it worse, right?

**Comment by cjheath** [comment]
You're probably aware of this, but a more efficient antenna that's *not* receiving the spurs will push them down in relative level. So you need to look at the absolute level to know what's going on.
Also, making a shield doesn't require soldering, if your board has the clips for it. It just requires some accurate metal bending and careful trimming.

**Comment by lastfuture** [comment]
So far three telescopic antennae which were all tuned to somewhere in the FM spectrum received the spurs at pretty much the same absolute level. My point of reference is one particular FM radio station that just about comes through the spurs with the best USB cable. I'm judging my USB cables by both the absolute intensity of the spurs in dBFS and by the intensity of my reference radio station in relation to the peaks of the spurs (and audible quality of the WFM demodulated sound)

My observation so far is:
* My USB cables close to 1m yield spurs peaking at around -80 dBFS and the radio station is visible in the noise and has some static but can be heard OK
* The USB cables much longer or shorter than 1m yield spurs peaking at around -65 dBFS and the radio station is harder to see in the FFT as well as much more staticky all the way to undetectable

To be honest I don't know if my board has clips for it or how they would look. With clips do you mean the holes in between the solder pads as can be seen in this image? https://camo.githubusercontent.com/fc5fea2c0ccc11b91ce651b812bc1d6cd0fbbfc9/68747470733a2f2f7261772e6769746875622e636f6d2f6d6f73736d616e6e2f6861636b72662f6d61737465722f646f632f4861636b52462d4f6e652d6664302d303030392e6a706567

**Comment by cjheath** [comment]
I assume you aren't using AGC (input settings) but setting RF and IF gain manually.

I mean the clips on the dashed RF boundary trace in this photo.
![20181113_103325](https://user-images.githubusercontent.com/1703/48381456-026dd900-e730-11e8-8857-5ffecbe3704f.jpg)

**Comment by lastfuture** [comment]
Yes, always the same gain settings: no RF gain, 24 dB IF and 30 dB BB. Those are the gain settings that make my reference FM radio station come in the clearest with the good cable. I'm also always cross-referencing against the good cable just in case other outside effects (e.g. atmospheric phenomena) changed how well this particular station is reaching me.

I didn't know some boards had these clips. I'm going to open my HackRF's case when I get the shield so I won't know until probably Saturday, unless there's another way to find out

**Comment by lastfuture** [comment]
OK so this is what my FM radio spectrum noise floor is supposed to look like, huh?

My sample size of possible USB cables has grown so much that I can now confidently say 0.9-1.0m length seems to be close to the sweet spot, 1.6-1.8m are terrible and 0.2m-0.4m are also terrible, all pretty much regardless of cable quality.

I'm pretty certain I'm not the only one using a HackRF and its included USB cable with a recent 2018 MacBook Pro Touch Bar, a 2012 iMac or a 2016 MacBook. Shouldn't there be more reports about this in that case?
Since those computers all show the spurs all the time in repeated tests … could my HackRF be defective?

**Comment by lastfuture** [comment]
Speaking of TCXOs … my HackRF is off by -25ppm, could that be related to the spurs?
As far as I can see a new TCXO is plug-and-play. Put it on the respective pins and it's in use instead of the built in oscillator. It couldn't hurt to try one, right?

**Comment by cjheath** [comment]
Right. Not quite plug and play, I had to bend two of the ISP pins down to
clear the oscillator can. I don't know if TCXOs are available with
different geometry. If I need to use ISP (hopefully not) I'll fit
right-angle header pins out the back of the board.

**Comment by cjheath** [comment]
Your problem is not your cables, they're just changing how you see the problem. Neither is lack of a TXCO I reckon, or you'd see a more variable result (drifting spurs, varying spacing, etc). It's most likely something about your computer or your location. Take stuff to another suburb, and try a different computer. If the problem goes away, your HackRF is probably fine, otherwise it's busted. It could be a simple matter of bad power supply bypassing (dud cap, or bad soldering). You might be able to fix it by reflowing the board...

**Comment by mossmann** [comment]
cjheath wrote:

> I mean the clips on the dashed RF boundary trace in this photo.

I've never seen clips like that before.  I didn't design for them, and we don't install them on Great Scott Gadgets boards.  I don't know who made your HackRF One, but its origin may have something to do with why it doesn't perform at lower frequencies.

I designed the RF section of HackRF One to fit the Laird BMI-S-230-C RF shield on the BMI-S-230-F-R frame.  We do not install the shield or frame on the units we sell.

**Comment by mossmann** [comment]
lastfuture: Everything you have reported appears normal to me.  It is common to pick up USB interference with a USB-connected radio receiver such as HackRF One, and most of that interference should be between 0 and 240 MHz.  It is common for changes in USB cables, antennas, grounding, and coupling with nearby objects to affect how this interference is conducted/radiated/received.

I do not believe your HackRF One is defective.  (If you were seeing interference above -40 dbFS with moderate gain settings I might think differently.)  It is unsurprising to me that you see a similar interference pattern with different spacing when using an rtl-sdr dongle.  HackRF One has a higher  maximum USB data rate, so it should typically result in more spurs per bandwidth.

The USB cables we include with HackRF One were selected based on some testing I did which indicated that the quality of shielding was much more important than the quality or presence of a ferrite.  Be aware that some USB cables have better shielding than others, and many USB cables (especially those intended primarily for charging) have no shielding at all.  You can test the shielding with an ohmmeter.  Also be aware that some USB cables that appear to have a ferrite actually just have an empty shell where a ferrite could go.

**Comment by lastfuture** [comment]
@mossmann thank you, your assessment of my situation means a lot. I guess I had too high expectations after seeing much cleaner spur free noise floors in videos showing off HackRF.

The spurs definitely feel like they're sullying signals I could otherwise demodulate. e.g. I've not managed to even find more than one AM radio station, and that station was barely distinguishable from the spurs and came in just clear enough to barely make out its name when it was announced. I've not been able to find the signal in the noise again, even though I've bookmarked its frequency, and even though I'm now trying with an antenna that should theoretically be tuned to roughly a quarter wavelength

**Comment by cjheath** [comment]
@mossmann Thanks. Sad that the HackRF I bought (2nd hand and damaged) might not be genuine. Nothing about it looks sub-standard, but I suppose that goes with the territory. I guess the mixer baluns are a spot where a clone-maker might skimp? Or perhaps the software is just not enabling the correct filter path. Anything else I can do to check what's causing low-band deafness? Or perhaps I just don't have an adequate antenna?

The PCB is labelled "13 February 2014".
`hackrf_info` says my serial number is 0000000000000000167c60c837524be7
Firmware Version: 2017.02.1 (API:1.02)
Part ID Number: 0xa0000a30 0x00624f5d, does that look plausible?

@lastfuture perhaps try to use a better antenna? The best first answer to SNR problems is "get more signal" :)

**Comment by lastfuture** [comment]
OK, I've installed the full monty now. TCXO, RF shield, aluminum enclosure. A first test with the ANT500 is looking very promising. A LOT better than in its factory state in the original case.

The TCXO is bumping the HackRF from -25ppm to 0ppm, and I managed not to fry it while soldering the RF shield, so hooray.

<img width="1634" alt="screenshot 2018-11-17 at 15 41 07" src="https://user-images.githubusercontent.com/4239297/48662290-666e0580-ea80-11e8-9d08-465511975d68.png">

This time for the first time the spurs aren't stable and changing intensity. I'm not entirely sure what's going on or what could be causing it. The screenshot above shows the absolute best that the s/n ratio gets. The worst looks almost like the best before the modifications. It seems to be somewhere in between for the most time.
I'm going to leave this running for a few hours away from the laptop with a slow waterfall and take a look at it later to see if it's changing without me being around.

**Comment by lastfuture** [comment]
There was no difference after a few minutes, the spectrum stayed in the "somewhere between" I mentioned.

However I learned that the difference between these two orientations of the HackRF …
![img_1660](https://user-images.githubusercontent.com/4239297/48665528-6d147100-eab0-11e8-97a2-55640135e46a.JPG)

… results in this difference in spectrum.
<img width="1292" alt="screenshot 2018-11-17 at 21 27 51" src="https://user-images.githubusercontent.com/4239297/48665530-743b7f00-eab0-11e8-9b38-ab338fb98a2f.png">

I'll have to be extra careful how I position it

**Comment by mossmann** [comment]
cjheath: It may be a genuine GSG board that has been modified. If it is one of our boards it should have the GSG gear logo visible on the bottom copper layer.  If it is not a GSG board, the most likely component substitutions that would affect the low frequency performance would be the DC blocking capacitors and inductors in the RF section.

Use of a proper antenna for the frequency of interest is important for performance.  ANT500 is not appropriate for anything below about 75 MHz.

It is expected for the performance at 1 MHz to be about 10 dB worse than the performance above 10 MHz.  See: https://greatscottgadgets.com/2015/05-15-hackrf-one-1MHz/

**Comment by mossmann** [comment]
lastfuture: Congrats on the successful mod! The results from that change of orientation are fascinating.

**Comment by lastfuture** [comment]
I'm still seeing a lot of spurs all across the spectrum (with the ANT500 and a similar telescopic antenna in particular), some of them making it harder for me as a learner to separate proper signals from the noise. e.g. this is my spectrum around 433 MHz at much more reasonable gain settings of RF off, IF 16 dB, BB 16 dB

I know that the ANT500 is probably not the best antenna for that frequency range, but can you please take a look at these and tell me if they're supposed to look that way?

at 20 Msps
<img width="1293" alt="screenshot 2018-11-19 at 23 26 12" src="https://user-images.githubusercontent.com/4239297/48739017-fe234d80-ec52-11e8-8416-44b7c28b727d.png">

at 12.5 Msps
<img width="1295" alt="screenshot 2018-11-19 at 23 32 20" src="https://user-images.githubusercontent.com/4239297/48739173-6eca6a00-ec53-11e8-93fd-3f10f785c645.png">

at 8 Msps
<img width="1296" alt="screenshot 2018-11-19 at 23 30 49" src="https://user-images.githubusercontent.com/4239297/48739117-3aef4480-ec53-11e8-8006-4c04d31533a5.png">

I'm assuming all of the spikes I see are spurs as they're permanent and don't _seem_ to be signals. Also quite a few of them are moving into the opposite direction of the direction i'm tuning, and they're mirrored around the center frequency, making me believe they're some sort of aliasing artifacts (?) The actual signals in this ISM band (mostly outside thermometers of neighbors' weather stations) are coming in at around 20 dB quieter than the loudest spurs.

If I'm honest I'm a bit disappointed with my HackRF experience right now. I had hoped for a cleaner spectrum for me to learn in. I'd still really love to do more to get it cleaner and spur-free. It's also making it hard for me to be a good neighbor on the spectrum as I learned I should be, because I need pretty CPU intensive settings on my band pass filter in order to prepare signals for replaying while leaving out the spurs. So steep in fact that I have to prepare them offline

**Comment by mossmann** [comment]
@lastfuture: I really don't think you have a problem with spurs.  If you go looking deep into the noise floor with any radio receiver, you will find such things.  I think you may have a problem with the received signal strength of your signals of interest, however.  Signals such as your neighbor's weather station should be detectable at a higher power than the spurs.

Do you happen to have an RF signal generator or a friend with another HackRF that you could use to perform a measurement?

**Comment by lastfuture** [comment]
Unfortunately I have neither an RF signal generator nor a friend with a HackRF. I do have a few remotes that will generate signals but I have no way of knowing in which intensity. I could compare the same remote received with the HackRF and with a NooElec neSDR SMArt if that would help

**Comment by unixpunk** [comment]
@lastfuture You mentioned the TXCO, that could be the noise you see every 10mhz.  Unless you're doing specific things where having a perfect click is required, might try taking that out of the mix.  Will you have to adjust ppm offset then?  Sure, but once you know what that offset is when the device is up to temp (by comparing to a known-stable signal), it usually doesn't change much.  As Mossman mentioned and as your LTE band antenna points to further, you may just need a better tuned antenna so that your desired signal is stronger and also so that other noise is tuned out.  The gains are also important, you may find that having one too high over the other causes some spurs to show or disappear even.  Sometimes having the LNA/amp on is better, then you can lower the other gains or vice-versa.  Hope that helps.

**Comment by mossmann** [comment]
I agree with @unixpunk that the TXCO could be a source of some spurs.

The SNR of the DECT screenshot looks good at a glance, but I notice that none of those peaks is higher than the DC spike.  They should be if the DECT devices are at close range.

**Comment by lastfuture** [comment]
I've noticed the spikes at 10 MHz intervals with the internal clock as well, before I ordered the TCXO. I'll try and remove it again to compare directly though. If I only had 10 MHz spurs I'd be happy.

The DECT base stations I'm picking up are all my neighbors' because I don't own one. No knowing how far they actually are or what's attenuating them on their way to me.

When I've looked at signals from remotes (RC car, garage door opener) I did get signals rising above the DC spike in power. In general signals from the neighborhood though or from the remote a few meters across the room never rose above the DC spike if I remember correctly. I can perform some tests with the remotes I've tried when I get home.

Am I right in dividing the speed of light over the frequency to get the length that the ANT500 should roughly be extended to for a given frequency? That would mean 67cm should be tuned for 443 MHz ish signals. In that case with the ANT500 and with my garage remote sending around that frequency, what intensity would you expect the signal to be from 2m away, relative to the DC spike? (or absolute in dBFS at specific gain settings). I know this depends on the remote, but what ball park should it be in?

**Comment by lastfuture** [comment]
I'm sorry, I'm of course talking about the 433 MHz ISM band and got my numbers mixed up, so my antenna length would work out to about 69 cm, right?

I was about to start testing signal strengths and this HackRF remains a mystery to me. The signal to noise ratio of the neighbors' weather stations etc. is still weak, but where did most of the spurs go now? I've clearly had them as you can seen in the screenshots above. And why exactly are the signals mirrored at the center frequency? This screenshot is with RF gain off, IF 16 dB, BB 26 dB, and the ANT500. Cold start, computer and HackRF freshly plugged in after a day at work. Same room, same location, same cable as before. Enclosure and TCXO unchanged.

<img width="1295" alt="screenshot 2018-11-20 at 19 38 52" src="https://user-images.githubusercontent.com/4239297/48795901-772baf00-ecfe-11e8-9eb0-08353807fee4.png">

This is my garage remote at an arm's length from the antenna. It's FSK so the two-peaked signal makes sense to me.
<img width="1294" alt="screenshot 2018-11-20 at 19 53 02" src="https://user-images.githubusercontent.com/4239297/48795932-8f033300-ecfe-11e8-901a-05a97cfb6a99.png">

This is it a hand's width from the antenna. I don't understand those spikes left and right of it. Harmonics due to distortion/saturation?
<img width="1294" alt="screenshot 2018-11-20 at 19 53 21" src="https://user-images.githubusercontent.com/4239297/48795951-9cb8b880-ecfe-11e8-922c-5dd60e1d57a8.png">

I wasn't able to directly screenshot the pandapter with the remote 2-3 meters away from the antenna but the peaks were at about the same height as the rightmost spur, so -50ish dBFS I guess.
<img width="1295" alt="screenshot 2018-11-20 at 19 53 57" src="https://user-images.githubusercontent.com/4239297/48796075-ec977f80-ecfe-11e8-993b-c7609714bc95.png">

I'm very curious why the spurs are gone for now and why the spectrum appears mirrored

**Comment by mossmann** [comment]
Spectrum mirroring typically indicates a hardware failure of one of the two quadrature channels.  If that problem comes back, we should replace your unit.

That last screenshot looks great.  The signal strength is high enough that the power of any spurs you've observed should be irrelevant.

**Comment by lastfuture** [comment]
Thank you again for your assessment. I appreciate that a lot.

If I understood everything about quadrature samples correctly so far (thanks to your video series), if it happens again I should see it in fail in a GNU Radio Time Sink in the way that either the waveform for the I or Q channel would remain flat. Correct?

**Comment by cjheath** [comment]
The GSG designed HackRF does not have the USB shield connected directly to ground, as it should be. See pin 0 of the connector J1 here: https://github.com/mossmann/hackrf/blob/master/doc/hardware/hackrf-one-schematic.pdf
There are cables where it is correct to leave one end of the shield unconnected, but USB is not one of those. Nail that sucker down and you might solve your problems - depending on where the spurs are coming from, of course.
