### ISSUE TITLE
 Increase GPS Signal Power

### ISSUE THREAD

**Issue by kiuhnm72** [mossmann/hackrf#547]
Hi all,
I use Hackrf one to send a GPS simulated signal and I like to increase the GPS signal power. how I can increase GPS signal power without use internal power amplifier in the Hackrf one.
thanks a lot,

**Comment by mossmann** [comment]
It is extremely easy to interfere with other users of GPS when experimenting with GPS simulation, so this should only be done when taking extreme caution including the use of a shielded enclosure for your experiment and continuously monitoring the leakage from your enclosure.

If you have taken such precautions, you should try turning on/up one or both of the TX amplifier settings.
