### ISSUE TITLE
Hackrf One Capture Internet Package

### ISSUE THREAD

**Issue by haryows** [mossmann/hackrf#551]
Greeting Everybody.

I just testing to sniff 2G signal (SMS and Voice Call) and it work perfect, and now i wonder that, is that possible to hackrf One capture internet package in 3G network? sorry if its sounds like dumb question but i really interesting in this topic and i have no idea to start it. i very appreciate every single suggest from all of u guys. 

thanks before.

**Comment by mossmann** [comment]
I'm not aware of any 3G SDR applications that support HackRF, but there is some 4G stuff, notably OpenLTE.
