### ISSUE TITLE
IC possibly burned/shorted

### ISSUE THREAD

**Issue by sgoudelis** [mossmann/hackrf#553]
While playing around with the power options/pins of my hackrf I think I messed something up. 
![hackrf short](https://user-images.githubusercontent.com/4840328/48742759-ed7dd200-ec68-11e8-9416-a7f34b8be716.png)
 
When I plug in the usb cable am I feeling excessive heat coming from the highlighted part in the image above. Also the power supply amp meter is at 1A (current limit reached). Can you provide me with name of that IC in order to replace it ?

**Comment by mossmann** [comment]
That is the voltage regulator, Texas Instruments TPS62410DRCR.

**Comment by sgoudelis** [comment]
Replaced and it works, thank you
