### ISSUE TITLE
Enhancement: sweep transmit,freqs below 1MHZ and more..

### ISSUE THREAD

**Issue by luoGanda** [mossmann/hackrf#574]
Hi !

This is not a bug, but i already sended this to g.s.g. email and i was redirected here.
By the way, how to mark this as an enhancement?

**A few questions..**

Can hackrf one's 'hackrf_init_sweep' be used with transmit?
this is probably no, or not yet..
If not, could it be implemented somehow, especially withouth any hardware change?
it could be quite useful, for example to create something like a multiband jammer tester or something similar..
I already wrote a test program for this, but it's a slow simulation compared to what sweep thing could do.
By the way, hackrfSpectrumAnalyzer is a good tool, regards to "the cooker".

Also, how can one monitor lower frequencies from 1hz to let's say 500khz?
I already tried noelec upConverter 1.3 barebones, but it is as it is, and as some docs says, it works from 500khz up. Maybe some more info about this, because on two sites, i got two different infos about it's range workings.

Also, the same question for higher freqs - above 7.2mhz, for lets say Ku radar band and higher.
This is teoretically possible - but someone could enlighten me with some info about this.

Also, could subHertz range be measured with this(eg 100.5555hz), theoretically i know this is possible, but someone could enlighten me about this too.

**Comment by thepillbug** [comment]
-------- Original Message --------

**Comment by mossmann** [comment]
TX sweep is a good suggestion.  It would be useful in conjunction with a spectrum analyzer (or second HackRF) for testing the frequency response of a filter or for measuring the HackRF's output power over a wide frequency range.

For some information about performance below 1 MHz, see:
https://greatscottgadgets.com/2015/05-15-hackrf-one-1MHz/

Using upconverters/dowconverters is probably the right approach for signals outside the operating frequency range of HackRF One.

**Comment by luoGanda** [comment]
what is the software used on that webPage to measure performance? it could come handy..

Other original question(s) remains, if someone has some cunning idea..
"Also, how can one monitor lower frequencies from 1hz to let's say 500khz?",
and also, how to measure below that, lets say 100hz.

This is possible - without using any up/down converter - i think some kind of math trick is used, something like 4xProcessing or so. For not too wide ranges it should work perfectly with same hardware, although for something more, probably hardware(up/down converter) should be used. But, as i said - docs from suggested upConverter are unclear what someone is looking at - which freq does it "hightenUp", when he/she tunes to 125MHZ that noelec v1.3 uses? somewhere it's written 500khz, somewhere something else.

Well, upConverter that could go all the way down to 1HZ(or downConverter) above 10GHZ would be briliant. Transverter would be even better, but usually they have smaller range.

Again, someone could enlighten me about this questions..

**Comment by luoGanda** [comment]
ok, i wrote a simple jammer some time ago - which is also a transmit sweep simulator,
if anyone want's to play with it - here it is as hrfJam(linuxVer)..
Meanwhile while i was playing with this, i figured out that we, as humans, are pretty good conductors..
[hrfJam.zip](https://github.com/mossmann/hackrf/files/2935455/hrfJam.zip)

A few samples:
./hrfJam freq=2400m:2480m
./hrfJam freq=2440m freq=2450m freq=2480m stepnumsamples=600k numrepeats=60
./hrfJam h or ./hrfJam -h or ./hrfJam /h <<=help, any opt can be without - or -- or /

**Comment by miek** [comment]
I'm gonna close this now as we've got #364 to track sweep transmit, and I think the other questions were answered.

**Comment by All3xJ** [comment]
> ok, i wrote a simple jammer some time ago - which is also a transmit sweep simulator,
> if anyone want's to play with it - here it is as hrfJam(linuxVer)..
> Meanwhile while i was playing with this, i figured out that we, as humans, are pretty good conductors..
> [hrfJam.zip](https://github.com/mossmann/hackrf/files/2935455/hrfJam.zip)
> 
> A few samples:
> ./hrfJam freq=2400m:2480m
> ./hrfJam freq=2440m freq=2450m freq=2480m stepnumsamples=600k numrepeats=60
> ./hrfJam h or ./hrfJam -h or ./hrfJam /h <<=help, any opt can be without - or -- or /

I don't want to necropost. But could you post the source of this program so I can learn how does it work?
