### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by ZeroChaos-** [mossmann/hackrf#582]
it's been a year, please tag a release :-)

**Comment by phantomdennis** [comment]
Any chance there will be a new release for the firmware? It has been a while since 2018.01.01. I'm sure you have some improvements in the last 2.5 years...right?

**Comment by straithe** [comment]
Done! https://github.com/mossmann/hackrf/releases/tag/v2021.03.1

**Comment by ZeroChaos-** [comment]
@straithe <3
