### ISSUE TITLE
Operation below 1MHz

### ISSUE THREAD

**Issue by DavidVanHorn** [mossmann/hackrf#583]
Is there any functionality on the HackRF one at 475 kHz?
Is there a modification I can make that will enable this?
I’m an EE, and totally comfortable with fine pitch rework.
 
I know I can mix my signals up, but that involves noise, and my whole purpose in working with the HackRF one is to investigate what can be done in DSP to dig our signals out of the noise.  I"ve seen a lot of premade front end software, but I want to really dig in and see what can be done if I am willing to sacrifice almost everything else to pull CW signals out of the noise.

I have a "Ham it up" converter coming as a backup plan. 
I also have an RSP2Pro which does cover this range, but I have not found a way to get it working in GnuRadio through the Osmocomm source, in Windows.  Most other SW I use requires windows, so I'm not really interested in solutions that start with "install linux".

Thanks.

**Comment by mossmann** [comment]
HackRF One is functional but very lossy at 475 kHz.  There is a plot of maximum TX power here: https://greatscottgadgets.com/2015/05-15-hackrf-one-1MHz/

Ham It Up is a good option.  The best option in theory is to construct an amplifier circuit to interface with the ADC/DAC signals directly via the analog baseband header, bypassing the RF section.
