### ISSUE TITLE
Shielding improvements

### ISSUE THREAD

**Issue by DavidVanHorn** [mossmann/hackrf#588]
I wish now, that I had recorded where I was starting from, and I'm reluctant to un-do all the work just to make those measurements, but I assume everyone is seeing what I saw with my plastic case HackRF, lots of spurs and "birdies" across the tuning range.  Not surprising, but my main interest is weak signal work, so I set off on a mission to quiet it down.

I ordered the internal shield kit and metal case from Nooelec.

The metal case is well made, but disappointing from a shielding perspective, as the surfaces which should touch are all painted, which makes those joints act as slot antennas. :(   A bit of work with a dremel removed that issue.

The internal shield kit worked well enough, though the soldering is a bit tricky and some of that has to be done from inside the can rather than outside.

Now here's the third thing I did, which seems to have cleaned up a lot is to apply flexible ferrite absorbing material pretty much everywhere.    The inside surfaces of the metal case and internal shields are basically reflectors.  Think of light in a box made of mirrors.  It's going to bounce around till it gets absorbed somewhere.   The FFAM sheets are like flat black paint.    I cut large sheets and lined the inside of both case halves, I put two thicknesses inside the internal shield, and then I cut up what I had on hand and basically plastered every available surface on the PCB.  Probably overkill, but I never liked half-measures. 

I still see lots going on below 10 MHz, but once i get above 10MHz, the spurs are largely gone.  Using the RF Analyzer 1.13 app on my phone shows a much cleaner spectrum than I had with plastic, internal shield, or the metal case 

If someone offered a pre-cut set of FFAM absorbers, I would have bought that. 

https://www.tokin.com/english/product/pdf_dl/flex.pdf  <--  What I used, their 3mm EFX6 material
https://www.fair-rite.com/flexible-ferrite/
https://pm.lairdtech.com/emc-components/ferrite-sheets
http://kgs-ind.com/products/emc/emi-absorbers/

**Comment by mossmann** [comment]
This is a nice tip, so I've created a new "tip" label to make it easier to find in the future.
