### ISSUE TITLE
Some information needed regarding transmission and reception

### ISSUE THREAD

**Issue by arun121cs** [mossmann/hackrf#591]
Hi,
I wanted to know that is it possible to transmit a signal at say 88MHz using hack RF one, and then switching the receive mode (using GNU radio) and receive that signal which comes after reflection? 
 there is any way to do it if this doesnt work ? I only have one hack rf one and i want to test the reflected signal. Thanks in advance.

**Comment by arun121cs** [comment]
I am thinking to use a selector block which can select the values by passing a binary signal. Can it be done? kindly guide me through it. @mossmann

**Comment by GravesJake** [comment]
It takes too long to switch between TX/RX to realistically be able to achieve this.
