### ISSUE TITLE
Receive gain

### ISSUE THREAD

**Issue by Cajuisland** [mossmann/hackrf#595]
Hi, I was left with a doubt. Is it possible to connect HackRF to a bidirectional amplifier with 20 dBm receive gain?

I read the article at https://github.com/mossmann/hackrf/wiki/HackRF-One.

Michael says that:

"The maximum RX power of HackRF One is -5 dBm. Exceeding -5 dBm can result in permanent damage!

In theory, HackRF One can safely accept up to 10 dBm with the front-end RX amplifier disabled. However, a simple software or user error could enable the amplifier, resulting in permanent damage. It is better to use an external attenuator than to risk damage. "

So, I can not connect my HackRF to a two-way RF Amplifier that has above "5 dBm" of RX gain, because it can damage it.

I intended to do an experiment with another friend close to 2.4 GHz and to increase the tx signal,  would use common amplifiers WiFi (2.4 GHz - 39 dBm). We got frustraded!

**Comment by miek** [comment]
It's important to understand the difference between dB and dBm. I recommend watching https://greatscottgadgets.com/sdr/3/ for a really good explanation.

An RF amplifier will have a gain specified in dB (not dBm) and this means that the power out will equal the power in plus the gain. For example, -15dBm power in to an amplifier with 20dB gain would give 5dBm power out.

So, you must have a way to measure the power going in to the amplifier to know whether it is safe to connect it to the HackRF. If in doubt, I don't recommend risking it.

It's also important to note that a lot of amplifiers will work outside the frequency of interest, so may amplify a signal that you weren't expecting (like a nearby mobile phone, or a broadcast FM radio transmitter down the road).
