### ISSUE TITLE
Application in Radar

### ISSUE THREAD

**Issue by Kartikk99** [mossmann/hackrf#597]
I know that HackRF One has half duplex type of communication. So I wanted to know if I could use a single HackRF One module to build a radar.

**Comment by GravesJake** [comment]
It takes too long to switch between TX/RX to be able to capture any transmitted signals without being extremely far away.

**Comment by Kartikk99** [comment]
Thank you.
Can you suggest any other open source SDR which can be used as a radar?

**Comment by GravesJake** [comment]
Sorry for the late response, I didn't realize you replied. I don't think there is currently a device capable of this, but I may be wrong.
