### ISSUE TITLE
Baseband lowpass filter option ("Bandwidth") in osmocom source seems to have no effect

### ISSUE THREAD

**Issue by johschmitz** [mossmann/hackrf#603]
### Steps to reproduce
1. In Osmocom Source I am setting the Ch0: Bandwidth(Hz) to 2e6 (sampling rate 8e6).
2. When observing the spectrum with QT GUI Frequency sink nothing seems to have changed.

### Expected behaviour
I am expecting that the "Bandwidth" option sets the baseband filter in the hardware.
Frequencies above/below +/-1MHz should be attenuated.

### Actual behaviour
Filter seems to have no effect.

### Version information
**Operating system**: Linux Mint 19

**hackrf_info output:**
hackrf_info version: unknown
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000a74461c838856a9f
Board ID Number: 2 (HackRF One)
Firmware Version: git-9bbbbbf (API:1.02)
Part ID Number: 0xa000cb3c 0x005d476e

**third party software**

GNU Radio Companion 3.7.11

**Comment by GravesJake** [comment]
Would you mind uploading screenshots of your frequency display with the filter on/off?

**Comment by miek** [comment]
The difference won't be noticeable unless you increase the IF/BB gains, here's an example from `osmocom_fft`:

![hackrf-lowbw](https://user-images.githubusercontent.com/578095/69640969-3a07a480-1057-11ea-8acf-18ccb4214e4e.png)
![hackrf-highbw](https://user-images.githubusercontent.com/578095/69640972-3c69fe80-1057-11ea-8abc-b643dc3fba76.png)
