### ISSUE TITLE
Issue with USB mode

### ISSUE THREAD

**Issue by sgoudelis** [mossmann/hackrf#606]
### Steps to reproduce
The issue only reproduces on 1 of my original hackrfs. I have two. The other one runs fine.

### Expected behaviour
Should go into USB mode when plugged in

### Actual behaviour
Most of the time the hackrf devide does not go into USB mode

### Version information
Windows 10, LInux, multiple boxes, multiple cables tested.

```

**Comment by GravesJake** [comment]
Does it work in the default non-DFU mode?

**Comment by miek** [comment]
I'm going to close this as there's not been a response in a while, but please feel free to re-open or open a new issue if you're still having trouble.
