### ISSUE TITLE
Antenna analyzer with Relative function

### ISSUE THREAD

**Issue by Patnetpatnet** [mossmann/hackrf#610]
Is anyone familiar with spectrum analyzer software that allows antenna return power calculations for VSWR. One needs to be able to zero out the power from the noise source so db level is flat. You can then add antennas to see reflected power and make SWR calculations. Pavels' Spektrum does this for RTL. Is there something similar for Hack RF One? Thanks.

**Comment by GravesJake** [comment]
Sorry for the late response, I think a better place to ask something like this would be the hackrf irc channel or the mailing list.

**Comment by miek** [comment]
qspectrumanalyzer does have this feature, but it's not super clear from the docs - here are some notes on how to use it: https://github.com/xmikos/qspectrumanalyzer/issues/70#issuecomment-557845699
