### ISSUE TITLE
Does 2Msps sampling rate affects Tx?

### ISSUE THREAD

**Issue by hopkinskong** [mossmann/hackrf#611]
I understand there is a 8Msps (or 2Msps) minimum sampling rate requirements for the ADC (and baseband). Is it only applies to Rx only? How about Tx?

**Comment by jboone** [comment]
@hopkinskong I don't see in the MAX5864 datasheet a minimum for the DAC. However, you will be limited by the width of the transmit baseband filter in the MAX2837. So at 2Msps, you will have alias images at multiples of the sampling frequency that aren't very well filtered. Additional filtering may be required, depending on your application.

**Comment by hopkinskong** [comment]
Thanks for the info! As for the image frequencies, i suppose there is no way to do the filtering on software (i.e. GNURadio), right?

**Comment by jboone** [comment]
@hopkinskong That's correct. At the point where these images are produced, you're no longer in the digital domain. So the solution would need to be analog in nature.

**Comment by hopkinskong** [comment]
@hopkinskong Thanks! Where do this image frequency produced? Is it in the baseband IC? I have read that the IF frequency will also generate spurs in the image frequencies too.

**Comment by jboone** [comment]
@hopkinskong It's produced from the act of converting digital samples into an analog voltage or power, and is due to sampling theory diverging from the actual behavior of electronics in the physical world. This takes place in the DAC portion of the MAX5864.

**Comment by hopkinskong** [comment]
@jboone I see. Thanks again for the rapid response. So not only there are surplus image frequencies produced by the DAC in MAX5864, there are also the same thing happen in MAX2837 IF.

Closing the issue as it is now resolved.
