### ISSUE TITLE
hackrf to microchip or arduino

### ISSUE THREAD

**Issue by pachoduran** [mossmann/hackrf#613]
Hi, i need sintonize one frecuence in hackrf only. is posible make this of arduino or un DSPIC??

Thanks

**Comment by GravesJake** [comment]
Sorry I'm not sure I understand the question, could you elaborate?

**Comment by Radiomix2000** [comment]
He means he wants to synthesize one frequency in hackrf

**Comment by miek** [comment]
It's still not very clear exactly what you want to do. I'm going to close this for now as there hasn't been a response in a while, but please re-open or open a new issue if you are still working on this & can explain in a bit more detail.
