### ISSUE TITLE
How hackrf_sweep normalizes FFT output

### ISSUE THREAD

**Issue by giomar207** [mossmann/hackrf#615]
Hi, 
I was using hackrf_sweep for collecting some data from 400-500MHz and I was using a walkie talkie at 420MHz as source. What I realized it is that the output is normalized by shifting the spectrum around -40dB so that the peak is close to 20/25dB.  I was wondering if there is any possibility to shift the spectrum (i.e. the bottom part) from -40dB to 0dB, so the dynamich is between 0 and 70dB? The output is in the following picture: I'd like to have a spectrum centered around zero dB.
![figure_1](https://user-images.githubusercontent.com/30689199/57285882-745a2600-70b4-11e9-9c9f-7f3f356c64a9.png)

**Comment by GravesJake** [comment]
Sorry for the late response, I think I'd need to know more about your setup before continuing. The IRC and mailing list would also be a good place to ask.
