### ISSUE TITLE
HackRF communicate with MCU board

### ISSUE THREAD

**Issue by bunphotk** [mossmann/hackrf#616]
I am new in HackRF One. 
 
Can HackRF communicate with microcontroller board/mini PC? If yes, which board/HW is recommended for starter? 
 
I want to use HackRF with my TDOA project so I want also to hook GPS data into it. Are there any port on HackRF I can feed GPS timestamp?

Thanks

**Comment by GravesJake** [comment]
There are various microcontroller boards that have RF TX/RX capabilities, but I'm a little confused about what you're looking for exactly. Could you elaborate?

**Comment by bunphotk** [comment]
@GravesJake. I understand that HackRF can only send IQ data to computer via USB port (I might be wrong). What about use HackRF with a microcontroller board instead of PC? What is the best way to start with? Thanks.

**Comment by GravesJake** [comment]
That's correct that the HackRF communicates with the host PC via USB. I'm not familiar with using other microcontroller boards with RF capabilities, a good place to ask about this would be the HackRF IRC channel or mailing list. Is it the USB communication itself that you're trying to circumvent?

**Comment by virendera** [comment]
I think there is a microcontroller fabricated on  hackrf PCB also.

**Comment by miek** [comment]
It's certainly possible to get the HackRF to communicate with another microcontroller, but it does not support it out of the box. It also doesn't support any sort of GPS timestamping currently, you would need to modify the firmware to implement that.
