### ISSUE TITLE
Error message when trying to send signals with HackRF One on GRC

### ISSUE THREAD

**Issue by Dyla2n** [mossmann/hackrf#618]
Hello,

I am using a HackRF One to transmit signals to an USRP NI 2921 which receives the signal. Whatever the signal I am sending (sine, cosine, triangle,...) and whatever the frequency of the signal sent, I always obtain the same peak located at the same frequency (around the frequency carrier shifted of 50 kHz) in the FFT received on the NI 2921. 
I am using GNURadio Companion as the software processing the signals. Here is the message I obtain in the console of the transmitting signal on GRC : 

`Warning: failed to XInitThreads() linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.11 built-in sink types: uhd hackrf bladerf soapy redpitaya freesrp file Cannot connect to server socket err = No such file or directory Cannot connect to server request channel jack server is not running or cannot be started JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock Using HackRF One with firmware 2018.01.1`

Can somebody enlighten me?

**Comment by GravesJake** [comment]
I'm not familiar with this specific issue, have you tried asking in the GRC mailing list?
