### ISSUE TITLE
HELP WITH A PROBLEM 

### ISSUE THREAD

**Issue by marumarce** [mossmann/hackrf#619]
Hi all!! I am starting in the world of radio frequency as an amateur and I am working on a project. I tell you my problem and I am 100% sure that you can help me solve it, I am from Argentina. I have the hackrf One device, I am doing tests to listen, copy and reproduce the alarm frequency of my cars. I'm doing it through androi (4.4.4) (my tablet Samngung SM_T560, capacity of the battery 5000 MAH), with the applications "rf analyzer" and "hackrf_test version 1.12". I leave a link to the procedure I am using. I'm interested in what you think about it (if the procedure is the right one), I'll try it on my 5 cars. And it only allows me to do it once in each one, when I want to carry out the process again (from scratch) it does not do it again. I already try deleting the data of the applications and even the cache and even then it does not work. I await your comments!!

**Comment by miek** [comment]
If I understand correctly, you were trying to perform replay attacks on your cars but the recorded signal only worked once? This is normal! Any modern car will use rolling codes to protect against replay attacks, see here for more info: https://en.wikipedia.org/wiki/Rolling_code
