### ISSUE TITLE
hackrf_sweep piping via awk then sort prints nothing

### ISSUE THREAD

**Issue by luoGanda** [mossmann/hackrf#627]
This may be, or not be an issue of hackrf_sweep, but here it is.
Os is mx-linux.
Maybe this has to do with buffering or something.

This are commands being piped through a custom script hrfReport which has something like:
hackrf_sweep -f 1:300 2>/dev/null | awk -F "," "$awkScript"
Now, this are piping results
./hrfReport 1 300  <=ok, as expected
./hrfReport 1 300 | cat <=ok, repeatedly reporting to stdout
./hrfReport 1 300 | sort <=no output, something blocks
./hrfReport 1 300 | head -n4|sort <=ok, but prints just first 4 and then pipe is closed

I guess 'head' closes file descriptor or something and then 'sort' can read from std.

Also, here is simpler(but full, testing version), with exactly the same simptoms:
hackrf_sweep -f1:300 2>/dev/null | awk 'BEGIN{t=0}{if(t==0)t=substr($2,0,8); if(t==substr($2,0,8))arr[n++]=$7; else{for(a in arr)print arr[a];t=n=0;delete arr}}'
This does ok - it prints out results every second, but:
* using the same as basic example - appending pipe eg | cat <= works ok
* using the same as basic example - appending pipe eg | sort <=does not work, something blocks
* using the same as basic example - saving it in file first with > sort.txt and then using sort sort.txt works ok

Also, if using basic example and adding -F "," to awk, also something blocks, although this is what i want, printing just number without , at end.

Can someone enlighten me with this?
Also using stdbuf -oL before commands doesn't help.
And in larger awk script(not written here) there is fflush(); after circa 8 prints.

I checked source a little bit,
maybe adding an option to flush output buffer after each sweep or not tweaking std io buffering at all, or something like this would probably solve this.

**Comment by GravesJake** [comment]
I'm not super familiar with these file operations, but I'm guessing you're right in that there is some weirdness between the sweep output and what you're trying to do with it. Feel free to poke around at the code and see what you find.

**Comment by miek** [comment]
The problem is that `sort` needs a finite input. Since `hackrf_sweep` never finishes, `sort` can't output anything - how would it know whether the next line should've been printed before the current output? To do something like this, you'd have to decide on a point where `hackrf_sweep` can end, then the sort can run.

**Comment by luoGanda** [comment]
i thought that a finite input is an end of line - i think this is how it should work. Not sure - but i think this is how it works with for example rtlsdr.
I also tried with with fflush like mentioned before - but no luck.

**Comment by miek** [comment]
`sort` only sorts whole lines in a file, so it needs to see the end of the file before it can sort

**Comment by luoGanda** [comment]
yes - i though it's something like this.
With awk tool, it's meant to use sort every 1sec, so some workaround with EOF thing would probably work. I think that this works with rtlsdr directly.
