### ISSUE TITLE
Is the HackRF firmware still being updated?

### ISSUE THREAD

**Issue by bluegizmo83** [mossmann/hackrf#628]
Github shows the last code commit was 4 months ago, and the last release was over a year and a half ago...

**Comment by GravesJake** [comment]
Yes HackRF is still an active project. Development efforts have been shifted elsewhere (GreatFET) lately, but HackRF dev/support is active.

**Comment by bg8wj** [comment]
https://github.com/marcinwrobel1986 is new portapack  3nd part firware update. for hackrf one and portapack you can found the new tools & bootload  firware for hackrf one.
