### ISSUE TITLE
Questions about GNU Radio Blocks Implementations 

### ISSUE THREAD

**Issue by rzn-290** [mossmann/hackrf#630]
Hi,
I am making a 802.11p Receiver using hackrf. I am trying to implement the receiver diagram provided at the end of this question. 

I can not find some tools such as OFDM Sync Short and such in my GNU Radio. Is it possible to implement it on hackrf? If not, can you please suggest what can I use instead? 

<img width="546" alt="Capture" src="https://user-images.githubusercontent.com/43007687/62095687-284ff500-b24f-11e9-9a53-20056bb68f2c.PNG">

**Comment by miek** [comment]
It looks like that flowgraph comes from a fairly old paper. GNURadio has changed a lot since then, so I don't know if those blocks are still available. I recommend having a look at https://github.com/bastibl/gr-ieee802-11 which should do what you want & is well maintained.
