### ISSUE TITLE
error no file system?

### ISSUE THREAD

**Issue by TeleportingKitten** [mossmann/hackrf#631]
I'm getting an error when I click the little red R icon when using the Capture, it's saying error at the top left and telling me I have no File system? I click OK and it brings me back to the Hack RF one capturing screen. It's definitely capturing because I see the spectrum, but am I missing files? I have a 64gb SD card inserted.

**Comment by blardyblar** [comment]
Uh, what platform are you using it on? With what software? There isn't nearly enough information in your post to even begin to know what you're talking about... "little red R icon"?? "64gb sdcard"?? This means nothing without context!

**Comment by miek** [comment]
This sounds like a Portapack issue. You probably just need to format the SD card with a FAT filesystem. For further info you should check out the Portapack repo/wiki: https://github.com/sharebrained/portapack-hackrf

**Comment by Arefgh13** [comment]
> I'm getting an error when I click the little red R icon when using the Capture, it's saying error at the top left and telling me I have no File system? I click OK and it brings me back to the Hack RF one capturing screen. It's definitely capturing because I see the spectrum, but am I missing files? I have a 64gb SD card inserted.

How do you solve it, I have same problem

**Comment by Arefgh13** [comment]
Please help I have no file system problem

**Comment by miek** [comment]
See my reply above, you need to format the SD card correctly: https://github.com/sharebrained/portapack-hackrf/wiki/General-Use#microsd-card-socket
