### ISSUE TITLE
Tx preamplifier for hackrf on 2m band

### ISSUE THREAD

**Issue by virendera** [mossmann/hackrf#636]
Anybody using external tx amplifier with hackrf for long distance communication over 2m band. If yes then how to do this with hackrf one.

**Comment by miek** [comment]
I've not seen any examples of anyone doing it, but roughly what you would need is: filtering on the HackRF output to remove harmonics and other spurs, amplification, and low-pass filtering on the output of the amplifier to remove any further harmonics.
