### ISSUE TITLE
HackRF as a Down Converter?

### ISSUE THREAD

**Issue by OKCarl** [mossmann/hackrf#639]
Uniden has a superior scanner ( new model) for sale, the Uniden SDS 200. Perfect in every way except for a lack luster frequency range. Is there some way the Hack RF might be paired with the Uniden in the role of a down converter?

**Comment by miek** [comment]
I don't think it would be possible without some significant hardware mods. The HackRF does make the baseband signal available on headers, but I don't see any way to feed that in to your scanner.
