### ISSUE TITLE
Possible Tuning Issue?

### ISSUE THREAD

**Issue by fhhowdy** [mossmann/hackrf#644]
### Steps to reproduce
1. HackRF with included antenna
2. gqrx, tune to frequencies below FM radio band

### Expected behaviour
I was expecting to see no FM radio signals.

### Actual behaviour
I'm seeing very strong WFM signals down to 77.9MHz.  At 80.9MHz, I'm getting 96.9 FM.  Is there some type of calibration process I need to follow?  It's strange that the frequencies are dead-on centered with what I'd expect from an actual fm radio (no weird offset)...but the frequencies extend well below normal broadcast range.

### Version information
**Operating system**: 
Mac OSX 10.15
HackRF One (just purchased from GS)
gqrx 2.5 software

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.
gqrx 2.5 software
<img width="1343" alt="Screen Shot 2019-09-24 at 9 10 40 PM" src="https://user-images.githubusercontent.com/6207228/65563914-c939f400-df10-11e9-9f99-4bd34830c33d.png">

### Output
```
Insert any commandline or build output here
```

**Comment by fhhowdy** [comment]
Actually, it goes to 73.9MHz  (89.9FM) ...  I haven't found any FM signals below this.  Both of these are 16MHz off from their true signal.  I can't imagine this is coincidental.  I'm thinking I have something configured incorrectly, but where, I don't know.  It works great, outside of the frequency deviation.
<img width="1343" alt="Screen Shot 2019-09-24 at 9 20 07 PM" src="https://user-images.githubusercontent.com/6207228/65564078-672dbe80-df11-11e9-94d3-ed9bfc59ab93.png">

**Comment by miek** [comment]
I've seen some issues like this with older firmware, or mismatched firmware/CPLD versions. Could you make sure you've got the latest CPLD and firmware images flashed? https://github.com/mossmann/hackrf/wiki/Updating-Firmware
