### ISSUE TITLE
doubt about operating rate

### ISSUE THREAD

**Issue by manotroll** [mossmann/hackrf#646]
in some places it says it starts at 10 mhz and others at 1 mhz what is the right start frequency?

**Comment by miek** [comment]
Early specifications set the lower limit at 10MHz, but as production units actually performed very well under 10MHz the specification was later lowered to 1MHz. There's a blog post with a bit more detail here: https://greatscottgadgets.com/2015/05-15-hackrf-one-at-1-mhz/, and the current full specification can be found here: https://github.com/mossmann/hackrf/wiki/HackRF-One
