### ISSUE TITLE
Requirement of HackRF Protocol / Interface Specifications Document

### ISSUE THREAD

**Issue by anisjamil345** [mossmann/hackrf#647]
Hi , 

      Currently I am working on an educational project in which I need to emulate HackRF for Simon's "SDR Console" through LabVIEW.  For this purpose, I need HackRF Protocol / Interface Specifications Document. (Although I am having HackRF which is working with "SDR Console" fine independently, but for emulation purpose I need to implement its protocol.)
         Can anyone help me in providing / finding HackRF communication Protocol / interface Specifications Document please?

Best Regards
   Anis Jamil

**Comment by miek** [comment]
There isn't any protocol specification document for the USB interface. Instead, we provide libhackrf as a stable interface for people to use. If you still want to do emulation at the USB level you could look at the source code for libhackrf and hackrf_usb for further details.

You may also be able to compile your own copy of libhackrf that just does simulation, and have SDR Console load that instead.
