### ISSUE TITLE
GNURadio won't recognize HackRF without hackrf=*serial* 

### ISSUE THREAD

**Issue by bluegizmo83** [mossmann/hackrf#654]
I'm having a weird issue with one of my systems... I just got a new Windows laptop and installed GNURadio and setup the HackRF on it. 

The HackRF works fine on this new system under SDR# and various other programs, but in GNURadio (using osmocom blocks) it will not recognize the HackRF unless I put hackrf=*device serial number* into the Device Arguments field of the blocks. I've also tried adding hackrf=0 but that didn't work. I'm only using one HackRF, not multiple or anything like that. 

I have two other systems (three if you count dual booting linux on one of them) and the HackRF works perfectly with GNURadio on all of them without needing special Device Arguments.

What could cause an issue like this? I've been getting around it for now by just adding the hackrf=*device serial number* to every osmocom block I use, but its a little tedious to do every single time I add an osmocom block.

**Comment by GravesJake** [comment]
Not super helpful, but being that it seems to be a gnuradio issue, you might be able to get a quicker/better answer there.
