### ISSUE TITLE
HackRF Radio FM Signals

### ISSUE THREAD

**Issue by GiacomoNasi** [mossmann/hackrf#655]
Hi everyone, I'd like to know if is there any way to get the FM audio from a specific frequency coming from an HackRF device.
I'd have to use this feature in my software, so I need a command line tool to call or a Java library.

Thanks for your help :)

**Comment by GravesJake** [comment]
I'm not exactly sure what you're after, are you trying to listen to the FM audio or do something else with it, ie. save it to file?

**Comment by GiacomoNasi** [comment]
No, I have to reproduce the audio in real time. If there's no way to do it, also saving the audio file and listening to it in a second moment could be ok :)

**Comment by febs** [comment]
Did you watch the videos from Ossmann? The first one does exactly that in gnu radio.

**Comment by miek** [comment]
As @febs says, have a look at the Software Defined Radio with HackRF video series here: https://greatscottgadgets.com/sdr/ - lesson 1 has a demo of receiving broadcast FM radio.
