### ISSUE TITLE
hackrf with simulink(cmake problem).

### ISSUE THREAD

**Issue by arielkantorovich** [mossmann/hackrf#656]
HI, 
I try to start work hackrf with Simulink, 
I was assisted in the video on youtube :https://www.youtube.com/watch?v=lJz4ZqB_oCw&t=552s
and I stuck I didn't find the directory libhackrf/build and because this I cant run cmake.
I really need any help even a link to the file or a particular guide because I seem to be doing something wrong .
Thank you very much:)

**Comment by miek** [comment]
The `build` directory doesn't need to exist, it's just the destination for the compiled files. If you get errors requiring it, you can just create it.
