### ISSUE TITLE
Question about modulation schemes for SDR design.

### ISSUE THREAD

**Issue by louemon** [mossmann/hackrf#658]
I would like to ask a question about modulation schemes. I am working on a low-cost SDR design to work with OpenBTS. The modulation scheme used for SMS is GMSK and voice modulation is QPSK (if I am wrong please correct me). My question is, would it be best to use an RFIC that supports GMSK and QPSK or can I instead use an RFIC similar to a CC1111 such as the CC1101 which does not support GMSK or QPSK? 

My second question is must I use an FPGA?

Thankyou all for your time.

**Comment by miek** [comment]
This is quite a complex task and not something I can really cover in a github issue :)

I recommend watching this talk by Harald Welte that talks about the complexities involved in making hardware for cellular basestation software (like OpenBTS): https://www.youtube.com/watch?v=JgRCvzTuGkE

It's worth clarifying that SDR hardware generally just works with baseband samples and doesn't "support" any particular modulations directly - it's up to you to do the modulation in software. RFICs like the CC1111 and the CC1101 are not SDR.

As for whether you need to use an FPGA, that's up to you as the hardware designer!
