### ISSUE TITLE
How to read the firmware documents???help me

### ISSUE THREAD

**Issue by FamerWaitingforRain** [mossmann/hackrf#665]
### research the code of hackrf one's MCU(LPC4320)
I downloaded  all the files of hackrf one project. And i want to konw how the mcu control these chip work.So i read the firmware document,but there are so many files,and exist several main function.I donot konw where is the first of these codes.
let's discuss.
![image](https://user-images.githubusercontent.com/49672670/69531125-497ee300-0fae-11ea-99d7-7f083c4c74c4.png)

**Comment by miek** [comment]
The main entry point for the standard HackRF One firmware is in `hackrf_usb/hackrf_usb.c`. Other `main` functions are for test/demo applications.

**Comment by FamerWaitingforRain** [comment]
thanks so much

> The main entry point for the standard HackRF One firmware is in `hackrf_usb/hackrf_usb.c`. Other `main` functions are for test/demo applications.

thanks so much
