### ISSUE TITLE
Can I reprogram with an open source programming language?

### ISSUE THREAD

**Issue by khanz1** [mossmann/hackrf#667]
I would like to reprogram Hackrf one with python to make a new UI or many button interface just like any other software but it still like using diagram block with GNU, can't I?

**Comment by miek** [comment]
The easiest way to use HackRF from Python would be via GNURadio and gr-osmosdr. There's a tutorial on writing GNURadio flowgraphs in Python here: https://wiki.gnuradio.org/index.php/Guided_Tutorial_GNU_Radio_in_Python
