### ISSUE TITLE
Unwanted transmission outside of the defined 5GHz channel 

### ISSUE THREAD

**Issue by BigBobsky** [mossmann/hackrf#675]
### Steps to reproduce
1. plug a spectrum analyzer on the HackRF antenna connector
2. play/replay a transmission on the 5GHz center frequency (originaly the bandwidth was 40MHz) :   hackrf_transfer -t jlt.bin -f 5000000000 -x 30
3. with the spectrum analyzer, observe signal on the 5GHz center freq but also an even greater signal around the 4.7 GHz frequency.
4. This behavior can be reproduced with other frequencies around 5GHz.

### Expected behaviour
Only the 5GHz centered signal should be present.

### Actual behaviour
Signal is present on the 5GHz center freq but also an even greater signal around the 4.7 GHz frequency.

### Version information
**Operating system**:
Ubuntu 18.04

**hackrf_info output:**
hackrf_info version: git-e9c6c2d
libhackrf version: git-e9c6c2d (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000a06063c822705b5f
Board ID Number: 2 (HackRF One)
Firmware Version: 2018.01.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x005c4774

**Comment by miek** [comment]
This sort of thing is expected. The HackRF One (like most wideband SDR devices) doesn't have any output filtering, so you will see some spurious signals. This is not generally an issue for low power experiments but if it is a problem in your case (or you want to amplify your TX signal) then you should use a band-pass filter for your frequency of interest.
