### ISSUE TITLE
 how i get output file hackrf_sweep

### ISSUE THREAD

**Issue by adjmxx** [mossmann/hackrf#678]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by adjmxx** [comment]
hackrf_sweep -f 20:100 > out.txt

**Comment by adjmxx** [comment]
hackrf_sweep -f 20:100 > out.txt

**Comment by miek** [comment]
I don't understand what you're asking, could you expand a bit?
