### ISSUE TITLE
Not receiving MacBook Pro

### ISSUE THREAD

**Issue by mattmac553** [mossmann/hackrf#680]
### Steps to reproduce
1. Plug HackRF into usb a to C
2. Open gqrx 

<img width="1062" alt="Screen Shot 2019-12-18 at 7 21 31 PM" src="https://user-images.githubusercontent.com/4474969/71317929-2b928a00-2457-11ea-868b-27b0ccef7b24.png">

### Expected behavior
Show normal somewhat flat line

### Actual behaviour
Get a weird hump in the display

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```
Only happens on MacBook Pro not my older windows computer

**Comment by mattmac553** [comment]
There should be pleanty Of p25 control channels and voice channels being displayed

**Comment by miek** [comment]
The "weird hump" that you see is probably just from the anti-aliasing filter - it's usually set to a value just under the sample rate but can be made narrower for better attenuation of out-of-band signals. You can adjust the width of it with the "bandwidth" setting in GQRX.
