### ISSUE TITLE
need bin file for U20 W25Q80BV

### ISSUE THREAD

**Issue by eeprommemory** [mossmann/hackrf#686]
need bin file for U20 W25Q80BV
usb no longer works dfu mode does not work want to reprogram spi chip need file thanks.

**Comment by miek** [comment]
You can find that in the release package under `firmware-bin` as `hackrf_one_usb.bin` https://github.com/mossmann/hackrf/releases/tag/v2018.01.1

**Comment by miek** [comment]
Also, could you give a bit more detail about why you think a PortaPack firmware bug is causing USB issues (as you mentioned on #684 and #681)?

**Comment by eeprommemory** [comment]
i did not see a burnable file in the release package.
chip size is 1mb only file i saw was 22kb.
and i think the software loads it into certain locations so it is not a full image.
it was working fine then it crashed so i reset it and all seems good then i need to use it as a SDR and nothing.
two computers several usb cords nothing.

**Comment by eeprommemory** [comment]
so the hope is put original firmware back in and get usb working again and update CPLD.

**Comment by miek** [comment]
That .bin file is written to address 0 on the SPI flash as-is. It's only 22kB because that's the size of the firmware - there's no need to pad it out to 1MB.

However, if DFU is not working then this is really unlikely to be a firmware problem. The DFU bootloader is burned in ROM on the LPC4320 & is selected with a dedicated pin. There's no way to overwrite or damage it with firmware updates.

**Comment by eeprommemory** [comment]
connecting hackrf to a battery bank seems to be the issue not software.
checked the data lines D+ and D- D- was direct short to ground.
removed U15 LXES1T1BCC2-004 short gone but still does not work.
I normality see a 100ohm resistor on USB ports going to a 3.3V CPU R58 and R57 are 0ohm.
so CPU fried no saving it.

**Comment by eeprommemory** [comment]
looked at datasheet and USB goes directly to cpu so why have R58 and R57 i have no idea.

**Comment by R2DYN** [comment]
> need bin file for U20 W25Q80BV
My bin file W25Q80BV (firmware hackrf-2024.02.1)  

[ROM Winbond W25Q80BV.zip](https://github.com/user-attachments/files/22989854/ROM.Winbond.W25Q80BV.zip)
