### ISSUE TITLE
How to configure Opera Cake to make HackRF One automated switching based on time

### ISSUE THREAD

**Issue by Zero1116** [mossmann/hackrf#687]
How to configure Opera Cake to make HackRF One automated switching based on time? I didn't find a command to do it.

**Comment by miek** [comment]
It's not supported at the moment - it's dependent on merging @docprofsky's code, more detail in #527

**Comment by Zero1116** [comment]
> It's not supported at the moment - it's dependent on merging @docprofsky's code, more detail in #527

I have merged the code, but I don't know how to start Pseudo-Doppler mode.
