### ISSUE TITLE
Use HackRf as Vector Network Analyzer (VNA)

### ISSUE THREAD

**Issue by robkers1993** [mossmann/hackrf#694]
Hi All!

Not sure about the place where to ask this question, so my appologies if I'm at the wrong place.

I was wondering if, and how, I could use the HackRf as a VNA. I would like to know the transfer of a RF filter for a 2.4 GHz radio. Since the HackRF could go up to 6GHz, I would be able to measure the first higher harmonic. 

I figure that I "simply" buy two HackRF ones, put one in TX mode, the other in RX mode. I would connect all the components and write a script that syncs the frequencies between the TX and RX device. 

I came here to check the feasibility, possible problems, and to know if there would be an easier way of measuring the transfer function (amplitude is sufficient, phase shift is not my main concern for now)?

Many Thanks!
Rob

**Comment by mossmann** [comment]
Yes, that can work.  When I do this I often use qspectrumanalyzer (sweeping quickly) on the receiving HackRF and script hackrf_transfer -c (sweeping slowly) on the transmitting HackRF.  The main thing you need to watch out for is that you don't blow out the receiving HackRF by transmitting with too much power.  I use a 20 dB SMA attenuator for safety.

In theory you could extend this solution from scalar measurements to vector measurements by synchronizing the clocks of the two HackRFs and tuning them to the same fixed frequency, but phase calibration would be tricky as there are a several different conditions (including tuning to a new frequency) that would necessitate recalibration.
