### ISSUE TITLE
invalid data at start of RX or TX

### ISSUE THREAD

**Issue by mossmann** [mossmann/hackrf#703]
In RX mode (e.g. `hackrf_transfer -r`) the first USB buffer of data received by the host is often invalid, typically left over from a previous RX or TX operation.

In TX mode (e.g. `hackrf_transfer -t`) the first USB buffer of data transmitted over the air has the same problem.

**Comment by mossmann** [comment]
For the specific case of the first RX operation after a HackRF is powered on, there is a trivial fix: set `phase = 1` as the initial value in hackrf_usb.c.

I want a more general solution than that.

**Comment by mossmann** [comment]
sweep_mode() does the right thing in setting `phase = 1` when starting, but it ought to do something about  usb_bulk_buffer_offset as well, perhaps in baseband_streaming_enable().  All three modes (RX, TX, and sweep) should probably be mutually exclusive states in a state machine.

**Comment by mossmann** [comment]
I have a branch in progress here: https://github.com/mossmann/hackrf/tree/transceiver

**Comment by ebarnard** [comment]
See #662. Fixing this issue is a side effect of that PR.

**Comment by ebarnard** [comment]
Your branch looks neater but it would be great if you could incorporate the changes to flush the SGPIO buffer and pre-fill the libusb tranfer buffers on transmit.

**Comment by mossmann** [comment]
Ooh, I should have taken a closer look at #662 when I started investigating this issue.  I'm going through it now.

**Comment by mossmann** [comment]
@miek Can you take a look at this too?

**Comment by miek** [comment]
Looks good! Definitely tidies things up a lot.

I think it breaks the CPLD update though: CPLD update has been changed to a proper transceiver mode, but `usb_vendor_request_set_transceiver_mode` hasn't been changed to actually set the transceiver mode when `TRANSCEIVER_MODE_CPLD_UPDATE` is specified.

**Comment by miek** [comment]
I rebased `transceiver` on master (here: https://github.com/miek/hackrf/tree/transceiver) and set up for some testing:

I'm tuned to 20MHz, sample rate 20M. I first transmit a 5MHz sine to fill the buffers, stop, then transmit a 0Hz sine and take a capture. CH1 is the TX LED (finally a reason to populate P5, I'm gradually filling all the empty headers :smiley:), CH2 is the RF output, CH3 is TXBBI+.

master (with a chunk of samples from the previous TX at the start):
![scope_0](https://user-images.githubusercontent.com/578095/74345097-6ead1180-4da5-11ea-82cf-744de6ca61a4.png)

miek/transceiver:
![scope_1](https://user-images.githubusercontent.com/578095/74345198-9ef4b000-4da5-11ea-942f-323d9655b3e8.png)

So it's certainly getting rid of that chunk of the previous samples, but the chunk of noise right after remains. I'll see if I can figure out where that's coming from.

**Comment by ebarnard** [comment]
The chunk of noise is due to the fact that libhackrf sends four buffers containing uninitialised memory to the HackRF before the first user supplied buffer. It calls `libusb_submit_transfer` for each of the four libusb transfers without first filling the transfer buffers.

In #662 I've made the following changes to fix this:
1. libhackrf requests data to fill the four transfer buffers before initialising the transfers. Thus the first four buffers sent to the HackRF no longer contain the contents of uninitialised memory.
2. In TX mode the HackRF waits for the first USB buffer to be received before starting to output samples. This means that in hardware triggered mode the first sample to be output is the first user provided sample.

**Comment by miek** [comment]
@ebarnard Yep, that was it - thank you! I've pushed a fix to my branch (I'd like to get `transceiver` merged to fix this issue first, then I'll look at getting your changes merged on top).

**Comment by miek** [comment]
RX is also looking good, here's a capture of a 50.5MHz signal, take with `hackrf_transfer -r temp.cs8 -s 20e6 -f 50e6 -n 20000000 -l 16 -g 24`:

`master`:
![rx-master](https://user-images.githubusercontent.com/578095/74364911-f6564880-4dc4-11ea-968b-f9fc1a304c4b.png)

`transceiver`:
![rx-transceiver](https://user-images.githubusercontent.com/578095/74365002-243b8d00-4dc5-11ea-8423-e178b9d5af2c.png)

Obviously there's still some junk, probably from PLLs settling. Not sure if we want to include that in the scope of this issue?

**Comment by ebarnard** [comment]
I would imagine that could be down to hackrf_transfer calling `hackrf_set_freq` (and a few other setup functions) after `hackrf_start_tx/rx` [(link)](https://github.com/mossmann/hackrf/blob/master/host/hackrf-tools/src/hackrf_transfer.c#L966). 

`hackrf_set_freq` results in [`set_freq`](https://github.com/mossmann/hackrf/blob/master/firmware/common/tuning.c#L57) being called which first toggles the MAX2837 in and out of standby mode even if the frequency is not being changed via `max2837_set_mode(&max2837, MAX2837_MODE_STANDBY)` and `max2837_set_mode(&max2837, prior_max2837_mode)`.

I imagine this would have a unpredictable effects on the samples being read by the MAX5864 during this process.

It should be a trivial thing to fix assuming there's not a good reason for this ordering of setup operations.
