### ISSUE TITLE
Integrate HackRF board to laptop

### ISSUE THREAD

**Issue by 5l1v3r1** [mossmann/hackrf#704]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what you expect should happen

Well it is not an issue but i really wonder, is there a way to this? I mean we can use the space of cd-rom. 

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by mossmann** [comment]
HackRF One is 120 mm x 75 mm (not counting connectors) which is 20 mm longer than the diameter of a CD.  Some internal optical drive bays may be long enough, but I imagine that some are not.  You would probably need to desolder the connectors (CLKIN, CLKOUT, USB) from one end and directly solder a USB connection from inside the laptop.  A suitable USB connection might be available on the drive bay connector.  It would be a tricky modification targeting an individual laptop model, but it may be possible.

Alternatively you could redesign a HackRF PCB for this, but that would be a great deal of work to produce something that fits only one model of laptop.
