### ISSUE TITLE
Due to a bad cable, the U15 LXES1TBCC2-004 burned out. Help me.

### ISSUE THREAD

**Issue by skyden-ua** [mossmann/hackrf#710]
Due to a bad cable, the U15 LXES1TBCC2-004 burned out. Help me.
For earlier I apologize for English google translator is to blame for everything))

The story is this, I connected the device with a bad cable and after a few seconds smoke came out of it.
I know for sure that the U15 LXES1TBCC2-004 burned out because it had a hole.
the question is, what else could suffer?
a local mobile phone repairman, got drunk and said should earn without this detail (of course this did not happen)

I have a portapack without battery.
Could I supply power to the contacts to test the functionality of these devices without USB?
if so, what contacts and how many volts?

With great pleasure I will accept any advice on the diagnosis and restoration of these devices.

PS
Be careful with the cables, have a nice day everyone.

![IMG_3754](https://user-images.githubusercontent.com/56937519/75887589-1369be80-5e3b-11ea-8ff7-5d2ba46d50e6.PNG)
![IMG_3755](https://user-images.githubusercontent.com/56937519/75887617-211f4400-5e3b-11ea-9bb2-a7c56982e3bc.jpg)

**Comment by RChadwick7** [comment]
I'm in the same boat. The LXES1TBCC2-004 was discontinued, as I'm sure you know by now. The only substitute I could find was a DRTR5V0U4LP16. You should check the datasheets yourself, and please let us know if it works.

**Comment by catalinalb** [comment]
As I read through all of this I start to wonder since I use a magnetic micro usb cable for the hackrf to avoid damaging the socket. It works fine still even with the portapack even though the usb cable is thin. 🙂

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mossmann** [comment]
We use Vishay part number VBUS54CV-HSF-G4-08 for U15. This has been documented in the KiCad source since 2018.

**Comment by mossmann** [comment]
Your HackRF One should operate normally (but lacks ESD protection) with U15 removed. Testing in that configuration would be a good first step to determine if everything else is working correctly.

**Comment by miek** [comment]
Could you give a bit more info about how you were powering the HackRF when it went wrong? Make/model of any battery packs or power supplies would be helpful.

**Comment by skyden-ua** [comment]
> Ваш HackRF One должен работать нормально (но без защиты от электростатического разряда) с удаленным U15. Тестирование в этой конфигурации было бы хорошим первым шагом, чтобы определить, все ли работает правильно.

Hello.
 Today I drank U15 LXES1TBCC2-004 and applied power to usb. Portapack showed no sign of life. The detail that I noted "t" is heated. I did not wait for a critical temperature and turned it off.
 I am also confused by the detail that I noted "?" it’s probably a stabilizer of drunkenness and a burn mark on it. Perhaps this is from U15 LXES1TBCC2-004 and the part is "?" whole.
Can I apply stabilized voltage to some place from the portapack side and run both boards? I met portapack with a built-in battery (I don’t have one) and pre-sented that you can revive them in this way.
If so, then what voltage do I need to apply and to which contacts?
I will be glad to any advice on the recovery and diagnosis of my accident.
![H](https://user-images.githubusercontent.com/56937519/78068489-2b345400-73a1-11ea-87d4-5759abb559b4.jpg)

**Comment by skyden-ua** [comment]
> Не могли бы вы дать немного больше информации о том, как вы использовали HackRF, когда он пошел не так? Марка / модель любых аккумуляторов или блоков питания будет полезна.

It looked like there was a hidden mechanical damage inside the cable, and at some point a short circuit occurred. The cable was high-quality, but it worked for many years.

**Comment by vasja2000** [comment]
> > Ваш HackRF One должен работать нормально (но без защиты от электростатического разряда) с удаленным U15. Тестирование в этой конфигурации было бы хорошим первым шагом, чтобы определить, все ли работает правильно.
> 
> Hello.
>  Today I drank U15 LXES1TBCC2-004 and applied power to usb. Portapack showed no sign of life. The detail that I noted "t" is heated. I did not wait for a critical temperature and turned it off.
>  I am also confused by the detail that I noted "?" it’s probably a stabilizer of drunkenness and a burn mark on it. Perhaps this is from U15 LXES1TBCC2-004 and the part is "?" whole.
> Can I apply stabilized voltage to some place from the portapack side and run both boards? I met portapack with a built-in battery (I don’t have one) and pre-sented that you can revive them in this way.
> If so, then what voltage do I need to apply and to which contacts?
> I will be glad to any advice on the recovery and diagnosis of my accident.
> ![InkedH_LI](https://user-images.githubusercontent.com/56937519/78068769-abf35000-73a1-11ea-85ab-e00654458bb4.jpg)

I think it can help
![изображение](https://user-images.githubusercontent.com/41041257/78463854-aae85880-76ea-11ea-999e-c4cb95d91981.png)

**Comment by vasja2000** [comment]
Кстати да! где этот транзистор или что это?
By the way, yes! where is this transistor or what is it?
![изображение](https://user-images.githubusercontent.com/41041257/78470766-7bf6d480-7734-11ea-845b-373b5fa29547.png)

**Comment by mossmann** [comment]
> Can I apply stabilized voltage to some place from the portapack side and run both boards?

You can apply 5 V to P20 pin 22 and ground to P20 pin 19.

**Comment by mossmann** [comment]
> Кстати да! где этот транзистор или что это?
> By the way, yes! where is this transistor or what is it?

The parts you have circled are resistors. One of them is a 0 ohm resistor, so it is really a short.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
