### ISSUE TITLE
Questions regarding gpsdo usage

### ISSUE THREAD

**Issue by strgaltdel** [mossmann/hackrf#711]
Hi,

i have bought a gpsdo that the manufacturer claims is suitable for hackrfone
https://shop.elektronikidee.de/product_info.php?language=en&info=p66_10mhz---40mhz-low-power-gps-frequenznormal-standard-0-001ppm-z-b--fuer-pluto-sdr.html

The device is recognized by hackrfone and measurements shows a tiny frequency difference than without

the output of the device is a sin wave (app +-1,9V, so 3,8Vpp)

according to the hackrfone description, CLKIN should be feeded by a square wave 0-3,3V,
the signal never should drop under 0V !

(1)
So, how could be that the gpsdo works fine, 
or in other words:
will this gpsdo damage the hackrfone?

(2)
until i got the gpsdo i tested hackrfone using a tcxo
Even then hackrf_debug detects an external clock.
What clock signal will be used, when the tcxo remains in hackrfone and i connect the gpsdo to hackrf ?

thanks and regards

Udo

**Comment by miek** [comment]
> according to the hackrfone description, CLKIN should be feeded by a square wave 0-3,3V,
> the signal never should drop under 0V !
> 
> (1)
> So, how could be that the gpsdo works fine,
> or in other words:
> will this gpsdo damage the hackrfone?

Yes, you are risking damage to the HackRF One using that GPSDO - it's operating outside the absolute maximum ratings of the clock generator IC on the board.

> (2)
> until i got the gpsdo i tested hackrfone using a tcxo
> Even then hackrf_debug detects an external clock.
> What clock signal will be used, when the tcxo remains in hackrfone and i connect the gpsdo to hackrf ?

You should only have one of them connected at any time, as they share the same pin for clock input:

![hackrf-clkin](https://user-images.githubusercontent.com/578095/76959115-d9a3b800-6910-11ea-83a4-cf9e4ac8ba64.png)
