### ISSUE TITLE
Lost all usb connectivity

### ISSUE THREAD

**Issue by 49handyman** [mossmann/hackrf#713]
### Steps to reproduce
1. windows 10
2. plug into working usb port
3. unable to identify usb device
4. portapack continued worked fine 

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead
unrecognized

would not recognize usb or dfu on multiple cables, 

Tests and repairs made:
1. Removed Portapack
2. re-soldered micro usb, retested with no improvement
3. tested all voltages in and out of all regulators -- Tested Good
4. looked up LXES1TBCC2-004 ESD protection chip
5. started to test voltages, but noticed the USB light was now lit -- checked zadiag -- Good
6. removed USB cable - powered off
7. inserted USB cable - powered on fine with USB light and windows device manager --- Good

Not sure if there is a reset on ESD chip or not, but possible cause.... more research needed now.

### Version information
**Operating system**:
windows 10
**hackrf_info output:**

hackrf_info version: git-92ee144
libhackrf version: git-92ee144 (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000c83868dc2c803ba3
Board ID Number: 2 (HackRF One)
Firmware Version: local-889220bb (API:1.03)
Part ID Number: 0xa000cb3c 0x00544374

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by JonaldJohnston** [comment]
seems to be related to my issue #681, looks like an ESD chip problem then?

**Comment by straithe** [comment]
Are you still experiencing this issue?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
