### ISSUE TITLE
LXES1TBCC2-004 chip blown

### ISSUE THREAD

**Issue by JonaldJohnston** [mossmann/hackrf#715]
my usb connection had been completely not working for a while (#681), couldn't figure out why. issue #713 led me to look at the LXES1TBCC2-004 chip on my board, and it looks like the smoke got let out: ![DSCN3682](https://user-images.githubusercontent.com/38843705/76694636-5863d100-6643-11ea-9ed6-026e014a414f.jpg)

Anywhere i could get a replacement chip? Or should i just send it in? its listed as obsolete and im having trouble finding them for sale.

**Comment by miek** [comment]
Could you give a bit more info about how you were powering the HackRF when it went wrong? Make/model of any battery packs or power supplies would be helpful.

**Comment by JonaldJohnston** [comment]
I don't exactly know, i put the HackRF away for a while and brought it back out so i could update the portapack firmware, that's when i discovered that the USB was no longer working. i have no idea what cables/battery packs i was using.

**Comment by JonaldJohnston** [comment]
Looks like #710 mentions using VBUS54CV-HSF-G4-08 instead of the LXES1TBCC2-004, will try.

**Comment by JonaldJohnston** [comment]
Looks like taking out the LXES1TBCC2-004 without replacing it with anything is a temporary fix, although i wouldn't recommend it as you might end up damaging something you cant replace :), will mark as closed for now.
