### ISSUE TITLE
 HackRF in the role of an oscilloscope

### ISSUE THREAD

**Issue by Rashid-S** [mossmann/hackrf#722]
Someone tried to use a HackRF in the role of an oscilloscope in a GNU Radio. Share your experience please.

**Comment by GravesJake** [comment]
It is possible to use a HackRF as an "oscilloscope" but it will be very easy to damage the ADC. Check the SDR video series for an example.

**Comment by ktemkin** [comment]
I'd definitely note the quotes on there-- there are a bunch of limitations that make HackRF hard to use this way (including AC input coupling and a relatively-low-impedance frontend that's meant for small amount of RF power). :)

**Comment by 5ch4um1** [comment]
Sort of, i tried to look at OOK radio signals with the time sink in gnuradio 3.7:
![image](https://user-images.githubusercontent.com/36307725/104533758-e6656b00-560a-11eb-8c66-e114d15cd8b4.png)
The closest i ever got to using an oscilloscope was running xoscope (soundcard o-scope) on my laptop, so i am a total beginner with this topic, but if you activate the controls and the grid, the time sink looks a bit like an oscilloscope.
But while the trigger function in xoscope worked for me more or less intuitively as expected, i could never figure out how this is supposed to work in gnuradio, probably i am using it wrong? It just won't stop?
![image](https://user-images.githubusercontent.com/36307725/104534253-d8fcb080-560b-11eb-9778-df04e29cff7b.png)
