### ISSUE TITLE
Question: How to use hackrf_transfer to capture just a few kHz?

### ISSUE THREAD

**Issue by Krack1n** [mossmann/hackrf#724]
This is not an issue but just a simple question I cannot find the answer for anywhere. I'm just wondering if it is possible to capture a very narrow band of just a few kHZ using the hackrf_transfer tool. If so, what options do you use to do that and if not is there any other tool possibly cut down a capture to just a few kHZ?
Thank you.

**Comment by miek** [comment]
It's not possible to do a capture that narrow in `hackrf_transfer`. For best results, capture with as high a sample rate as possible with the minimum bandwidth setting (1.75MHz). Then use an external tool to filter and decimate: a good option would be a GNURadio's flowgraph using the Low-pass filter block (or the Xlating FIR filter block, if you're doing offset tuning). You could also use inspectrum's tuner & export samples feature for one-off processing.
