### ISSUE TITLE
hackrf python ctypes

### ISSUE THREAD

**Issue by 49handyman** [mossmann/hackrf#726]
I've researched this hard before posting here and spent 20+ hours trying to port to windows.

how can we get ctypes to work with hackrf.dll  or .lib?  i've tried everything found in 15+ articles and tried all linux versions on git hub already.  5+ versions

i can load libusb-1.0.dll and rtlsdr.dll in python ctypes no problem and the wrapper for rtlsdr works fine on windows. Why cant i get any where porting this to windows?

confirmed all is 64-bit do i need libusb instead of winusb?

i love the hackrf but really want to stick with windows.

**Comment by straithe** [comment]
This sounds like a very ambitious project, and you've definitely put a lot of effort into it! Unfortunately, at this time we are unable to provide direct support for this endeavour. Happy hacking!
