### ISSUE TITLE
HackRF Not Responding after transmit.

### ISSUE THREAD

**Issue by letvinov28** [mossmann/hackrf#727]
HostOS:Win10
VirtualOS:ParrotOS
My hackRF stop work after first trasmit.

>  └──╼ $hackrf_transfer -r /dev/null -s 20000
> call hackrf_set_sample_rate(20000 Hz/0.020 MHz)
> call hackrf_set_freq(900000000 Hz/900.000 MHz)
> Stop with Ctrl-C
>  0.5 MiB / 1.000 sec =  0.5 MiB/second
>  0.3 MiB / 1.004 sec =  0.3 MiB/second
> ^CCaught signal 2
>  0.3 MiB / 0.510 sec =  0.5 MiB/second
>  Exiting...
> Total time: 2.51408 s
> hackrf_stop_rx() done
> hackrf_close() done
> hackrf_exit() done
> fclose(fd) done
> exit
> ┌─[user@parrot]─[~]
> └──╼ $hackrf_transfer -r /dev/null -s 20000
> call hackrf_set_sample_rate(20000 Hz/0.020 MHz)
> call hackrf_set_freq(900000000 Hz/900.000 MHz)
> Stop with Ctrl-C
>  0.0 MiB / 1.001 sec =  0.0 MiB/second
> 
> Couldn't transfer any bytes for one second.
> 
> Exiting... hackrf_is_streaming() result: HACKRF_TRUE (1)
> Total time: 1.00116 s
> hackrf_stop_rx() done
> hackrf_close() done
> hackrf_exit() done
> fclose(fd) done
> exit
> ┌─[✗]─[user@parrot]─[~]
> └──╼ $
> 

And in GQRX my hackrf stop work if i change any settings.

**Comment by GravesJake** [comment]
Can you describe the GQRX issue? Paste `hackrf_info` output?

**Comment by straithe** [comment]
Are you still having trouble? We will close this issue if we don't get a reply within the next month.

**Comment by letvinov28** [comment]
Hello, last time when i test HackRF yes i had troubles. Today i will test
one more time and then i will reply you.

**Comment by straithe** [comment]
Were you able to test your HackRF again?

**Comment by letvinov28** [comment]
Please excuse me, I completely forgot that I had to do this. There were
many unexpected problems. I promise today by 3 o'clock (+ 0GMT) I will do
all the tests. But as far as I remember, the problem was only in Vmware on
the physical host, everything worked well.

чт, 11 февр. 2021 г., 01:04 Straithe <notifications@github.com>:

**Comment by letvinov28** [comment]
Hello, I checked my device and as I said the problem is only on this
machine.

**Comment by straithe** [comment]
What happens when you try a different OS, such as Ubuntu, on your VM?

**Comment by letvinov28** [comment]
Same story , tested on Ubuntu, Arch , Debian. Maybe problem is in host os?
Mac OS

вт, 16 февр. 2021 г., 04:05 Straithe <notifications@github.com>:

**Comment by mossmann** [comment]
Thank you for bringing this to our attention, but unfortunately we are not able to support operation on virtual machines. There are too many combinations of vm software and operating systems for us to test, and USB pass-through is one of the least reliable features of vm software in our experience.  If you experience similar problems when operating in a native OS, please open a new issue.
