### ISSUE TITLE
firmware update fixes gr-gsm

### ISSUE THREAD

**Issue by theoden8** [mossmann/hackrf#728]
The release page says for [release 2018.01.1](https://github.com/mossmann/hackrf/releases/tag/v2018.01.1)

> ... If you do not frequently use DFU boot, there is no reason to upgrade to this release.

[grgsm_livemon](https://github.com/ptrkrysik/gr-gsm) was not detecting hackrf as an appropriate device until I updated the firmware.

**Comment by straithe** [comment]
Thank you for the tip!
