### ISSUE TITLE
HackRF One Tx Spectrum Problem

### ISSUE THREAD

**Issue by eoinoc87** [mossmann/hackrf#731]
Hi all,

I created some IQ samples of white noise with an Fs of 8MHz and a bandwidth of 2 MHz.
The RF spectrum with external RF amplification has nasty side bands where I see images of the spectrum at 7.4MHz offsets from the center of my band.

For example if I transmit @ 850MHz, i see mirror images of the baseband signal at 850 + 7.4 and 850 -7.4 and again at 850+ 14.8 and 850 -14.8 and so on.

Does anybody have an idea whats going on? It looks like there is a 7.4MHz tone getting into the chain and mixing in with my baseband signal.

I am using the console along with an iq sample file to generate this spectrum. Has anybody ever seen problems like this before?

Eoin

**Comment by miek** [comment]
Do you see those tones without external amplification?
