### ISSUE TITLE
Help getting started with HackRF One on Ubuntu 18.04

### ISSUE THREAD

**Issue by zen1963** [mossmann/hackrf#734]
i can't  include a screen shot , because I haven't  started yet to install hackrf one ! This page is the only on I found to install hackfr on ubuntu 18-04  ! That's why I want to understand this advice to follow it after following pelixm ... 
Thanks for you help ! I am a beginner !

_Originally posted by @zen1963 in https://github.com/mossmann/hackrf/issues/605#issuecomment-616197760_

**Comment by ChasJutaro** [comment]
> i can't include a screen shot , because I haven't started yet to install hackrf one ! This page is the only on I found to install hackfr on ubuntu 18-04 ! That's why I want to understand this advice to follow it after following pelixm ...
> Thanks for you help ! I am a beginner !
> 
> _Originally posted by @zen1963 in [#605 (comment)](https://github.com/mossmann/hackrf/issues/605#issuecomment-616197760)_

Do you have the hackrf one device with you?
If you are new to Linux in general, I wouldn't start with the HackRF one, since using the HackRF One needs some knowledge on how to configure Linux.

If you're not a Linux beginner, then you can proceed and follow the guide in this repo's wiki on setting up on Ubuntu.

If you're a Linux beginner, follow the same guide but use a RTL-SDR dongle instead, cause that would be much easier to work with.

**Comment by zen1963** [comment]
I Have the kackrf one device with me . 
And I tried ton install it following these orders :
Step 1 sudo apt-get update -y
Step 2
sudo apt-get install -y hackrf
At the end I find that ;
![Capture d’écran_2020-04-20_15-17-26](https://user-images.githubusercontent.com/63970730/79755967-3a604f00-831a-11ea-8ff2-32b5975ede5f.png)
And when I triy to use this command : hackrf_info 
I find that on the terminal :
![Capture d’écran_2020-04-20_15-09-29](https://user-images.githubusercontent.com/63970730/79756136-71cefb80-831a-11ea-9d2f-0baa2ac4bf02.png)
What does it mean ?

**Comment by zen1963** [comment]
However the hackrf one is well connected : all the leds light up well !

**Comment by zen1963** [comment]
What  can i do to unlock : ? I can access to the the hackrf info !

**Comment by miek** [comment]
Check what groups your user is already in with the `groups` command. You probably need to add your user to the `plugdev` group if it's not listed, see here for details on how to do that: https://askubuntu.com/a/79566

**Comment by zen1963** [comment]
How can I check " what  groups your user is already in with the groups command "
I can't access to hackrf info but I haven't any problem to access hackrf _transfer ! What does it mean ? 
Hackrf is well installed and I can use it even I can't access to hackrf _info ?

**Comment by zen1963** [comment]
![Capture d’écran_2020-04-20_16-41-25](https://user-images.githubusercontent.com/63970730/79767433-9da5ad80-8329-11ea-809c-7b9387f3479f.png)

**Comment by ChasJutaro** [comment]
ur hackrf_info is working correctly.
You just need admin access to access hackrf one device go retrieve the relevant information.
I.e. run again using "sudo hackef_info"

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by miek** [comment]
> How can I check " what groups your user is already in with the groups command "

Type the word `groups` into a terminal. It will list which groups your user is in. If `plugdev` is not in the list, follow the instructions above to add it.

> I can't access to hackrf info but I haven't any problem to access hackrf _transfer ! What does it mean ?

`hackrf_transfer` is just showing the help there, it's not trying to access the USB device so it doesn't hit the permissions error

**Comment by zen1963** [comment]
Thant you Very much for your help !  It was very helpful from you for helping me ! Have a nice day and more ....

**Comment by zen1963** [comment]
Thant you Very much for your help !  It was very helpful from you for helping me ! Have a nice day and more ....

**Comment by zen1963** [comment]
Hi , 
I have  another problem when I enter this command ; hackrf_transfer   ͞  r  /dev/null it doesn't work as on the lesson 5 of Michael Ossman ! 
The  same lines with the command : hackrf_transfer are repeated !
And I notice that there is two lines that we don't find on the lesson 5 of Michael Ossman :
![Capture d’écran_2020-04-24_14-04-10](https://user-images.githubusercontent.com/63970730/80210722-840bab00-8634-11ea-9990-6584e6fe98d5.png)
![Capture d’écran_2020-04-24_13-58-42](https://user-images.githubusercontent.com/63970730/80210848-c634ec80-8634-11ea-8280-0e44a5e05bca.png)

**Comment by zen1963** [comment]
Any one to help me ?

**Comment by zen1963** [comment]
Hi , What's wrong when I enter this line of command : hackrf_transfer  ͞  r /dev/null  it doesn't work ?

**Comment by miek** [comment]
Could you paste the output from when you run `hackrf_transfer -r /dev/null`? The pictures above only show runs with no arguments.

**Comment by zen1963** [comment]
Hi , What's wrong when I enter this line of command : hackrf_transfer  ͞  r /dev/null  it doesn't work ? 
![Capture d’écran_2020-04-28_16-51-57](https://user-images.githubusercontent.com/63970730/80502244-a96c2200-8970-11ea-98c0-8b9db7b2c421.png)

**Comment by zen1963** [comment]
I paste the output with arguments  ! It's what you asked ?

**Comment by zen1963** [comment]
as I told it the runs it's the same when I enter this argument ; hackrf_transfer !

**Comment by miek** [comment]
The symbol before 'r' must be '-' (a hyphen). The command you're entering has some other symbol which is not recognised.

**Comment by zen1963** [comment]
Thanks Mike ! It's better but now when I run hackrf_transfer -r dev/null it fail to open file !
![Capture d’écran_2020-04-29_08-15-33](https://user-images.githubusercontent.com/63970730/80566104-78cccc80-89f2-11ea-868c-d6c32b964dd6.png)

**Comment by miek** [comment]
It should be `/dev/null` - note the leading slash.

**Comment by zen1963** [comment]
Thank you so much Mike . I'm ashamed to be so dizzy !
When I run hackrfè_transfer -r /del/null it works now but  it doesn't stop !!! 
![Capture d’écran_2020-04-30_10-58-14](https://user-images.githubusercontent.com/63970730/80692942-9a9d8080-8ad2-11ea-8526-11f64ef69b1c.png)
It contines without stopping !

**Comment by miek** [comment]
Yep, that's expected - it will carry on until stopped. You can stop it with CTRL+C.

**Comment by zen1963** [comment]
Thanks a lot Mike .. I am very grateful to you .
it works !! 
It means now everything is ok ?
