### ISSUE TITLE
No HackRF boards found.

### ISSUE THREAD

**Issue by ChansimDeng** [mossmann/hackrf#737]
### Steps to reproduce
**problem：**
hackrf_info:
hackrf_info version: git-43e6f99
libhackrf version: git-43e6f99 (0.5)
No HackRF boards found.

1.my env:
Physical machine：mac os
virtual machine：ubuntu 16(hackrf use)

and I also successfully installed the required libraries in ubuntu, eg:libusb-1.0-0-dev hackrf

**Comment by ChansimDeng** [comment]
@mossmann

**Comment by ChansimDeng** [comment]
and command (lsusb) in ubuntu info:

Bus 001 Device 002: ID 0e0f:000b VMware, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 005: ID 0e0f:0008 VMware, Inc. 
Bus 002 Device 003: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 002 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

**Comment by GravesJake** [comment]
Are you able to see your device on the host machine?

**Comment by ChansimDeng** [comment]
yeah, On my mac i can see usb information
![image](https://user-images.githubusercontent.com/20291976/81882091-6b077180-95c4-11ea-9961-bdcd8ce15b11.png)

**Comment by GravesJake** [comment]
Sorry for the delay, I've not been able to reproduce this. What macos version are you running? VM software?
