### ISSUE TITLE
HackRF One TCXO issue

### ISSUE THREAD

**Issue by heesungsong** [mossmann/hackrf#738]
### Steps to reproduce
1. I installed the TCXO on the HackRF One and sensed something strange. 
It returned to normal after the TCXO release.
2. FM Receiving (88-100Mhz)
3. There is a lot of noise and a low reception.
4. It looks like it's transmitting when it's not transmitting.

![1](https://user-images.githubusercontent.com/65500552/82153218-1fddaf00-98a1-11ea-8309-1568da7f68ec.png)

### Expected behaviour
 The reception is not good.### Actual behaviour

### Version information
**Operating system**:
Windows 7 

**hackrf_info output:**

hackrf_info 버전 : unknown
libhackrf 버전 : unknown (0.5)
Found HackRF
Index: 0
Serial number : 0000000000000000901868dc2966808b
Board ID Number : 2 (HackRF One)
Firmware Version : 2018.01.1 (API : 1.02)
Part ID Number : 0xa000cb3c 0x00674755

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.
!

### Output
```
Insert any commandline or build output here
```

**Comment by eried** [comment]
That spike is the way it works https://github.com/mossmann/hackrf/wiki/FAQ#what-is-this-big-spike-in-the-center-of-my-received-spectrum, post a video comparison with and without the accessory, without changing anything else to see how the quality degrades
