### ISSUE TITLE
hackrf one range

### ISSUE THREAD

**Issue by roboticsai** [mossmann/hackrf#739]
i have non technical question. i tried to search this question in internet but didn't found any. My question is what is the maximum range i.e distance from which this device can be connected and audio, video can be communicated two way. 

And does it also works with ROS, odroid c2, ubuntu 18?

**Comment by eried** [comment]
The range question does not really have any simple answer, you can check the transmit power https://github.com/mossmann/hackrf/wiki/HackRF-One#transmit-power and use some online calculator to get some ballpark number. The number you are looking for is: "depends" meters.
