### ISSUE TITLE
Jump in noise floor of several decibels 

### ISSUE THREAD

**Issue by jbaggs** [mossmann/hackrf#751]
I have been experiencing an issue with the noise floor suddenly increasing by 4-10 dB (depending on amplification) over a wide portion of spectrum (peak at least 30 mHz wide) for some time now. It can last anywhere from a number of minutes to hours, independent of time of day, and seemingly independent of temperature. It does not appear to matter how long the HackRF has been in use, and is not resolved with a restart. It is not affected by whether or not the computer running it is on wall power or battery. 

I would lean towards outside interference, except for the fact that it is so broad, and not fitting any patterns I can discern. Is there any component that could be failing that might cause the issue?

Images of a 5 mHz section of VHF spectrum, with and without the noise, both with AMP on, and off:
AMP on, normal:
![amp-normal](https://user-images.githubusercontent.com/15326032/85215918-b0416080-b333-11ea-8fc7-b1b5997b9fa1.png)
AMP on, noise:
![amp-noise](https://user-images.githubusercontent.com/15326032/85215925-b7686e80-b333-11ea-8ede-37634da20fce.png)
AMP off, normal:
![amp_0-normal](https://user-images.githubusercontent.com/15326032/85215927-bcc5b900-b333-11ea-9c25-5a4507e279b5.png)
AMP off, noise:
![amp_0-noise](https://user-images.githubusercontent.com/15326032/85215929-bfc0a980-b333-11ea-8064-d492bd150765.png)

Thanks in advance for any ideas.

**Comment by mossmann** [comment]
Have you observed this in other bands? Does it happen with alternative USB cables?

**Comment by jbaggs** [comment]
I see it on low VHF as well. (e.g. 41.7 - 47.7 mHz) I can try some other bands, but will have to wait awhile to get both a clean and high noise picture. Switching USB cables doesn't help it. The one I normally use with the HackRF has ferrite chokes. Some others I have add noise on top of the reported problem.

**Comment by Videogamer555** [comment]
I'm guessing also outside interference. Possibly some ultrawideband communication mode of some kind.

**Comment by jbaggs** [comment]
This is at least 160 MHz wide at a constant power level with no signs of intentional modulation. It's definitely not an intentional emission, if it is external.

**Comment by jbaggs** [comment]
I put an AM demodulator in the middle of the spectrum where it seemed the worst, and noted there is a roughly 120 Hz raspy tone in with the the normal background noise. I had expected if there was line noise I would be hearing something more around 60 Hz, but did some reading and found that high voltage lines often arc on both sides of the cycle. I also threw together an impromptu mobile antenna and drove around a bit, confirming it is location dependent. Glad it is not the device.
