### ISSUE TITLE
What is the difference between -a and -p in hackrf_transfer?

### ISSUE THREAD

**Issue by Videogamer555** [mossmann/hackrf#752]
According to the official documentation for hackrf_transfer in the command line help.
[-a amp_enable] # RX/TX RF amplifier 1=Enable, 0=Disable.
[-p antenna_enable] # Antenna port power, 1=Enable, 0=Disable.

At first it sounds like -a activates in internal amplifier, but after looking at the source code and seeing this command line switch corresponds to the hackrf api function hackrf_set_amp_enable, and then looking at the description for that function on Github, it sounds like -a actually enables power to the antenna port, to run an external amplifier. Yet the -p command line switch also is supposed to enable power to the antenna port. So what's the difference? Also, I've noticed on my hackrf, even without an external amplifier, the -a command line switch appears to boost the strength of a transmitted signal.

Can somebody explain these features?

**Comment by miek** [comment]
-a controls the internal amplifier
-p controls power on the antenna connector for external devices

The description on the wiki was incorrect, I've fixed that.
