### ISSUE TITLE
HackRf one not working..

### ISSUE THREAD

**Issue by Fabtolab** [mossmann/hackrf#759]
### Steps to reproduce
1. Turning on..
2. Connecting PC to HackRF using the provided cable
3. Turning on SDR sharp in PC 

### Expected behaviour-
i wanna play fm radio using sdr sharp and gqrx.

### Actual behaviour
it is not  playing fm at any frequency and it is not showing any fm frequency in both sdr sharp and gqrx.

### operating system
windows  10,ubuntu 20.04,kali linux 2020.4

Gqrx version-2.11.5
Sdr sharp version-x86 rev 1732

### Additional Comments
Also it is not capturing car key fob signals
I also tried same things with my friend's hackrf his hackrf is working fine playing radio and capturing and transmitting car key fobs.

![WhatsApp Image 2020-07-07 at 5 32 07 PM](https://user-images.githubusercontent.com/66944097/86889657-bb5d0480-c119-11ea-9a69-f37ac4878e7d.jpeg)

**Comment by GravesJake** [comment]
Can you try downloading the [Release Package](https://github.com/mossmann/hackrf/releases/tag/v2018.01.1) and [updating your host tools](https://github.com/mossmann/hackrf/tree/master/host#how-to-build-the-host-software-on-linux) to match your Firmware Version (2018.01.1). 

After that can you post the output of `lsusb` and `hackrf_info` please?

**Comment by GravesJake** [comment]
Also screenshots of your fm capture would be helpful.

**Comment by Fabtolab** [comment]
Done but still no success..
Let me know..

![2d3dbd36-65c2-4f48-9af9-cfbd6b6563ab](https://user-images.githubusercontent.com/66944097/87221900-39751180-c38d-11ea-9e3a-dd489f7f3891.jpeg)
![31b577a3-cd17-497f-9e34-63768ae9ff21](https://user-images.githubusercontent.com/66944097/87221904-3aa63e80-c38d-11ea-926e-a144babf3c2f.jpeg)
![132c6aa5-af56-4863-a112-4979706608b5](https://user-images.githubusercontent.com/66944097/87221906-3b3ed500-c38d-11ea-8e49-869684703ac2.jpeg)
![903dd4b6-1f3a-49e1-9483-4743af163f7e](https://user-images.githubusercontent.com/66944097/87221907-3bd76b80-c38d-11ea-8d2a-ea415e3ac742.jpeg)

**Comment by Fabtolab** [comment]
Any updates?

**Comment by GravesJake** [comment]
What do the settings on the right side of the gqrx window look like? Also it doesn't appear that the host tools were properly updated to match the firmware version (hackrf_info version: unknown; libhackrf version: unknown)

**Comment by Fabtolab** [comment]
Hi Graves,
Customer is not getting it to work even after the updates. He is comparing his unit with another previous unit he has and upon doing the same things he is not getting the frequencies. 
Also he is saying that his other hackrf purchased previously also had hacked info and libhackrf versions unknown..
Please suggest..
Thanks,
Niraj, Fab.to.Lab

**Comment by GravesJake** [comment]
Could be a hardware issue, I'll email you with RMA info.

**Comment by Fabtolab** [comment]
Thanks Graves,
waiting..
We will place a new order soon. 
You can send the replacement alongwith.
We will share the shipping tracker asap.
Thanks,
Niraj
Fab.to.Lab
