### ISSUE TITLE
HackRF Goes into DFU mode, no output on lsusb.

### ISSUE THREAD

**Issue by mohitjaswal** [mossmann/hackrf#763]
### Steps to reproduce
1. The hackrf had Havoc firmware along with portapack. Stopped working all of a sudden while switching power source from a bty bank to regular adapter. Portapack Screen has gone off. 
2. HackRF goes into DFU mode but is not listed in lsusb. Removed Portapack, While in DFU Mode 3.3 V led is lit and Tx, Rx and USB led dim lit. 
3. DFU Mode - lsusb : The NXP chip is not getting listed even in DFU mode. 

### Expected behaviour
1. On removing the Portapack and Connecting the HackRF on DFU mode. The lsusb should have listed the NXP chip for further writing the firmware in through dfu-util.

### Actual behaviour
1. The hackrf does not get detected in any PC , tried with three,  Sigint OS, Windows and Kali VM. 
### Version information

**Operating system**:
Windows 10, SigintOS

**hackrf_info output:**

hackrf_info version: unknown
libhackrf version: unknown (0.5)
No HackRF boards found.

Any way of flashing the NXP CPU again using the GPIO Pins. I am less into flashing and stuff.
Thanks in advance.

**Comment by miek** [comment]
There's no simple way of re-flashing it (even using jtag, the actual flash programming happens over usb with `hackrf_spiflash`).
Though, given the symptoms, this sounds like a hardware failure that's stopping the NXP chip running at all. If you got your HackRF from one of our [resellers](https://greatscottgadgets.com/wheretobuy/) we can sort out a replacement.
