### ISSUE TITLE
Emission then reception

### ISSUE THREAD

**Issue by qwetch** [mossmann/hackrf#764]
Hello, I am sorry if there already was a topic answering my problem but I did not find any so I created a new one.

Here is my problem. I would like to ask a radar transponder and to listen to its response.

Precisely I would like to transmit a signal with my hackrf during a very short time (between 50n and 2us). Then I would like to listen to the device's response I asked. However I need to change from TX mode to RX mode in a very short time. I think I have to synchronize the begining of the reception with the end of my transmission but I do not know how to do this and if it is possible to do it with the hackrf.

I work with GNU Radio.

Thank you in advance for your response.

**Comment by miek** [comment]
With the existing software, it's not possible due to the USB delay (on the order of milliseconds).

It might be possible with some custom firmware, but I don't know offhand whether the hardware would be capable of switching that fast - you'd have to run some tests.
