### ISSUE TITLE
PCB manufacturing

### ISSUE THREAD

**Issue by zjobra** [mossmann/hackrf#779]
Good day!
This board is available at PCBHubs for easy manufacturing order
https://pcbhubs.com/newpcb/15983199695f446d6169506

**Comment by noviceFedora** [comment]
Thanks for this, I was looking for something like that. But unfortunately your link doesn't provide the total cost of all the components involved.

**Comment by miek** [comment]
Thanks!

**Comment by samsam3441** [comment]
hi I want to have a hack rf one device. can i order in this kicad project ? is it producible ??  They sells on amazon  400 dollars. 1 dollar equal 19 turk liras. in my country.  can i use pcbway assembly service ?? please help me
