### ISSUE TITLE
Python Library for Streaming HackRF I/Q Data

### ISSUE THREAD

**Issue by AgileEngineeringLLC** [mossmann/hackrf#785]
Is anyone aware of a working Python library for streaming HackRF I/Q Data? I've been trying this one:

https://github.com/dressel/pyhackrf

and I'm able to run the read_samples() command to grab a single block of data, but I'm not able to get the callback example working to continuously stream I/Q data. 

Thx! Don

**Comment by straithe** [comment]
Unfortunately we don't have a solution for this at this time. Python has recently gained the ability to do the asynchronous communications that are needed but, as far as we know, no one has put the effort in to creating the software you are looking for.
