### ISSUE TITLE
make: *** [all] Error 2

### ISSUE THREAD

**Issue by mieluw** [mossmann/hackrf#786]
I am using Ubuntu 18.04 LTS 64 bit
cmake 3.7.2
Python 3.6
Pip 3

when i try to makefrom this source https://github.com/mossmann/hackrf/tree/master/firmware it shows 
![Screenshot from 2020-09-08 01-45-07](https://user-images.githubusercontent.com/70920409/92419275-3328c900-f175-11ea-99fa-401600b90a84.png)

CMakeFiles/hackrf_usb_objects.dir/build.make:326: recipe for target 'CMakeFiles/hackrf_usb_objects.dir/usb_api_board_info.c.obj' failed

@postmodern @posixninja

**Comment by miek** [comment]
Could you post the full output from the cmake command?

**Comment by straithe** [comment]
Are you still having trouble? We will close this issue if we don't get a reply within the next month.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
