### ISSUE TITLE
Question: how to log signal above a certain threshold

### ISSUE THREAD

**Issue by larkolab** [mossmann/hackrf#787]
Hello,
I'm not sure if we can ask question here, so sorry if it is the not the proper place.

I would like to know if there is a command tool which would allow to set a signal strength threshold and capture all the moments where the signal is above that threshold (with timestamp). All this in a given frequency range.

The use case is that I would like to know when a device transmits over a quite long period (several hours).

I've looked at rx_tools/rx_power, we we cannot set the threshold trigger.

Thanks in advance.
Best regards,
Michael

**Comment by miek** [comment]
I don't know of any off-the-self tools to do it.
One option would be to write a GNURadio flowgraph for it. It should be possible using the 'Burst Tagger' and 'Tagged file sink' blocks.

**Comment by larkolab** [comment]
Hi @miek ,
Thank you for your answer, I'll have a look to gnuradio and see if I can manage to set it up. :)
Best regards,
Michael

**Comment by larkolab** [comment]
@miek Would you have a flowgraph example, I really don't know how to configure the Burst Tagger :/ And I'm not a signal processing expert, so lotss of unknown. :/
I have GRC running, and I'm able to see the signal with a QT GUI Sink. But then, from there, detecting the signal and logging, I have no idea how to configure this.

**Comment by miek** [comment]
Sure, here's an example:
![taggedfilesink](https://user-images.githubusercontent.com/578095/92800499-a6685000-f3ac-11ea-81f1-c2b3c46396d4.png)
That generates a signal with a varying amplitude and writes out a file for each period that it's above the threshold.

[taggedfilesink.zip](https://github.com/mossmann/hackrf/files/5204487/taggedfilesink.zip)

**Comment by larkolab** [comment]
@miek thank you very much !
