### ISSUE TITLE
Can a single HackRF perform RX/TX in GNURadio based on button press (PTT) 

### ISSUE THREAD

**Issue by metmayhem** [mossmann/hackrf#788]
I recently bought a hackrf and have been going through the lessons. I have a question and was told to ask it here. Is it possible in gnuradio to have a single HackRF flip back and forth between RX and TX using a button to establish PTT? I tried without any success so far, but thought maybe someone might have more information. Or maybe there is different software I should use?

**Comment by GravesJake** [comment]
Hi, sorry this fell through the cracks. Are you still having trouble accomplishing this? I personally haven't tried this but it should definitely be feasible.

**Comment by straithe** [comment]
There hasn't been a response on this issue for a while. Do you still have this question? If you don't respond within a month I will close this issue.

**Comment by metmayhem** [comment]
Yes, I'm still having trouble with this. I kind of set this one aside and have been working on other projects, but would really like to get this working, if possible. Any ideas or things to try would be appreciated.

**Comment by miek** [comment]
There was a talk recently at the GNURadio Amateur Radio Meetup where Gavin Jacobs went through his solution to this: https://www.youtube.com/watch?v=rTp6vQk5MqE

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
