### ISSUE TITLE
Two channels reception with one HackRF

### ISSUE THREAD

**Issue by NicolasDELLEAD** [mossmann/hackrf#802]
Hi, everyone!

I am trying to design a receiver able to record two radio stations on the same time. I am setting the number of channels equals to two and putting as device arguments "hackrf=0,nchan=2". However, I am receiving the following error message:

  File "/usr/lib/python3.7/site-packages/gnuradio/gr/top_block.py", line 111, in start
    top_block_start_unlocked(self._impl, max_noutput_items)
  File "/usr/lib/python3.7/site-packages/gnuradio/gr/runtime_swig.py", line 4534, in top_block_start_unlocked
    return _runtime_swig.top_block_start_unlocked(r, max_noutput_items)
RuntimeError: resolve_port: hierarchical block 'source_impl': output 1 is not connected internally

Any suggestions, ideas, solutions, corrections?

Thank you!

**Comment by miek** [comment]
I think this got solved on the mailing list: https://pairlist9.pair.net/pipermail/hackrf-dev/2020-October/002949.html

The reason for the error is that the HackRF only has one receive channel, and the option to enable multiple channels is meant for other osmosdr-supported devices.
