### ISSUE TITLE
Hi, i need to implement an anti-spoofing algoritm based for GPS signal, based on the GPS correlation of C/A code. The only way to work with GPS is to use GNSS-SDR? And in this case, how can I pick up the correlation signal from hackRF? Please, any advice are helpful!!

### ISSUE THREAD

**Issue by gianand** [mossmann/hackrf#809]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by mossmann** [comment]
Yes, you can receive GPS signals with [GNSS-SDR](https://gnss-sdr.org/). You may also be interested in [gps-sdr-sim](https://github.com/osqzss/gps-sdr-sim). Have fun!
