### ISSUE TITLE
What zadig do I use for  YardStjck one

### ISSUE THREAD

**Issue by matriarch-007** [mossmann/hackrf#812]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by mossmann** [comment]
Software questions related to YARD Stick One are best directed to [rfcat](https://github.com/atlas0fd00m/rfcat).
