### ISSUE TITLE
How to start YardStick One ???

### ISSUE THREAD

**Issue by matriarch-007** [mossmann/hackrf#813]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by mvaden78** [comment]
Unrelated question .sorry.
any chance the small holes on the yard stick can plug into  my hackRF to run it at full duplex rather then half.

**Comment by straithe** [comment]
> Unrelated question .sorry.
> any chance the small holes on the yard stick can plug into my hackRF to run it at full duplex rather then half.

No. These devices are not designed to plug into each other.

**Comment by straithe** [comment]
> ### Steps to reproduce
> 
> 
> ### Expected behaviour
> 
> Tell us what you expect should happen
> ### Actual behaviour
> 
> Tell us what happens instead
> ### Version information
> 
> **Operating system**:
> 
> **hackrf_info output:**
> 
> If you are reporting a problem that involves third party software
> (GNU Radio, Gqrx, etc), please report the version here.
> ### Output
> 
> ```
> Insert any commandline or build output here
> ```

Please check out the [RFCat Documentation](https://github.com/atlas0fd00m/rfcat). If you have further YARD Stick One questions please ask them on the [YARD Stick One Repo](https://github.com/greatscottgadgets/yardstick).
