### ISSUE TITLE
hackrfone wont detect in my pc

### ISSUE THREAD

**Issue by learn2hack-vishnu** [mossmann/hackrf#818]
while iam doing a firmware update .suddently my electricity gone .. 
after that  my hackrfone not detect in my linux and windows .. but power Led and ax led is working but other led's are not working .. 
please give me a solution

**Comment by straithe** [comment]
Have you tried DFU boot mode (https://github.com/mossmann/hackrf/wiki/Updating-Firmware)?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.

**Comment by learn2hack-vishnu** [comment]
Thanku .. i will.  Check
