### ISSUE TITLE
need technical specifications

### ISSUE THREAD

**Issue by ghost** [mossmann/hackrf#819]
Missing specifications:
- speed of panoramic analysis;
- the number of monitored channels;
- the minimum duration of the detected radio signal;

**Comment by draeath** [comment]
I get the sense you perhaps don't realize this is an SDR device? You give it a center frequency and sample rate, and it spits out I/Q pairs. It doesn't "understand" signals - that's done by software reading those I/Q pairs.

**Comment by straithe** [comment]
I'm closing this ticket as original poster has deleted their account.
