### ISSUE TITLE
HackRF One Spikes only and noise (PCB 13 February 2014)

### ISSUE THREAD

**Issue by yourSpace24** [mossmann/hackrf#827]
### Steps to reproduce
Using GQRX Version 2.11.5 to tune into some FM Radio signal got a channel here on 100mhz if i try to tune in i see the spike and noise nothing more.

### Expected behaviour
from the examples you should get some audio

### Actual behaviour
only noise on audio. 
![gqrx1](https://user-images.githubusercontent.com/76238791/107214350-85885180-6a55-11eb-8c54-2d7af9e7e1cb.png)
![gqrx2](https://user-images.githubusercontent.com/76238791/107214369-8b7e3280-6a55-11eb-877d-9dd9a0d3a747.png)

### Version information
**Operating system**:
Debian 10

**hackrf_info output:**
hackrf_info version: unknown
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Serial number: 000000000000000017c467dc2d1b47c3
Board ID Number: 2 (HackRF One)
Firmware Version: 2018.01.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x0061475e

**Operating system**:
If you are reporting a problem that involves third party software 
GQRX

### Output
```
Insert any commandline or build output here
```

**Comment by straithe** [comment]
I think you might be experiencing an issue with your antenna. If you can, please try swapping your antenna out for another. If you don't have an antenna you can use a straightened paperclip.

**Comment by yourSpace24** [comment]
I did and used a paperclip no change looks always the same. Is there maybe the amplifier fried ? the device was new unpacked it and just turned it on.

**Comment by straithe** [comment]
Can you send me two new screenshots, one where in the control tab of GQRX the RF is set to 0 and another where in the control tab of GQRX the RF is set to 14?

**Comment by yourSpace24** [comment]
sure
![rf0](https://user-images.githubusercontent.com/76238791/108004538-e14c6f00-7041-11eb-9211-39a0b4323108.png)
![rf14](https://user-images.githubusercontent.com/76238791/108004574-f7f2c600-7041-11eb-952b-b99a5f83e44e.png)

**Comment by straithe** [comment]
Are you able to pick up FM radio stations on any other radio receivers you may have?

**Comment by yourSpace24** [comment]
from my car radio just 5meter away yes.

**Comment by straithe** [comment]
Thank you for the extra information. It does look like you have a hardware failure. Please get in contact with the reseller that sold you your HackRF One and they will replace it for you.
