### ISSUE TITLE
Will DC Offset phantom spike pose a problem in survey with rtl_power?

### ISSUE THREAD

**Issue by noviceFedora** [mossmann/hackrf#832]
"The rtlsdr" dc offset varies because it's actually not really one single device due to multiple tuners and hardware versions, so comparing dc offsets is difficult, and more expensive transceiver like the ones sold by ADI obviously try to get rid of it. I suppose you could just search for "dc offset" in the rtlsdr subreddit, the reason why there is a faq entry is becausee this is the questions everyone new to sdr has been asking for the past 8 years.

That being said I don't see how you could verify anything beyond what the faq explains, considering that I'd just ensure you never see the signal you're looking for by adjusting the software you're using - but I'd suppress the dc offset as well to get around the usual dc offset question everyone asks...

_Originally posted by @Hoernchen in https://github.com/mossmann/hackrf/issues/826#issuecomment-770313768_

If I do a survey with rtl_power over the entire frequency range covered by HackRF One, will this DC Offset's phantom spike pollute the recording? 

And I didn't notice this DC Offset phantom spike in Sarah's videos. They are here:

https://www.youtube.com/watch?v=CTzWZnNtAJQ
https://www.youtube.com/watch?v=fuwW5ZNK_0Y
https://www.youtube.com/watch?v=4rpkVhBpYPM

**Comment by miek** [comment]
`rtl_power` is only for the rtlsdr dongles, so it doesn't support the HackRF.

The recommended option would be to use `hackrf_sweep`, which can output the same format as `rtl_power`. It automatically removes the DC spike from the output.

**Comment by noviceFedora** [comment]
> `rtl_power` is only for the rtlsdr dongles, so it doesn't support the HackRF.
> 
> The recommended option would be to use `hackrf_sweep`, which can output the same format as `rtl_power`. It automatically removes the DC spike from the output.

Okay.
