### ISSUE TITLE
Respin Hacker RF One Circuit Board

### ISSUE THREAD

**Issue by wgrefe** [mossmann/hackrf#836]
I was able to find the size of Hacker RF One is smaller at 120 mm x 75 mm (PCB size).  
Is the board truly 2.95276 inches wide and 4.72441 inches long?
The circuit board needs to fit in a 3” tube.  Is it possible to respin the board to be smaller width wise and shorter?

Sincerely,
William K Grefe
william.grefe@baesystems.com

**Comment by straithe** [comment]
Yes, the HackRF One PCB is 120mm x 75mm, and yes it could be made smaller with some design effort.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you want to discuss things further.
