### ISSUE TITLE
Is there anything can replace Sky13350_385LF?

### ISSUE THREAD

**Issue by TONJA233** [mossmann/hackrf#838]
### Steps to reproduce
1.Buy electronic components 
2.Solder electronic components

### Expected behaviour
Make a **HackRf One**

### Actual behaviour
I can't buy a **Sky13350_385LF**

  And last,thank you very much.

**Comment by markwhi** [comment]
These 3 parts look like they _might_ be drop-in replacements: https://www.digikey.com/short/8hhc91f7
