### ISSUE TITLE
tx problem

### ISSUE THREAD

**Issue by yyyy8334051** [mossmann/hackrf#855]
<img width="960" alt="未命名" src="https://user-images.githubusercontent.com/71495160/111751584-a43cfc00-88cf-11eb-9d1b-140f69f5f8ad.png">
  
it has some problems that i cant figure out.
it show Failed to open HackRF device (-5) HackRF not found and my TX of hackrf one  cant work
does someone can help me?

**Comment by straithe** [comment]
Can you show me the output of running `hackrf_info` on the command line?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
