### ISSUE TITLE
release no longer includes cpld in firmware-bin

### ISSUE THREAD

**Issue by ZeroChaos-** [mossmann/hackrf#858]
yes, I know that the hackrf code no longer expects the cpld to be flashed.  However, at this time, other code such as the portapack firmware does expect the cpld to be flashed.  

Is firmware/cpld/sgpio_if/default.xsvf the required file, or do I need to do something with it first?

**Comment by mossmann** [comment]
Yes, firmware/cpld/sgpio_if/default.xsvf is the correct file.

**Comment by ZeroChaos-** [comment]
thanks.  I can (and will) use this release as is, but you might want to copy the file to the firmware-bin for releases as was done previously.  There are likely to be use cases for having it, even though you have eliminated the need in the main firmware.  super excited about the release, thanks again for that!

**Comment by mossmann** [comment]
After confirming with @jboone that PortaPack also loads CPLD bitstreams into SRAM from the ARM firmware, I think it is safe to continue leaving the bitstream out of release packages.
