### ISSUE TITLE
multi-device support

### ISSUE THREAD

**Issue by mossmann** [mossmann/hackrf#87]
libhackrf and hackrf-tools should support multiple HackRF devices connected over USB.  It should be possible to select a particular device for a given operation.  It should be straightforward to use two HackRF devices together for full-duplex operation.

**Comment by hessu** [comment]
I grabbed Jared's branch and tried to polish it a bit. Feedback welcome in pull request #158.

**Comment by hessu** [comment]
@dominicgs merged pull request #158 yesterday, and multiple devices support is now in the git master branch. I'll submit the gr-osmosdr changes this weekend. They're now in my feature branch: https://github.com/hessu/gr-osmosdr/tree/feature/hackrf_multidev

**Comment by dominicgs** [comment]
This has been merged and in use for over a month now.  I think we can close this issue.
