### ISSUE TITLE
Error building gr-osmosdr with libhackrf

### ISSUE THREAD

**Issue by NicolasCaseau** [mossmann/hackrf#876]
Hello,

I'm trying to build gr-osmosdr with cmake using the following command (I'm working on a conda environnement) : 

cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DLIBHACKRF_INCLUDE_DIRS=/usr/include ../

The cmake command seems to work fine as the terminal tells me that it found the library for hackfr :

-- Checking for module 'libhackrf'
--   No package 'libhackrf' found
-- Found LibHackRF: /lib64/libhackrf.so  

The hackrf ils also in the enabled components after the cmake :

######################################################
-- # Gnuradio enabled components                         
-- ######################################################
--   * Python support
--   * IQ File Source & Sink
--   * RTLSDR TCP Client
--   * Ettus USRP Devices
--   * HackRF & rad1o Badge
--   * RFSPACE Receivers
--   * Red Pitaya SDR

However when I'm trying to use the "make" command I get the Following error : 

In file included from /home/Nicolas/gr-osmosdr/lib/source_impl.cc:60:
/home/Nicolas/gr-osmosdr/lib/hackrf/hackrf_source_c.h:29:10: fatal error: libhackrf/hackrf.h: No such file or directory
   29 | #include <libhackrf/hackrf.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

I already specified the -DLIBHACKRF_INCLUDE_DIRS and I don't really know what I could do to solve my problem. If someone has any idea on how I could do that I'm a taker. 

Thanks and have a good day :)

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
