### ISSUE TITLE
Not receiving FM with Hackrf One on GNUradio but can receive on SDR#?

### ISSUE THREAD

**Issue by shinobirain** [mossmann/hackrf#877]
Hi Everyone!

I recently started using the hackrf one on my windows 10 pc and have having issues with the first tutorial from great scotts in that I cannot seem to receive/see any of the FM signals I see in SDR#. Here is the link to the tutorial I am using with the time stamped right has hes about to run the project.

Below are some pictures that I have attached to show what I have going on right now in the project file.

![1](https://user-images.githubusercontent.com/54257350/115055292-46400c00-9eaf-11eb-86ac-20361b3388cd.png)
![2](https://user-images.githubusercontent.com/54257350/115055297-47713900-9eaf-11eb-9c07-da9a727b689f.png)
![3](https://user-images.githubusercontent.com/54257350/115055309-4b04c000-9eaf-11eb-8667-e589c33cc407.png)
![4](https://user-images.githubusercontent.com/54257350/115055315-4c35ed00-9eaf-11eb-91ea-cebeeb0d0ae4.png)

A few background things:

1. Currently running the 2021.03.1 Hackrf One Firmware and GNUradio 3.8

2. The command prompt does indicate warnings that say they are over written by something else that is very similarly titled (shown in the picture below). There are many more above; however, I'm not sure if that's effecting the output...?
![5](https://user-images.githubusercontent.com/54257350/115055380-58ba4580-9eaf-11eb-8479-a24ca69bc811.png)

I have also used SDR# with my Hackrf One and have been able to receive FM radio and listen to them as well.
![6](https://user-images.githubusercontent.com/54257350/115055397-5e179000-9eaf-11eb-8d86-3a65b36a24ac.png)

Thank you for your help and suggestions in advance!

**Comment by miek** [comment]
You have the gains set a bit higher in SDR#, so you could try increasing them in the osmocom source properties.
Also, try enabling some averaging in the QT GUI sink (~20 works well for me). That will make it easier to see the signals above the noise.

**Comment by shinobirain** [comment]
Hey Miek, 

  I apologize for the delayed reply, I have tried what you suggested and am still receiving the same results as shown in the photos above.

**Comment by straithe** [comment]
I suspect that there might be something wrong with gr-osmosdr. What is the output in the GNURadio Companion console when running the flow graph?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
