### ISSUE TITLE
No power on usb 

### ISSUE THREAD

**Issue by michaeltak** [mossmann/hackrf#881]
No power on USB.

**Comment by straithe** [comment]
Have you tried using a different cables?

**Comment by michaeltak** [comment]
yes tried it all  and 2 things on the pcb are broken... don't know how... Just felt off have this board for ages now...

**Comment by michaeltak** [comment]
![Screenshot_20210425_044448](https://user-images.githubusercontent.com/69692773/115978650-31373d00-a581-11eb-9a24-ac78a58e72bb.jpg)

**Comment by miek** [comment]
If those parts are missing, that would certainly explain the problem.
Could you post some photos of your board?

**Comment by michaeltak** [comment]
gonna make pics when home

**Comment by michaeltak** [comment]
![16195975430452580763168967492695](https://user-images.githubusercontent.com/69692773/116370029-4a9eea00-a80a-11eb-938d-69250ef86483.jpg)

**Comment by michaeltak** [comment]
![16195975921888637501862337289745](https://user-images.githubusercontent.com/69692773/116370132-61ddd780-a80a-11eb-9b69-56daf2071081.jpg)

**Comment by michaeltak** [comment]
never mind... can't find the problem... so it's for the bin...

**Comment by pickeditmate** [comment]
Looks like it's missing L10, and C146 and R52. Do you want a CSV of the parts and their values or do you have it already?

**Comment by michaeltak** [comment]
this I gonna order I hope this is it 


https://www.mouser.be/ProductDetail/963-LBM2016T4R7JV
https://www.mouser.be/ProductDetail/739-TYA2016104R7M-10
https://www.mouser.be/ProductDetail/581-04024D106MAT2A
https://www.mouser.be/ProductDetail/810-YFF18PC0J475M
https://www.mouser.be/ProductDetail/71-CRCW0603-49.9-E3

**Comment by straithe** [comment]
Please keep us updated!

**Comment by michaeltak** [comment]
the site charge sending cost to high ... cant fint the righjt parts for sure so
