### ISSUE TITLE
hackrf one does not react

### ISSUE THREAD

**Issue by smlyclts** [mossmann/hackrf#893]
### Steps to reproduce
1. not connecting to computer
2. only 3.3v led is on
3. not connecting to pc in dfu mode
4. 

### Expected behaviour
HackRF should be detected in PC. USB LED should glow

### Actual behaviour
only 3.3v led light is on

### Version information
windows 10, Linux

**hackrf_info output:**
Unable to connect to computer, hackrf info unknown

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
I am using clone hackrf one portapack h1 i connect power with power bank but portapack screen turned on and off

only 3.3v led light is on, i disconnected the portapack from hackrf and plugged it into the computer

this is how it shows up in device manager "unknown USB device (device descriptor request failed)"

i changed cable it because the  might be damaged, i changed the power supply, same result

I suspect a short circuit but I can't detect it, I don't have a thermal camera to find the heated part, but I found the heated part by trying a primitive method. I froze the card using lighter gas and then plugged in the usb cable and found the part where the ice melted
![IMG_20210530_113951sssss](https://user-images.githubusercontent.com/55598741/120098531-18e9ad80-c13f-11eb-9afc-5abdc74f88a1.jpg)
![IMG_20210530_114014](https://user-images.githubusercontent.com/55598741/120098534-1c7d3480-c13f-11eb-8562-1b3e1e89da7a.jpg)

I measured with the help of a voltmeter as in the photo

p3GND AND P8VCC = 3.29-3.3 volts

P3GND AND P1 1V8= 0.01volt
![IMG_20210530_111345](https://user-images.githubusercontent.com/55598741/120097508-809cfa00-c139-11eb-8af4-8905b83f4fd3.jpg)

![IMG_20210530_112903](https://user-images.githubusercontent.com/55598741/120097644-57309e00-c13a-11eb-8a34-10cf1ab0ea29.jpg)

What should I do, will this device work?
please i am waiting for your help

**Comment by straithe** [comment]
I suggest replacing or removing the TVS diode (U15) and seeing if that helps!

**Comment by smlyclts** [comment]
> TVS diyot (U15)

Where is the U15 diode? Where can I find a detailed dataset that will show the location of other components

**Comment by smlyclts** [comment]
when I examined the u15 I saw that it is usb (D - and D+), when I plug in the portapack it only gets DC (- and +) current with powerbank. I don't think it will work if I dismantle u15
![Ekran Görüntüsü (3)](https://user-images.githubusercontent.com/55598741/122878588-979dc900-d340-11eb-93ff-d58d038950a4.jpg)

**Comment by straithe** [comment]
Removing U15 does not remove the connection to the microcontroller. The connections you've highlighted don't just go up to U15, they also go right to R58 and R57 which lead to the microcontroller through 0 Ohm resistors which just make them wires. Please do try the recommended solution of removing or replacing U15 and let me know the results.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.

**Comment by smlyclts** [comment]
![WhatsApp Image 2021-09-20 at 14 09 59](https://user-images.githubusercontent.com/55598741/133993089-24035497-372a-4dcb-b91d-8555e3552f5b.jpeg)
 I took out the u15, the 3.3v led light is on, the computer is not responding, the portapack is not working

**Comment by straithe** [comment]
Conversation continues in #958 .
