### ISSUE TITLE
Can not control multiple OperaCake boards

### ISSUE THREAD

**Issue by Nzbu** [mossmann/hackrf#894]
I am using two HackRF One SDRs, each having their own OperaCake board connected. 
On one OperaCake, I've changed the address from default "24" to "28", using adequate pin headers, and the other one has the default "24" address. 

I wanted to control both of them, so I've tried starting the "hackrf_info" function, and there I get both of the SDRs IDs, serial numbers etc., along with the both Operacake boards detected (one at address 0x18,and the other one at the address 0x1c).

I've then then tried the "hackrf_operacake - l" command, and here I get only one board (24 or 28, depending on which one is at which usb port, but never both of them). 

I've also tried controlling them via "hackrf_operacake -o 24( or 28) -a POSITION - b POSITION", commands, but it also works only on one board. 
I've tried various usb ports, connecting and disconnecting usb devices, reseting the SDR, but nothing seems to work. 

From what I've gathered, it seems that only the board on the hackrf device that has the ID "hackrf 0" can be listed, or controlled, and the other one with ID "hackrf 1" can not. 

I would ask for your help on how can i control both Operacake boards from my terminal. 

I am using Ubuntu 20.04, and have the latest firmware on my SDRs (March 2021).

**Comment by gozu42** [comment]
what happens when you specify which hackRF to use with the -d option?
the -o option is mainly useful if you have multiple operacake connected to the same hackRF.
