### ISSUE TITLE
Opera Cake hardware availability?

### ISSUE THREAD

**Issue by unjordy** [mossmann/hackrf#900]
Are there any vendors currently selling complete hardware or bare PCBs for the Opera Cake add-on? Also, is the neapolitan full-duplex add-on in this repo finished, and has anyone successfully made one?

**Comment by mossmann** [comment]
We at Great Scott Gadgets will be selling Opera Cake soon. We have manufacturing in progress but waiting for arrival of some of the components. We do not currently have any plans to manufacture Neapolitan as we encountered difficulties with CPLD/firmware in that project.
