### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by modarken** [mossmann/hackrf#904]
I am trying to get our company to use SDRs (HackRF). I will eventually need to process and send data from one of our services in C#. I was hoping to have a good place to start by looking at the source code for SDRSharp but it seems we can only make plugins? 

Q: Why is the source code for SDR# not available? If it is I apologise, I can't find it. I did find what appeared to be an old version on github in a different library but not the modern version on airspy.

**Comment by straithe** [comment]
SDR# is not software created by Great Scott Gadgets, as you've mentioned. SDR# is an Airspy product. If you have questions about SDR# and how that source code is managed you will want to reach out to Airspy. 

If you have more general questions about transferring your data from one of your services in C# you may want to join our [Discord Server](https://discord.gg/rsfMw3rsU8) to see if anyone in our community has suggestions.
