### ISSUE TITLE
hackrf_sweep -r flag not available, cannot generate output file

### ISSUE THREAD

**Issue by suciokhan** [mossmann/hackrf#909]
### Steps to reproduce
1.On command line in Ubuntu 20.04, run `hackrf_sweep -f 2400:2490 -r output.csv`
2. Receive error message `hackrf_sweep: invalid option -- 'r'`

### Expected behaviour
I anticipated the ability to generate an output file, as documented here: https://hackrf.readthedocs.io/en/latest/hackrf_sweep.html#usage

```
[-h] # this help
[-d serial_number] # Serial number of desired HackRF
[-a amp_enable] # RX RF amplifier 1=Enable, 0=Disable
[-f freq_min:freq_max] # minimum and maximum frequencies in MHz
[-p antenna_enable] # Antenna port power, 1=Enable, 0=Disable
[-l gain_db] # RX LNA (IF) gain, 0-40dB, 8dB steps
[-g gain_db] # RX VGA (baseband) gain, 0-62dB, 2dB steps
[-n num_samples] # Number of samples per frequency, 8192-4294967296
[-w bin_width] # FFT bin width (frequency resolution) in Hz
[-1] # one shot mode
[-B] # binary output
[-I] # binary inverse FFT output
-r filename # output file
```

### Actual behaviour
The -r flag for creating an output file is not available, nor does the -h flag reveal any alternatives to this.

### Version information
**hackrf_info output:**
hackrf_info version: unknown
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000088869dc3958851b
Board ID Number: 2 (HackRF One)
Firmware Version: 2021.03.1 (API:1.04)
Part ID Number: 0xa000cb3c 0x006f4f7d

### Output
```
hackrf_sweep -f 2400:2490 -r output.csv
hackrf_sweep: invalid option -- 'r'
Usage:
	[-h] # this help
	[-d serial_number] # Serial number of desired HackRF
	[-a amp_enable] # RX RF amplifier 1=Enable, 0=Disable
	[-f freq_min:freq_max] # minimum and maximum frequencies in MHz
	[-p antenna_enable] # Antenna port power, 1=Enable, 0=Disable
	[-l gain_db] # RX LNA (IF) gain, 0-40dB, 8dB steps
	[-g gain_db] # RX VGA (baseband) gain, 0-62dB, 2dB steps
	[-n num_samples] # Number of samples per frequency, 16384-4294967296
	[-w bin_width] # FFT bin width (frequency resolution) in Hz
	[-1] # one shot mode
	[-B] # binary output

Output fields:
	date, time, hz_low, hz_high, hz_bin_width, num_samples, dB, dB, . . .

```

**Comment by miek** [comment]
The `-r` flag was introduced in the latest version of the host tools (v2021.03.1) but Ubuntu 20.04 packages an older version.

As a workaround you can pipe the output to a file instead: `hackrf_sweep -f 2400:2490 > output.csv`, or install the newer host tools from source (you might need to do this anyway to match the firmware version you have installed).
