### ISSUE TITLE
hackrf_transfer replay failure

### ISSUE THREAD

**Issue by mossmann** [mossmann/hackrf#91]
Waveforms captured with hackrf_transfer (RX) don't seem to be reproduced properly when replayed by hackrf_transfer (TX).  See http://nine.pairlist.net/pipermail/hackrf-dev/2013-July/000110.html

**Comment by gusevargas** [comment]
Hi, I have observed similar behavior. I'm running Ubuntu 18.04 and I have an RTL-SDR and the HackrF One both in separate USB ports.  Using gnuRadio-companion to receive the signal, and the Hackrf_One to transmit the signal (file) either an .s8 or .f32 format.
In either case, as soon as I execute the command, I get the hackrf_open() failed: Resource busy (-1000)

**Comment by dennisdebel** [comment]
Ii record a signal on 137Mhz and when I play it back its offset (and garbled)..weird
