### ISSUE TITLE
USB C

### ISSUE THREAD

**Issue by tomveich** [mossmann/hackrf#918]
Hello, I know that there are already some closed tickets about USB type C, but I don't think it would be a bad idea.

I wrote  few points why migrating to USB type C could benefit HackRF and the users:

- Convenience - Hardware manufacturers are slowly migrating towards USB type C ports. New Android phones already dispose with such ports, Apple is integrating USB type C in majority their products including laptops. Other laptop manufacturers are also adding USB type C ports to their devices.
- Cost - Having one cable capable of charging phone, transferring data or connecting a SDR reduces the cost for end users. 
-  Symmetry - USB type C has rotationally symmetrical connector.
-  Durability - Type C connectors are more durable
- Speed - 10 to 20 times more data could be transferred
- Power - USB type C can deliver up to 100W

Thank you! 😊

**Comment by straithe** [comment]
Thank you for your suggestion!
