### ISSUE TITLE
spiflash crashes when byte count exceeds 131072

### ISSUE THREAD

**Issue by JDogHerman** [mossmann/hackrf#92]
When running the spiflash command and setting the length to be output to a file, if you set the bytes requested as 131073 or more the application says...

Reading 256 bytes from 0x01fd00.
Reading 256 bytes from 0x01fe00.
Reading 256 bytes from 0x01ff00.
Reading 1 bytes from 0x020000.

and then Halts.

Terminating the program and trying with a smaller number or any other hackrf command shows the error...

hackrf_open() failed: HACKRF_ERROR_LIBUSB (-1000)

After removing and adding the USB plug, the HackRF will respond to other commands.

I found this error using Win7 64bit

**Comment by mossmann** [comment]
This doesn't seem to be a problem anymore.  We've been using 1048576 as the default size since a062596.
