### ISSUE TITLE
Lightning damage 

### ISSUE THREAD

**Issue by Mike-G1SBN** [mossmann/hackrf#922]
### Steps to reproduce
1.Mother nature not co-operating(fortunately)
2.Tick box for receive pre-amp causes signal decrease when trying to use the pre-amp.
3.

### Expected behaviour
Signal should increase when tick set in HDSDR EXTIO.DLL box

### Actual behaviour
Signal now decreases to unusable when pre-amp enabled.

### Version information
**Operating system**:not relevant. Problem also happens with SDR#

**hackrf_info output:**
I suspect the surge protector did not do its job but which component has been damaged?
I want to know which to replace, the SKY13317 switch or the MGA-81563 RF amp?

### Output
`hackrf_info version: 2018.01.1
libhackrf version: 2018.01.1 (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000a06063c82530375f
Board ID Number: 2 (HackRF One)
Firmware Version: 2017.02.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x00554755
``
Insert any commandline or build output here
```

**Comment by straithe** [comment]
It is possible that other components suffered damage, but you will most certainly need to replace the MGA-81563 RF amp.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
