### ISSUE TITLE
github wiki gone?

### ISSUE THREAD

**Issue by draeath** [mossmann/hackrf#928]
The [github wiki](https://github.com/mossmann/hackrf/wiki/) is no longer accessible - attempts to access it redirect to the top of the repo.

Was this removed? If so, where can we find the documentation now?

### Steps to reproduce
N/A

### Expected behaviour
N/A

### Actual behaviour
N/A

### Version information
N/A

### Output
N/A

**Comment by straithe** [comment]
The information is in the repo README. Documentation is now at hackrf.rtfd.io.

**Comment by draeath** [comment]
Ah, I see it in #21c99a36a61911a3d075c09d4dd7b9e30ad36ec4 - thanks.
