### ISSUE TITLE
cannot open hackrf device is the device locked somewhere

### ISSUE THREAD

**Issue by gaspar1987** [mossmann/hackrf#938]
How we can repair the to hackrf one repair the pitole usb not work on pc the hackrf has led green 3V3.

Please give me the tool that could fix it if you can help me fix it that would be nice

**Comment by straithe** [comment]
I would like to help but I am not certain that I understand what you are asking for. Are you asking for a tool to open the case that goes around a HackRF? Can you provide a picture?

**Comment by gaspar1987** [comment]
the problem comes from the buttons when I try to restart it does not restart and this is the image it tells me that I give you .it doesn't plug into my computer### 
![WIN_20210823_19_02_30_Pro](https://user-images.githubusercontent.com/13591469/130487770-b53d9bad-05da-4c6b-8f36-2765cd7f0422.jpg)

**Comment by straithe** [comment]
I don't think I'm familiar with this case. 

What doesn't plug into your computer?

**Comment by gaspar1987** [comment]
hello I would like to know if there is a software to reformat it

**Comment by gaspar1987** [comment]
thank you for your help

**Comment by straithe** [comment]
The documentation for HackRF is here: https://hackrf.readthedocs.io/en/latest/

**Comment by gaspar1987** [comment]
what I need to download on I don't understand

**Comment by straithe** [comment]
I'm sorry. I still don't understand what you are asking for. All of the HackRF software is available in this repository. All the information you need should be in the documentation that I have linked.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.

**Comment by Janxyxy** [comment]
![Image](https://github.com/user-attachments/assets/15642d89-3c7c-4234-a8a7-5f707a16d439)
I got this error in AIRSPY SDR when connecting HackRF one.

**Comment by martinling** [comment]
@Janxyxy  This normally means that some other program still has the HackRF device open.

If you're still having trouble please open your own issue rather than commenting on old closed ones.
