### ISSUE TITLE
downgrade hackrf firmware

### ISSUE THREAD

**Issue by juankr10s** [mossmann/hackrf#949]
how to downgrade firmware hackrf one to 2018.01.01?
i have a ezp210 programmer eeprom and i think erase and send 2018.01.01 hackrf_one_usb.bin to  eeprom windbond 25q80dvsig
what is the correct procedure to downgrade hackrf one in linux system?
```

**Comment by miek** [comment]
You can follow the normal process for flashing firmware described here: https://hackrf.readthedocs.io/en/latest/updating_firmware.html
It'll work just fine for doing a downgrade too.

**Comment by juankr10s** [comment]
ok, I'll try the indicated method.
now I will close the ticket and later I will comment on the results
Thank you so much
