### ISSUE TITLE
hackrf one does not react

### ISSUE THREAD

**Issue by smlyclts** [mossmann/hackrf#958]
Steps to reproduce
not connecting to computer
only 3.3v led is on
not connecting to pc in dfu mode
Expected behaviour
HackRF should be detected in PC. USB LED should glow

Actual behaviour
only 3.3v led light is on

Version information
windows 10, Linux

hackrf_info output:
Unable to connect to computer, hackrf info unknown

If you are reporting a problem that involves third party software
(GNU Radio, Gqrx, etc), please report the version here.

Output
I am using clone hackrf one portapack h1 i connect power with power bank but portapack screen turned on and off

only 3.3v led light is on, i disconnected the portapack from hackrf and plugged it into the computer

this is how it shows up in device manager "unknown USB device (device descriptor request failed)"

i changed cable it because the might be damaged, i changed the power supply, same result

I suspect a short circuit but I can't detect it, I don't have a thermal camera to find the heated part, but I found the heated part by 

trying a primitive method. I froze the card using lighter gas and then plugged in the usb cable and found the part where the ice melted

![WhatsApp Image 2021-09-20 at 14 09 59](https://user-images.githubusercontent.com/55598741/133993856-a275058e-85bf-4896-a9b4-e250f3422915.jpeg)
![120098534-1c7d3480-c13f-11eb-8562-1b3e1e89da7a](https://user-images.githubusercontent.com/55598741/133993889-b43ff4cd-9015-4bcd-b9f2-394590e8842b.jpg)
![120098531-18e9ad80-c13f-11eb-9afc-5abdc74f88a1](https://user-images.githubusercontent.com/55598741/133993901-e33fe5d5-b73c-4d92-a660-e40688aabd08.jpg)

**Comment by smlyclts** [comment]
I removed u15 with Straithe suggestion and got no result
![WhatsApp Image 2021-09-20 at 14 09 59](https://user-images.githubusercontent.com/55598741/133994201-df7f84a0-24e0-4956-a0df-4e1962d7ba4e.jpeg)
s

**Comment by straithe** [comment]
I'm sorry but this does look like a hardware problem and this board does not look like a Great Scott Gadgets produced HackRF. I suggest contacting your seller to see if they will send you a replacement.
